return {
	["date"]= 20130630, 
	["keybinds"]= {
		{"epic_chili_minimap_alwaysdisplaymexes", "f4"}, 
		{"epic_chili_widget_selector_widgetlist", "f11"}, 
		{"togglecammode", "Shift+backspace"}, 
		{"edit_backspace", "Any+backspace"}, 
		{"edit_complete", "Any+tab"}, 
		{"chatally", "Alt+enter"}, 
		{"chatswitchally", "Alt+enter"}, 
		{"chatall", "Ctrl+enter"}, 
		{"chatswitchall", "Ctrl+enter"}, 
		{"chatspec", "Shift+enter"}, 
		{"chatswitchspec", "Shift+enter"}, 
		{"chat", "Any+enter"}, 
		{"edit_return", "Any+enter"}, 
		{"pause", "pause"}, 
		{"crudemenu", "esc"}, 
		{"exitwindow", "s+escape"}, 
		{"quitforce", "Ctrl+Shift+esc"}, 
		{"edit_escape", "Any+escape"}, 
		{
			"speedup", 			{"Any++", "Any+=", "Any+numpad+"}, 
		}, 
		{"prevmenu", ","}, 
		{"decguiopacity", "Shift+,"}, 
		{
			"slowdown", 			{"Any+-", "Any+numpad-"}, 
		}, 
		{"nextmenu", "."}, 
		{"incguiopacity", "Shift+."}, 
		{"specteam 9", "0"}, 
		{"specteam 19", "Ctrl+0"}, 
		{"group0", "Any+0"}, 
		{"specteam 0", "1"}, 
		{"specteam 10", "Ctrl+1"}, 
		{"group1", "Any+1"}, 
		{"specteam 1", "2"}, 
		{"specteam 11", "Ctrl+2"}, 
		{"group2", "Any+2"}, 
		{"specteam 2", "3"}, 
		{"specteam 12", "Ctrl+3"}, 
		{"group3", "Any+3"}, 
		{"specteam 3", "4"}, 
		{"specteam 13", "Ctrl+4"}, 
		{"group4", "Any+4"}, 
		{"specteam 4", "5"}, 
		{"specteam 14", "Ctrl+5"}, 
		{"group5", "Any+5"}, 
		{"specteam 5", "6"}, 
		{"specteam 15", "Ctrl+6"}, 
		{"group6", "Any+6"}, 
		{"specteam 6", "7"}, 
		{"specteam 16", "Ctrl+7"}, 
		{"group7", "Any+7"}, 
		{"specteam 7", "8"}, 
		{"specteam 17", "Ctrl+8"}, 
		{"group8", "Any+8"}, 
		{"specteam 8", "9"}, 
		{"specteam 18", "Ctrl+9"}, 
		{"group9", "Any+9"}, 
		{
			"buildfacing inc", 			{"Any+insert", "[", "Shift+["}, 
		}, 
		{
			"drawinmap", 			{"Any+\\", "Any+`", "Any+0xa7"}, 
		}, 
		{
			"buildfacing dec", 			{"Any+delete", "]", "Shift+]"}, 
		}, 
		{"attack", "a"}, 
		{"areaattack", "Alt+a"}, 
		{"debugcolvol", "Alt+b"}, 
		{"selfd", "C+d"}, 
		{"selectcomm", "ctrl+c"}, 
		{"manualfire", "d"}, 
		{"oneclickwep", "d"}, 
		{"reclaim", "e"}, 
		{"fight", "f"}, 
		{"forcestart", "Alt+f"}, 
		{"guard", "None"}, 
		{"sharedialog", "h"}, 
		{"gameinfo", "Any+i"}, 
		{"cloak", "k"}, 
		{"togglelos", "l"}, 
		{"loadunits", "l"}, 
		{"morph", "m"}, 
		{"singlestep", "Alt+o"}, 
		{"patrol", "p"}, 
		{"groupclear", "Shift+q"}, 
		{"repair", "r"}, 
		{"stop", "s"}, 
		{"unloadunits", "u"}, 
		{"pastetext", "Ctrl+v"}, 
		{"buildunit_cormex", "w"}, 
		{"wait", "ctrl+w"}, 
		{"areamex", "w"}, 
		{"onoff", "o"}, 
		{"buildspacing dec", "Any+x"}, 
		{"buildspacing inc", "Any+z"}, 
		{"edit_delete", "Any+delete"}, 
		{"edit_prev_line", "Any+up"}, 
		{"moveforward", "Any+up"}, 
		{"edit_next_line", "Any+down"}, 
		{"moveback", "Any+down"}, 
		{"edit_end", "Any+end"}, 
		{"edit_next_word", "Ctrl+right"}, 
		{"edit_next_char", "Any+right"}, 
		{"moveright", "Any+right"}, 
		{"edit_home", "Any+home"}, 
		{"edit_prev_word", "Ctrl+left"}, 
		{"edit_prev_char", "Any+left"}, 
		{"moveleft", "Any+left"}, 
		{"increaseviewradius", "home"}, 
		{"decreaseviewradius", "end"}, 
		{"moveup", "Any+pageup"}, 
		{"movedown", "Any+pagedown"}, 
		{"showelevation", "f1"}, 
		{"viewfps", "C+f1"}, 
		{"showpathtraversability", "f2"}, 
		{"viewta", "C+f2"}, 
		{"lastmsgpos", "f3"}, 
		{"viewtw", "C+f3"}, 
		{"showmetalmap", "None"}, 
		{"viewrot", "C+f4"}, 
		{"viewfree", "C+f5"}, 
		{"HideInterface", "Any+f5"}, 
		{"NoSound", "Any+f6"}, 
		{"DynamicSky", "Any+f7"}, 
		{"savegame", "Ctrl+Shift+f8"}, 
		{"luaui showhealthbars", "f9"}, 
		{"showhealthbars", "Any+f9"}, 
		{"createvideo", "Ctrl+Shift+f10"}, 
		{"luaui tweakgui", "C+f11"}, 
		{"screenshot", "f12"}, 
		{"movefast", "Any+shift"}, 
		{"moveslow", "Any+ctrl"}, 
		{"resurrect", "t"}, 
		{"controlunit", "alt+v"}, 
		{"jump", "j"}, 
		{"select AllMap++_ClearSelection_SelectAll+", "ctrl+a"}, 
		{"select AllMap+_Builder_Not_Building_Not_Transport_Idle+_ClearSelection_SelectAll+", "ctrl+b"}, 
		{"select AllMap+_Not_Builder_Not_Building_Not_Commander_Not_Transport_Not_Aircraft_Weapons+_ClearSelection_SelectAll+", "ctrl+g"}, 
		{"select AllMap+_Not_Builder_Not_Building_Not_Commander_Not_Transport_Aircraft_NameContain_Stiletto+_ClearSelection_SelectAll+", "ctrl+h"}, 
		{"select PrevSelection+_Not_RelativeHealth_50+_ClearSelection_SelectAll+", "ctrl+t"}, 
		{"select Visible+_InPrevSel+_ClearSelection_SelectAll+", "ctrl+x"}, 
		{"select AllMap+_Not_Builder_Not_Building_Not_Commander_Not_Transport_Not_Aircraft_Weapons_WeaponRange_600+_ClearSelection_SelectAll+", "ctrl+y"}, 
		{"select AllMap+_Builder_Idle+_ClearSelection_SelectOne+", "z"}, 
		{"select AllMap+_InPrevSel_Not_Builder+_ClearSelection_SelectAll+", "ctrl+z"}, 
		{"epic_chili_integral_menu_tab_factory", "n"}, 
		{"epic_chili_integral_menu_tab_economy", "x"}, 
		{"epic_chili_integral_menu_tab_defence", "c"}, 
		{"epic_chili_integral_menu_tab_special", "v"}, 
		{"markingmenu", "b"}, 
		{"settarget", "t"}, 
		{"canceltarget", "y"}, 
		{"epic_combo_overhead/free_camera_(experimental)_overviewmode", "tab"}, 
		{"epic_combo_overhead/free_camera_(experimental)_follow", "alt+l"}, 
		{"epic_combo_overhead/free_camera_(experimental)_trackmode", "alt+t"}, 
		{"epic_combo_overhead/free_camera_(experimental)_thirdpersontrack", "alt+k"}, 
		{"select PrevSelection+_Not_RelativeHealth_30+_ClearSelection_SelectAll+", "ctrl+e"}, 
		{"select AllMap+_Not_Builder_Not_Building_Not_Transport_Aircraft_Weapons_Not_NameContain_Vamp_Not_Radar+_ClearSelection_SelectAll+", "ctrl+f"}, 
		{"select AllMap+_NameContain_Vamp+_ClearSelection_SelectAll+", "ctrl+g"}, 
		{"select PrevSelection+_Idle+_ClearSelection_SelectAll+", "ctrl+i"}, 
		{"select AllMap+_Not_Builder_Not_Building+_ClearSelection_SelectAll+", "ctrl+r"}, 
		{"select AllMap+_Not_Builder_Not_Building_Not_Transport_Aircraft_Radar+_ClearSelection_SelectAll+", "ctrl+s"}, 
		{"select AllMap+_Not_Builder_Not_Building_Transport_Aircraft+_ClearSelection_SelectAll+", "ctrl+t"}, 
		{"select AllMap+_InPrevSel+_ClearSelection_SelectAll+", "ctrl+z"}, 
		{"priority", "q"}, 
		{"areaguard", "g"}, 
		{"showeco", "f4"}, 
		{"epic_chili_gesture_menu_markingmenu", "b"}, 
		{"move", "m"}, 
		{"epic_settings/hud_panels/integral_menu_integral_menu...", "None"}, 
		{"debug", "Alt+n"}, 
		{"select AllMap+_Builder_Not_Building_Idle+_ClearSelection_SelectOne+", "ctrl+v"}, 
		{"crudesubmenu", "f10"}, 
		{"epic_defense_range_zero-k_enemyground", "C+o"}, 
		{"epic_defense_range_zero-k_enemyair", "C+o"}, 
		{"screenshot jpg", "C+f12"}, 
		{"epic_chili_pro_console_test_defaultallychat", "f8"}, 
		{"epic_chili_pro_console_enableconsole", "f8"}, 
		{"placebeacon", "d"}, 
		{"toggleoverview", "Tab"}, 
		{"track", "Alt+T"}, 
	}, 
}