--ID,Code,Name,XpCost,Level,RequiredID,Type,Morph,MaxCount,Limit,Chassis,Metal,Metal2,Metal3,Metal4
local unlocks = {
	[1] = {
		code = "corcom",
		name = "Battle Commander",
		xp = 350,
		level = 5,
		type = "Chassis",
		maxCount = 1,
		morphCost = {300,900,600},
	},
	[2] = { 
		code = "commrecon", 
		name = "Recon Commander",
		xp = 350,
		level = 6,
		type = "Chassis",
		morphCost = {300,900,600},
	},
	[3] = {  
		code = "commsupport", 
		name = "Support Commander",
		xp = 350,
		level = 6,
		type = "Chassis",
		morphCost = {300,900,600},
	},
	[4] = {  
		code = "factoryjump", 
		name = "Jumpjet/Specialist Plant",
		xp = 150,
		level = 2,
		type = "Unit",
	},
	[5] = {  
		code = "screamer", 
		name = "Screamer",
		xp = 250,
		level = 5,
		type = "Unit",
	},
	[6] = {  
		code = "armcsa", 
		name = "Athena",
		xp = 250,
		level = 5,
		type = "Unit",
	},
	[8] = {  
		code = "factorytank", 
		name = "Heavy Tank Factory",
		xp = 200,
		level = 3,
		type = "Unit",
	},
	[11] = {  
		code = "factoryplane", 
		name = "Airplane Plant",
		xp = 150,
		level = 2,
		type = "Unit",
	},
	[33] = {  
		code = "corcrw", 
		name = "Krow",
		xp = 350,
		level = 6,
		type = "Unit",
	},
	[37] = {  
		code = "armbanth", 
		name = "Bantha",
		xp = 500,
		level = 8,
		requiredID = 6,
		type = "Unit",
	},
	[38] = {  
		code = "gorg", 
		name = "Jugglenaut",
		xp = 500,
		level = 8,
		requiredID = 6,
		type = "Unit",
	},
	[39] = {  
		code = "armorco", 
		name = "Detriment",
		xp = 750,
		level = 10,
		requiredID = 6,
		type = "Unit",
	},
	[40] = {  
		code = "cafus", 
		name = "Singularity Reactor",
		xp = 400,
		level = 6,
		type = "Unit",
	},
	[41] = {  
		code = "armanni", 
		name = "Annihilator",
		xp = 250,
		level = 7,
		type = "Unit",
	},
	[42] = {  
		code = "cordoom", 
		name = "Doomsday Machine",
		xp = 250,
		level = 7,
		type = "Unit",
	},
	[43] = {  
		code = "corbhmth", 
		name = "Behemoth",
		xp = 300,
		level = 8,
		type = "Unit",
	},
	[45] = {  
		code = "mahlazer", 
		name = "Starlight",
		xp = 1000,
		level = 10,
		type = "Unit",
	},
	[47] = {  
		code = "module_ablative_armor", 
		name = "Ablative Armor Plates",
		xp = 250,
		level = 5,
		type = "Module",
		morph = 1,
		limit = 8,
		cost = 175,
	},
	[48] = {  
		code = "commweapon_shotgun", 
		name = "Shotgun",
		xp = 250,
		level = 5,
		type = "Weapon",
		morph = 1,
		limit = 2,
		cost = 100,
	},	
	[49] = {  
		code = "armcom", 
		name = "Strike Commander",
		xp = 200,
		level = 5,
		type = "Chassis",
		morphCost = {300,900,600},
	},
	[50] = {  
		code = "commweapon_rocketlauncher", 
		name = "Rocket Launcher",
		xp = 350,
		level = 6,
		type = "Weapon",
		morph = 1,
		limit = 2,
		chassis = {armcom = true, corcom = true,},
		cost = 150,
	},
	[51] = {  
		code = "commweapon_heavymachinegun", 
		name = "Heavy Machine Gun",
		xp = 300,
		level = 6,
		type = "Weapon",
		morph = 1,
		limit = 2,
		chassis = {armcom = true, corcom = true, commrecon = true},
		cost = 100,
	},	
	[53] = {  
		code = "module_high_power_servos", 
		name = "High Power Servos",
		xp = 250,
		level = 6,
		type = "Module",
		morph = 1,
		limit = 8,
		cost = 200,
	},	
	[55] = {  
		code = "module_adv_nano", 
		name = "CarRepairer's Nanolathe",
		xp = 200,
		level = 5,
		type = "Module",
		morph = 1,
		limit = 8,
		cost = 150,
	},	
	[56] = {  
		code = "module_fieldradar", 
		name = "Field Radar Module",
		xp = 300,
		level = 5,
		type = "Module",
		morph = 1,
		limit = 1,
		cost = 75,
	},	
	[59] = {  
		code = "armbrtha", 
		name = "Big Bertha",
		xp = 350,
		level = 8,
		type = "Unit",
	},
	[60] = {  
		code = "commweapon_gaussrifle", 
		name = "Gauss Rifle",
		xp = 250,
		level = 5,
		type = "Weapon",1,2,
		chassis = {armcom = true, corcom = true, commsupport = true,},
		cost = 75,
	},	
	[61] = {  
		code = "commweapon_heatray", 
		name = "Heat Ray",
		xp = 350,
		level = 7,
		type = "Weapon",
		morph = 1,
		limit = 2,
		chassis = {corcom = true, commrecon = true,},
		cost = 125,
	},	
	[62] = {  
		code = "commweapon_beamlaser", 
		name = "Beam Laser",
		xp = 200,
		level = 5,
		type = "Weapon",
		morph = 0,
		limit = 2,
		cost = 50,
	},	
	[63] = {  
		code = "conversion_shockrifle", 
		name = "Shock Rifle Conversion",
		xp = 400,
		level = 7,
		requiredID = 60,
		type = "Module",
		morph = 3,
		limit = 2,
		chassis = { commsupport = true },
		cost = 450,
	},	
	[64] = {  
		code = "commweapon_slowbeam", 
		name = "Slow Beam",
		xp = 300,
		level = 6,
		type = "Weapon",
		morph = 1,
		limit = 2,
		chassis = {armcom = true, corcom = true, commsupport = true,},
		cost = 100,
	},	
	[65] = {  
		code = "corgol", 
		name = "Goliath",
		xp = 200,
		level = 4,
		requiredID = 8,
		type = "Unit",
	},
	[66] = {  
		code = "armcybr", 
		name = "Licho",
		xp = 250,
		level = 6,
		requiredID = 11,
		type = "Unit",
	},
	[67] = {  
		code = "module_jammer",
		name = "Radar Jammer",
		xp = 400,
		level = 5,
		type = "Module",
		morph = 2,
		limit = 1,
		chassis = {armcom = true, corcom = true, commsupport = true,},
		cost = 175,
	},	
	[68] = {  
		code = "module_energy_cell", 
		name = "Energy Cell",
		xp = 200,
		level = 5,
		type = "Module",
		morph = 1,
		limit = 8,
		cost = 250,
	},	
	[69] = {  
		code = "conversion_disruptor", 
		name = "Disruptor Beam Conversion",
		xp = 350,
		level = 7,
		requiredID = 64,
		type = "Module",
		morph = 2,
		limit = 2,
		chassis = {commrecon = true, commsupport = true,},
		cost = 150,
	},	
	[70] = {  
		code = "commweapon_riotcannon", 
		name = "Riot Cannon",
		xp = 250,
		level = 5,
		type = "Weapon",1,2,
		chassis = {armcom = true, corcom = true,},
		cost = 100,
	},
	[71] = {  
		code = "armcarry", 
		name = "Reef",
		xp = 300,
		level = 5,
		type = "Unit",
	},
	[72] = {  
		code = "module_cloak_field", 
		name = "Cloaking Field",600,9,67,
		type = "Module",
		morph = 3,
		limit = 1,
		chassis = {armcom = true, commsupport = true},
		cost = 700,
	},	
	[73] = {  
		code = "weaponmod_standoff_rocket", 
		name = "Standoff Rocket",
		xp = 500,
		level = 7,
		requiredID = 50,
		type = "Module",
		morph = 2,
		limit = 1,
		cost = 450,
	},	
	[74] = {  
		code = "module_areashield", 
		name = "Area Shield",
		xp = 400,
		level = 7,
		type = "Module",
		morph = 3,
		limit = 1,
		chassis = {corcom = true, commsupport = true},
		cost = 400,
	},
	[75] = {  
		code = "weaponmod_autoflechette", 
		name = "Autoflechette",
		xp = 400,
		level = 7,
		requiredID = 48,
		type = "Module",
		morph = 2,
		limit = 1,
		chassis = {corcom = true, commrecon = true,},
		cost = 450,
	},	
	[76] = {  
		code = "module_adv_targeting", 
		name = "Advanced Targeting System",
		xp = 250,
		level = 6,
		type = "Module",
		morph = 1,
		limit = 8,
		cost = 150,
	},	
	[77] = {  
		code = "commweapon_concussion", 
		name = "Concussion Shell",
		xp = 450,
		level = 8,
		type = "Weapon",
		morph = 3,
		limit = 1,
		chassis = {commrecon = true, commsupport = true,},
		cost = 75,
	},	
	[78] = {  
		code = "commweapon_clusterbomb", 
		name = "Cluster Bomb",
		xp = 450,
		level = 9,
		type = "Weapon",
		morph = 3,
		limit = 1,
		chassis = {armcom = true, corcom = true},
		cost = 75,
	},	
	[79] = {  
		code = "commweapon_disruptorbomb", 
		name = "Disruptor Bomb",
		xp = 500,
		level = 10,
		type = "Weapon",
		morph = 3,
		limit = 1,
		chassis = {commrecon = true, commsupport = true,},
		cost = 125,
	},	
	[82] = {  
		code = "commweapon_sunburst", 
		name = "Sunburst Cannon",
		xp = 500,
		level = 9,
		type = "Weapon",
		morph = 3,
		limit = 1,
		chassis = {armcom = true, corcom = true, commsupport = true},
		cost = 250,
	},	
	[83] = {  
		code = "commweapon_napalmgrenade", 
		name = "Hellfire Grenade",
		xp = 400,
		level = 8,
		type = "Weapon",
		morph = 3,
		limit = 1,
		chassis = {corcom = true, commrecon = true,},
		cost = 50,
	},	
	[84] = {  
		code = "module_heavy_armor", 
		name = "High Density Plating",
		xp = 300,
		level = 7,
		requiredID = 47,
		type = "Module",
		morph = 2,
		limit = 7,
		cost = 425,
	},	
	[85] = {  
		code = "module_personal_cloak", 
		name = "Personal Cloak",
		xp = 400,
		level = 6,
		type = "Module",
		morph = 2,
		limit = 1,
		chassis = {armcom = true, corcom = true, commsupport = true,},
		cost = 175,
	},	
	[86] = {  
		code = "spherepole", 
		name = "Scythe",
		xp = 150,
		level = 4,
		type = "Unit",
	},
	[88] = {  
		code = "panther", 
		name = "Panther",
		xp = 100,
		level = 2,
		requiredID = 8,
		type = "Unit",
	},
	[91] = {  
		code = "blackdawn", 
		name = "Black Dawn",
		xp = 200,
		level = 4,
		type = "Unit",
	},
	[94] = {  
		code = "module_dmg_booster", 
		name = "Damage Booster",
		xp = 250,
		level = 6,
		type = "Module",
		morph = 1,
		limit = 8,
		cost = 150,
	},	
	[95] = {  
		code = "weaponmod_disruptor_ammo", 
		name = "Disruptor Ammo",
		xp = 450,
		level = 8,
		type = "Module",
		morph = 2,
		limit = 1,
		cost = 350,
	},	
	[96] = {  
		code = "weaponmod_high_frequency_beam", 
		name = "High Frequency Beam",
		xp = 500,
		level = 9,
		type = "Module",
		morph = 3,
		limit = 1,
		cost = 425,
	},	
	[97] = {  
		code = "weaponmod_high_caliber_barrel", 
		name = "High Caliber Barrel",
		xp = 450,
		level = 9,
		type = "Module",
		morph = 2,
		limit = 1,
		cost = 450,
	},	
	[98] = {  
		code = "weaponmod_napalm_warhead",
		name = "Napalm Warhead",
		xp = 350,
		level = 8,
		type = "Module",
		morph = 2,
		limit = 1,
		chassis = {armcom = true, corcom = true,},
		cost = 275,
	},	
	[99] = {  
		code = "weaponmod_plasma_containment",
		name = "Plasma Containment Field",
		xp = 400,
		level = 8,
		type = "Module",
		morph = 3,
		limit = 1,
		chassis = {armcom = true, corcom = true, commrecon = true},
		cost = 500,
	},	
	[100] = {  
		code = "module_resurrect", 
		name = "Lazarus Device",
		xp = 350,
		level = 8,
		type = "Module",
		morph = 2,
		limit = 1,
		cost = 250,
	},	
	[101] = {  
		code = "conversion_partillery", 
		name = "Plasma Artillery Conversion",
		xp = 400,
		level = 7,
		requiredID = 70,
		type = "Module",
		morph = 3,
		limit = 2,
		chassis = {armcom = true, corcom = true,},
		cost = 425,
	},	
	[103] = {  
		code = "capturecar", 
		name = "Dominatrix",
		xp = 200,
		level = 4,
		type = "Unit",
	},
	[105] = {  
		code = "corgrav", 
		name = "Newton",
		xp = 150,
		level = 2,
		type = "Unit",
	},
	[106] = {  
		code = "factoryshield", 
		name = "Shield Bot Factory",
		xp = 100,
		level = 1,
		type = "Unit",
	},
	[107] = {  
		code = "corsilo", 
		name = "Silencer",
		xp = 400,
		level = 7,
		type = "Unit",
	},
	[108] = {  
		code = "module_personal_shield", 
		name = "Personal Shield",
		xp = 350,
		level = 6,
		type = "Module",
		morph = 2,
		limit = 1,
		cost = 300,
	},	
	[109] = {  
		code = "raveparty", 
		name = "Disco Rave Party",
		xp = 1000,
		level = 10,
		type = "Unit",
	},
	[110] = {  
		code = "commweapon_lightninggun",
		name = "Lightning Gun",
		xp = 350,
		level = 6,
		type = "Weapon",
		morph = 1,
		limit = 2,
		chassis = {armcom = true, commsupport = true},
		cost = 125,
	},	
	[115] = {  
		code = "commweapon_disintegrator",
		name = "Disintegrator Gun",
		xp = 600,
		level = 10,
		type = "Weapon",
		morph = 3,
		limit = 1,
		chassis = {armcom = true, corcom = true,},
		cost = 250,
	},	
	[116] = {  
		code = "module_autorepair", 
		name = "Autorepair System",
		xp = 250,
		level = 6,
		type = "Module",
		morph = 1,
		limit = 8,
		cost = 250,
	},	
	[117] = {  
		code = "weaponmod_stun_booster", 
		name = "Flux Amplifier",
		xp = 400,
		level = 8,
		requiredID = 110,
		type = "Module",
		morph = 2,
		limit = 1,
		cost = 225,
	},	
	[119] = {  
		code = "module_companion_drone", 
		name = "Companion Drone",
		xp = 450,
		level = 8,
		type = "Module",
		morph = 3,
		limit = 1,
		cost = 275,
	},
	[120] = {  
		code = "module_radanet", 
		name = "Integrated Radar Network",
		xp = 500,
		level = 9,
		requiredID = 3,
		type = "Module",
		morph = 3,
		limit = 1,
		chassis = { commsupport = true },
		cost = 450,
	},	
	[121] = {  
		code = "armarad", 
		name = "Advanced Radar Tower",
		xp = 200,
		level = 7,
		type = "Unit",
	},
	[122] = {  
		code = "armmstor", 
		name = "Storage",
		xp = 150,
		level = 5,
		type = "Unit",
	},
}

return unlocks