
local defs = {
	energysingu = {
		static = {
			distortion = {
				distortionType = "point",
				pieceName = "energyball",
				distortionConfig = {
					posx = 0,
					posy = 0,
					posz = 0,
					radius = 55,
					noiseStrength = 0.9,
					noiseScaleSpace = 1.2,
					distanceFalloff = 0.8,
					windAffected = -0.2,
					riseRate = 0.6,
					lifeTime = 0,
					effectType = 0,
				},
			}
		},
	},
	energyfusion = {
		static = {
			pLeft = {
				distortionType = "beam",
				pieceName = "pyramid_tip1",
				distortionConfig = {
					posx = 0,
					posy = -3,
					posz = 1,
					pos2x = 0,
					pos2y = -25,
					pos2z = 0.99,
					theta = 0.55,
					radius = 15,
					effectStrength = 0.75,
					noiseStrength = 0.4,
					noiseScaleSpace = 1.2,
					distanceFalloff = 0.7,
					windAffected = -0.2,
					riseRate = 1.6,
					lifeTime = 0,
					effectType = 0,
				},
			},
			pRight = {
				distortionType = "beam",
				pieceName = "pyramid_tip2",
				distortionConfig = {
					posx = 0,
					posy = -3,
					posz = 1,
					pos2x = 0,
					pos2y = -25,
					pos2z = 0.99,
					theta = 0.55,
					radius = 15,
					effectStrength = 0.75,
					noiseStrength = 0.4,
					noiseScaleSpace = 1.2,
					distanceFalloff = 0.7,
					windAffected = -0.2,
					riseRate = 1.6,
					lifeTime = 0,
					effectType = 0,
				},
			}
		},
	},
	energygeo = {
		static = {
			heat = {
				distortionType = "beam",
				distortionConfig = {
					posx = 0,
					posy = 10,
					posz = 0,
					pos2x = 0,
					pos2y = 30,
					pos2z = -0.01,
					radius = 36,
					effectStrength = 1,
					noiseStrength = 0.7,
					noiseScaleSpace = 1.2,
					distanceFalloff = 0.9,
					windAffected = -0.2,
					riseRate = 1.5,
					lifeTime = 0,
					effectType = 0,
				},
			}
		},
	},
	energyheavygeo = {
		static = {
			heat = {
				distortionType = "beam",
				distortionConfig = {
					posx = 0,
					posy = 15,
					posz = 0,
					pos2x = 0,
					pos2y = 35,
					pos2z = -0.01,
					radius = 45,
					effectStrength = 1.1,
					noiseStrength = 0.7,
					noiseScaleSpace = 1.2,
					distanceFalloff = 0.9,
					windAffected = -0.2,
					riseRate = 1.5,
					lifeTime = 0,
					effectType = 0,
				},
			}
		},
	},
	staticmex = {
		-- Mex od[i] pieces are shown and hidden based on overdrive multiplier
		static = {
			distortion_1 = {
				distortionType = "beam",
				pieceName = "od1",
				distortionConfig = {
					posx = 0,
					posy = 0,
					posz = 0,
					pos2x = 0,
					pos2y = 15,
					pos2z = -0.01,
					radius = 16.5,
					effectStrength = 0.65,
					noiseStrength = 0.9,
					noiseScaleSpace = 1.2,
					distanceFalloff = 0.6,
					windAffected = 0,
					riseRate = 1.7,
					lifeTime = 0,
					effectType = 0,
				},
			},
			distortion_2 = {
				distortionType = "beam",
				pieceName = "od2",
				distortionConfig = {
					posx = 0,
					posy = 0,
					posz = 0,
					pos2x = 0,
					pos2y = 20,
					pos2z = -0.01,
					radius = 19,
					effectStrength = 0.8,
					noiseStrength = 0.9,
					noiseScaleSpace = 1.22,
					distanceFalloff = 0.55,
					windAffected = 0,
					riseRate = 2.6,
					lifeTime = 0,
					effectType = 0,
				},
			},
			distortion_3 = {
				distortionType = "beam",
				pieceName = "od3",
				distortionConfig = {
					posx = 0,
					posy = 0,
					posz = 0,
					pos2x = 0,
					pos2y = 22,
					pos2z = -0.01,
					radius = 21,
					effectStrength = 0.7,
					noiseStrength = 0.9,
					noiseScaleSpace = 1.23,
					distanceFalloff = 0.7,
					windAffected = 0,
					riseRate = 3.2,
					lifeTime = 0,
					effectType = 0,
				},
			},
			distortion_3_cone = {
				distortionType = "cone",
				pieceName = "od3",
				distortionConfig = {
					posx = 0,
					posy = 5,
					posz = 0,
					dirx = 0,
					diry = 1,
					dirz = 0,
					theta = 0.8,
					radius = 70,
					effectStrength = 1.2,
					noiseStrength = 0.9,
					noiseScaleSpace = 1.22,
					distanceFalloff = 1,
					windAffected = 0,
					riseRate = 3.2,
					lifeTime = 0,
					effectType = 0,
				},
			},
			distortion_4 = {
				distortionType = "beam",
				pieceName = "od4",
				distortionConfig = {
					posx = 0,
					posy = 0,
					posz = 0,
					pos2x = 0,
					pos2y = 22,
					pos2z = -0.01,
					radius = 23,
					effectStrength = 0.8,
					noiseStrength = 0.9,
					noiseScaleSpace = 1.24,
					distanceFalloff = 0.7,
					windAffected = 0,
					riseRate = 5.4,
					lifeTime = 0,
					effectType = 0,
				},
			},
			distortion_4_cone = {
				distortionType = "cone",
				pieceName = "od4",
				distortionConfig = {
					posx = 0,
					posy = 2,
					posz = 0,
					dirx = 0,
					diry = 1,
					dirz = 0,
					theta = 1.1,
					radius = 85,
					effectStrength = 1.9,
					noiseStrength = 0.9,
					noiseScaleSpace = 1.22,
					distanceFalloff = 1.1,
					windAffected = 0,
					riseRate = 4.8,
					lifeTime = 0,
					effectType = 0,
				},
			},
		}
	},
}

return defs
