

local unitLights = {
	turretlaser = {
		static = {
			{
				lightType = 'cone',
				pieceName = 'barrel',
				lightConfig = { posx = 0, posy = 5, posz = 3, radius = 380,
					dirx = 0, diry = 0, dirz = 1, theta = 0.24,
					r = 0.95, g = 0.95, b = 0.88, a = 0.4,
					modelfactor = -0.4, specular = -0.3, scattering = 1.8, lensflare = 0,
					lifetime = 0, sustain = 0, selfshadowing = 3},
			},
			{
				lightType = 'point',
				pieceName = 'barrel',
				lightConfig = { posx = 0, posy = 5, posz = 6.5, radius = 7,
								color2r = 0.8, color2g = 0.9, color2b = 1, colortime = 0,
								r = 0.8, g = 0.9, b = 1, a = 0.6,
								modelfactor = 0.5, specular = 0.2, scattering = 0.9, lensflare = 0,
								lifetime = 0, sustain = 0, selfshadowing = 0},
			},
			{
				lightType = 'point',
				pieceName = 'base',
				lightConfig = { posx = -9, posy = 10, posz = 9, radius = 7,
								color2r = 0, color2g = 0, color2b = 0, colortime = -1.5,
								r = 1.2, g = 1, b = 0.4, a = 0.5,
								modelfactor = 0.4, specular = 0.5, scattering = 0.0, lensflare = 0,
								lifetime = 0, sustain = 0, selfshadowing = 0},
			},
			{
				lightType = 'point',
				pieceName = 'base',
				lightConfig = { posx = 9, posy = 10, posz = 9, radius = 7,
								color2r = 0, color2g = 0, color2b = 0, colortime = -1.5,
								r = 1.2, g = 1, b = 0.4, a = 0.5,
								modelfactor = 0.4, specular = 0.5, scattering = 0.0, lensflare = 0,
								lifetime = 0, sustain = 0, selfshadowing = 0},
			},
			{
				lightType = 'point',
				pieceName = 'base',
				lightConfig = { posx = -9, posy = 10, posz = -9, radius = 7,
								color2r = 0, color2g = 0, color2b = 0, colortime = -1.5,
								r = 1.2, g = 1, b = 0.4, a = 0.5,
								modelfactor = 0.4, specular = 0.5, scattering = 0.0, lensflare = 0,
								lifetime = 0, sustain = 0, selfshadowing = 0},
			},
			{
				lightType = 'point',
				pieceName = 'base',
				lightConfig = { posx = 9, posy = 10, posz = -9, radius = 7,
								color2r = 0, color2g = 0, color2b = 0, colortime = -1.5,
								r = 1.2, g = 1, b = 0.4, a = 0.5,
								modelfactor = 0.4, specular = 0.5, scattering = 0.0, lensflare = 0,
								lifetime = 0, sustain = 0, selfshadowing = 0},
			},
			{
				lightType = 'point',
				pieceName = 'base',
				lightConfig = { posx = 0, posy = 34, posz = -9.5, radius = 10,
								color2r = 0, color2g = 0, color2b = 0, colortime = -1,
								r = 1, g = 1, b = 1, a = 0.4,
								modelfactor = 0.4, specular = 0.5, scattering = 0.1, lensflare = 0,
								lifetime = 0, sustain = 0, selfshadowing = 0},
			},
			{
				lightType = 'point',
				pieceName = 'base',
				lightConfig = { posx = 0, posy = 34, posz = 9.5, radius = 10,
								color2r = 0, color2g = 0, color2b = 0, colortime = -1,
								r = 1, g = 1, b = 1, a = 0.4,
								modelfactor = 0.4, specular = 0.5, scattering = 0.1, lensflare = 0,
								lifetime = 0, sustain = 0, selfshadowing = 0},
			},
			-- topteam = {
			-- 	lightType = 'point',
			-- 	pieceName = 'base',
			-- 	lightConfig = { posx = -3.4, posy = 61, posz = 8, radius = 5,
			-- 					color2r = 0, color2g = 0, color2b = 0, colortime = 45,
			-- 					r = -1, g = 1, b = 1, a = 1.5,
			-- 					modelfactor = 0.4, specular = 0.3, scattering = 0.3, lensflare = 0,
			-- 					lifetime = 0, sustain = 0, selfshadowing = 0},
			-- },
			{
				lightType = 'point',
				pieceName = 'barrel',
				lightConfig = { posx = 0, posy = 2, posz = -14, radius = 4.5,
								color2r = 0, color2g = 0, color2b = 0, colortime = 45,
								r = -1, g = 1, b = 1, a = 1.5,
								modelfactor = 0.6, specular = 0.3, scattering = 0.15, lensflare = 0,
								lifetime = 0, sustain = 0, selfshadowing = 0},
			},
			{
				lightType = 'point',
				pieceName = 'barrel',
				lightConfig = { posx = 0, posy = -3, posz = -14, radius = 4.5,
								color2r = 0, color2g = 0, color2b = 0, colortime = 45,
								r = -1, g = 1, b = 1, a = 1.5,
								modelfactor = 0.6, specular = 0.3, scattering = 0.15, lensflare = 0,
								lifetime = 0, sustain = 0, selfshadowing = 0},
			},
			-- sidetop1 = {
			-- 	lightType = 'point',
			-- 	pieceName = 'base',
			-- 	lightConfig = { posx = -10.5, posy = 56, posz = 0, radius = 7,
			-- 					color2r = 1, color2g = 1, color2b = 0.4, colortime = -1,
			-- 					r = -1, g = 1, b = 1, a = 1.5,
			-- 					modelfactor = 0.4, specular = 0.5, scattering = 0.5, lensflare = 0,
			-- 					lifetime = 0, sustain = 0, selfshadowing = 0},
			-- },
			-- sidetop2 = {
			-- 	lightType = 'point',
			-- 	pieceName = 'base',
			-- 	lightConfig = { posx = 10.5, posy = 56, posz = 0, radius = 7,
			-- 					color2r = 1, color2g = 1, color2b = 0.4, colortime = -1,
			-- 					r = -1, g = 1, b = 1, a = 1,
			-- 					modelfactor = 0.4, specular = 0.5, scattering = 0.5, lensflare = 0,
			-- 					lifetime = 0, sustain = 0, selfshadowing = 0},
			-- },
		},
	},
}

return unitLights
