-- antinuke
-- antinuke_cloud
-- antinuke_cloud_rings1
-- antinuke_cloud_main
-- antinuke_cloud_rings2

return {
  ["antinuke"] = {
    usedefaultexplosions = false,
    cloud = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = 20,
        dir                = [[dir]],
        explosiongenerator = [[custom:ANTINUKE_CLOUD]],
        pos                = [[0, 0, 0]],
      },
    },
    pikes = {
      air                = true,
      class              = [[explspike]],
      count              = 32,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.006,
        alwaysvisible      = true,
        color              = [[1,0.5,0.1]],
        dir                = [[-8 r16, -8 r16, -8 r16]],
        length             = 1,
        lengthgrowth       = 1,
        width              = 64,
      },
    },
    sphere = {
      air                = true,
      class              = [[CSpherePartSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 0.5,
        alwaysvisible      = true,
        color              = [[1,1,0.5]],
        expansionspeed     = 15,
        ttl                = 80,
      },
    },
  },

  ["antinuke_cloud"] = {
    bottom = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = 30,
        dir                = [[dir]],
        explosiongenerator = [[custom:ANTINUKE_CLOUD_RINGS2]],
        pos                = [[0, -256, 0]],
      },
    },
    center = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = 15,
        dir                = [[dir]],
        explosiongenerator = [[custom:ANTINUKE_CLOUD_RINGS1]],
        pos                = [[0, 0, 0]],
      },
    },
    main = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = 15,
        dir                = [[dir]],
        explosiongenerator = [[custom:ANTINUKE_CLOUD_MAIN]],
        pos                = [[0, 0, 0]],
      },
    },
    top = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = 30,
        dir                = [[dir]],
        explosiongenerator = [[custom:ANTINUKE_CLOUD_RINGS2]],
        pos                = [[0, 256, 0]],
      },
    },
  },

  ["antinuke_cloud_rings1"] = {
    ring = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.98,
        alwaysvisible      = true,
        colormap           = [[0 0 0 0  0.75 0.75 0.75 1  0.75 0.75 0.75 0.75  0.75 0.75 0.75 0.5  0 0 0 0]],
        directional        = false,
        emitrot            = 90,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 256,
        particlelife       = 180,
        particlelifespread = 20,
        particlesize       = 4,
        particlesizespread = 4,
        particlespeed      = 16,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 16,
        sizemod            = 0.75,
        texture            = [[smokesmall]],
      },
    },
  },

  ["antinuke_cloud_main"] = {
    cloud = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.98,
        alwaysvisible      = true,
        colormap           = [[0 0 0 0  0.5 0.5 0.5 1  0.5 0.5 0.5 0.75  0.5 0.5 0.5 0.5  0 0 0 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 64,
        particlelife       = 120,
        particlelifespread = 30,
        particlesize       = 4,
        particlesizespread = 4,
        particlespeed      = 8,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 4,
        sizemod            = 1,
        texture            = [[smokesmall]],
      },
    },
  },

  ["antinuke_cloud_rings2"] = {
    ring = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.98,
        alwaysvisible      = true,
        colormap           = [[0 0 0 0  0.75 0.75 0.75 1  0.75 0.75 0.75 0.75  0.75 0.75 0.75 0.5  0 0 0 0]],
        directional        = false,
        emitrot            = 90,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 128,
        particlelife       = 120,
        particlelifespread = 20,
        particlesize       = 4,
        particlesizespread = 4,
        particlespeed      = 12,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 16,
        sizemod            = 0.75,
        texture            = [[smokesmall]],
      },
    },
  },

}

