-- atlas_engine

return {
  ["atlas_engine"] = {
    fire = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        useairlos       = false,
        colormap           = [[1 1 0 0.9      1 0.8  0.3 08    0 0 0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 5,
        particlelifespread = 0,
        particlesize       = 0.5,
        particlesizespread = 0.3,
        particlespeed      = 2,
        particlespeedspread = 0.2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 2,
        sizemod            = 1.0,
        texture            = [[orangesmoke2]],
      },
    },
    fluffy = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        useairlos       = false,
        colormap           = [[1 1 1 1  1 1 1 1 0 0 0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 20,
        particlelifespread = 0,
        particlesize       = [[5 r5]],
        particlesizespread = 0,
        particlespeed      = [[3.5 r3.5]],
        particlespeedspread = 0.2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.4,
        sizemod            = 1.0,
        texture            = [[smokesmall]],
      },
    },
  },

}

