-- beamerray

return {
  ["beamerray"] = {
    usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 0,
      circlegrowth       = 1,
      flashalpha         = 1.0,
      flashsize          = 26,
      ttl                = 24,
      color = {
        [1]  = 0,
        [2]  = 0,
        [3]  = 1,
      },
    },
    meltage = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = 0,
        explosiongenerator = [[custom:LASERS_MELT1]],
        pos                = [[0, 0, 0]],
      },
    },
    pikes = {
      air                = true,
      class              = [[explspike]],
      count              = 5,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.06,
        color              = [[0.2,0.2,1]],
        dir                = [[-2 r4,-2 r4,-2 r4]],
        length             = 11,
        width              = 7,
      },
    },
    sparks_yellow = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[1 1 0 0.01   1 0.7 0.5 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 80,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.4, 0]],
        numparticles       = 5,
        particlelife       = 15,
        particlelifespread = 0,
        particlesize       = 1,
        particlesizespread = 2.5,
        particlespeed      = 3,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[plasma]],
      },
    },
    sparks_blue = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.2 0.2 1.0 0.01   0.1 0.1 0.8 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 80,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 5,
        particlelife       = 10,
        particlelifespread = 3,
        particlesize       = 8,
        particlesizespread = 2.5,
        particlespeed      = 4,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[plasma]],
      },
    },
  },

  ["beamerray_angry"] = {
    usedefaultexplosions = false,
    pikes = {
      air                = true,
      class              = [[explspike]],
      count              = 5,
      ground             = true,
      water              = true,
      underwater         = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.065,
        color              = [[1,0.2,0.2]],
        dir                = [[-2 r4,-2 r4,-2 r4]],
        length             = 11,
        width              = 5,
      },
    },
    sparks_yellow = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      underwater         = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.8 0.6 0 0.01   1 0.7 0.1 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 80,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.4, 0]],
        numparticles       = 5,
        particlelife       = 15,
        particlelifespread = 0,
        particlesize       = 1.8,
        particlesizespread = 2.5,
        particlespeed      = 3,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = -0.05,
        sizemod            = 1.0,
        texture            = [[plasma]],
      },
    },
    sparks_red = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[1.0 0.2 0.2 0.01   0.8 0.1 0.1 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 80,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 5,
        particlelife       = 10,
        particlelifespread = 3,
        particlesize       = 10,
        particlesizespread = 2.5,
        particlespeed      = 4,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = -0.05,
        sizemod            = 0.98,
        texture            = [[plasma]],
      },
    },
  },
  ["beamerray_angry_thermite"] = {
    usedefaultexplosions = false,
    pikes = {
      air                = true,
      class              = [[explspike]],
      count              = 5,
      ground             = true,
      water              = true,
      underwater         = true,
      properties = {
        alpha              = 1,
        alphadecay         = [[d0.0002 0.1]],
        color              = [[1, d1 x0.5 -0.4, d1 x0.5 -0.4]],
        dir                = [[-2 r4,-2 r4,-2 r4]],
        length             = [[0.75 d1 14]],
        width              = [[0.78 d1 8.1]],
        pos                = [[0, 5, 0]],
      },
    },
    sparks_white = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      underwater         = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.8 0.8 0.8 0.01   1 1 1 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = [[60 d-3.53]],
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.15, 0]],
        numparticles       = [[d0.2 k]],
        particlelife       = 15,
        particlelifespread = 0,
        particlesize       = [[0.05 d1 x0.8 1]],
        particlesizespread = 2.5,
        particlespeed      = [[d0.4 1]],
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = -0.05,
        sizemod            = 1.0,
        texture            = [[plasma]],
      },
    },
    sparks_yellow = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      underwater         = false,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.8 0.6 0 0.01   1 0.7 0.1 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 50,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.15, 0]],
        numparticles       = [[d1 0.6 k]],
        particlelife       = 15,
        particlelifespread = 0,
        particlesize       = [[0.042 d1 x0.8 1.5]],
        particlesizespread = 2.5,
        particlespeed      = [[d0.06 1.1]],
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = -0.05,
        sizemod            = 1.0,
        texture            = [[plasma]],
      },
    },
    sparks_red = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater         = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[1.0 0.2 0.2 0.01   0.8 0.1 0.1 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 80,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.08, 0]],
        numparticles       = [[d0.2 1 k]],
        particlelife       = [[d1 x0.5 5]],
        particlelifespread = 3,
        particlesize       = [[0.07 d1 x0.9]],
        particlesizespread = 2.5,
        particlespeed      = [[0.07 d1 x0.7 4]],
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = -0.05,
        sizemod            = 0.98,
        texture            = [[plasma]],
      },
    },
	bubbles_rising = {
		class              = [[CSimpleParticleSystem]],
		count              = 1,
		air                = false,
		ground             = false,
		underwater         = true,
		properties = {
			airdrag            = [[0.98]],
			--alwaysvisible      = true,
			colormap           = [[0.9 0.9 0.9 0.9
						   0.8 0.8 0.8 0.2
						   0.8 0.8 0.8 0.1
						   0 0 0 0]],
			directional        = true,
			emitrot            = 45,
			emitrotspread      = 10,
			emitvector         = [[0, 1, 0]],
			gravity            = [[0, 0 d0.1 x0.1, 0]],
			numparticles       = [[r4]],
			particlelife       = [[20 d0.5]],
			particlelifespread = 20,
			particlesize       = 1,
			particlesizespread = 3,
			particlespeed      = 0.3,
			particlespeedspread = 1,
			pos                = [[-5 r10, -5 r10, -5 r10]],
			sizegrowth         = [[0.3 r0.2]],
			sizemod            = [[0.98 r0.01]],
			texture            = [[randdots]],
			useairlos          = false,
		},
	},
  },
  ["beamerray_angry_thermite_initial"] = {
    usedefaultexplosions = false,
    pikes = {
      air                = true,
      class              = [[explspike]],
      count              = 5,
      ground             = true,
      water              = true,
      underwater         = true,
      properties = {
        alpha              = 1,
        alphadecay         = [[d0.0002 0.1]],
        color              = [[1, 16.66 x0.5 -0.4, 16.66 x0.5 -0.4]],
        dir                = [[-2 r4,-2 r4,-2 r4]],
        length             = 14.4,
        width              = 11.6,
        pos                = [[0, 5, 0]],
      },
    },
    sparks_yellow = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      underwater         = false,
      properties = {
        airdrag            = 0.98,
        colormap           = [[0.8 0.6 0 0.01   1 0.7 0.1 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = -180,
        emitrotspread      = 60,
        emitvector         = [[dir]],
        gravity            = [[0.03 r-0.06, 0.03 r-0.06, 0.03 r-0.06]],
        numparticles       = 3,
        particlelife       = 20,
        particlelifespread = 15,
        particlesize       = 1,
        particlesizespread = 4,
        particlespeed      = 1,
        particlespeedspread = 0.8,
        pos                = [[3 r-6, 3 r-6, 3 r-6]],
        sizegrowth         = -0.05,
        sizemod            = 1.0,
        texture            = [[plasma]],
      },
    },
	bubbles_rising = {
		class              = [[CSimpleParticleSystem]],
		count              = 1,
		air                = false,
		ground             = false,
		underwater         = true,
		properties = {
			airdrag            = [[0.98]],
			--alwaysvisible      = true,
			colormap           = [[0.9 0.9 0.9 0.9
						   0.8 0.8 0.8 0.2
						   0.8 0.8 0.8 0.1
						   0 0 0 0]],
			directional        = true,
			emitrot            = 45,
			emitrotspread      = 10,
			emitvector         = [[0, 1, 0]],
			gravity            = [[0, 0 d0.1 x0.1, 0]],
			numparticles       = [[r4]],
			particlelife       = [[20 d0.5]],
			particlelifespread = 20,
			particlesize       = 1,
			particlesizespread = 3,
			particlespeed      = 0.3,
			particlespeedspread = 1,
			pos                = [[-5 r10, -5 r10, -5 r10]],
			sizegrowth         = [[0.3 r0.2]],
			sizemod            = [[0.98 r0.01]],
			texture            = [[randdots]],
			useairlos          = false,
		},
	},
  },
}

