return {
	["blastwingtrail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
		head                 = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.99,
				alwaysvisible       = false,
				colormap            = [[1 1 1 0.05   0.01 0.005 0.02 0.01]],
				directional         = true,
				emitrotspread       = 0,
				emitvector          = [[dir]],
				gravity             = [[0 0 0]];
				numparticles        = 3,
				particlelife        = 3,
				particlelifespread  = 0,
				particlesize        = 8,
				particlesizespread  = 8,
				particlespeed       = 0.9,
				particlespeedspread = 0.02,
				pos                 = [[0 0 0]],
				sizegrowth          = 0,
				sizemod             = 0.7,
				texture             = [[orangenovaexplo]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.9 0.5 0.2 0.01     0.8 0.3 0.1 0.01     0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[plasma3]],
				size         = 4.2,
				sizegrowth   = -0.3,
				ttl          = 3,
			},
		},
		shaftFront             = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.9 0.5 0.2 0.01     0.8 0.3 0.1 0.01     0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = 1,
				sidetexture  = [[plasma3]],
				size         = 4.2,
				sizegrowth   = -0.3,
				ttl          = 3,
			},
		},
	},
}

