return {
  ["heavy_cannon_muzzle"] = {
	muzzle = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = 0,
        explosiongenerator = [[custom:RAIDMUZZLE]],
        pos                = [[0, 0, 0]],
		dir				   = [[dir]],
      },
    },
	muzzle2 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = 0,
        explosiongenerator = [[custom:LEVLRMUZZLE]],
        pos                = [[0, 0, 0]],
		dir				   = [[dir]],
      },
    },
  },
  ["heavy_cannon_muzzle_shell"] = {
	muzzle = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = 0,
        explosiongenerator = [[custom:RAIDMUZZLE]],
        pos                = [[0, 0, 0]],
		dir				   = [[dir]],
      },
    },
	muzzle2 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = 0,
        explosiongenerator = [[custom:LEVLRMUZZLE]],
        pos                = [[0, 0, 0]],
		dir				   = [[dir]],
      },
    },
	shell = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.75 0 0 1   0.75 0 0 1]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, -0.5, 0]],
        numparticles       = 1,
        particlelife       = 15,
        particlelifespread = 0,
        particlesize       = 6.0,
        particlesizespread = 0,
        particlespeed      = 3,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[shell]],
      },
    },
  },
}
