local trails = {
  ["heavy_cannon_muzzle"] = {
	muzzle = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = 0,
        explosiongenerator = [[custom:RAIDMUZZLE]],
        pos                = [[0, 0, 0]],
		dir				   = [[dir]],
      },
    },
	muzzle2 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = 0,
        explosiongenerator = [[custom:LEVLRMUZZLE]],
        pos                = [[0, 0, 0]],
		dir				   = [[dir]],
      },
    },
  },
  ["heavy_cannon_muzzle_shell"] = {
	muzzle = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = 0,
        explosiongenerator = [[custom:RAIDMUZZLE]],
        pos                = [[0, 0, 0]],
		dir				   = [[dir]],
      },
    },
	muzzle2 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = 0,
        explosiongenerator = [[custom:LEVLRMUZZLE]],
        pos                = [[0, 0, 0]],
		dir				   = [[dir]],
      },
    },
	shell = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.75 0 0 1   0.75 0 0 1]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, -0.5, 0]],
        numparticles       = 1,
        particlelife       = 15,
        particlelifespread = 0,
        particlesize       = 6.0,
        particlesizespread = 0,
        particlespeed      = 3,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[shell]],
      },
    },
  },
  
	["light_plasma_trail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
		glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.1,
				alwaysvisible       = false,
				colormap            = [[0.1 0.07 0 0.01  0.1 0.07 0 0.02]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 10,
				particlespeed       = 0.1,
				sizegrowth          = 20,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3.2,
				sidetexture  = [[smoothtrail]],
				size         = 8,
				sizegrowth   = -0.3,
				ttl          = 5,
			},
		},
	},
	["medium_plasma_trail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
		glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.3,
				alwaysvisible       = false,
				colormap            = [[0.1 0.07 0 0.01  0.1 0.07 0 0.01]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 15,
				particlespeed       = 0.4,
				sizegrowth          = 10,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 8,
				sizegrowth   = -0.8,
				ttl          = 5,
			},
		},
	},
	["heavy_plasma_trail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
		glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.3,
				alwaysvisible       = false,
				colormap            = [[0.1 0.07 0 0.01  0.1 0.07 0 0.01]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 30,
				particlespeed       = 0.4,
				sizegrowth          = 20,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
		front                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -1.5,
				sidetexture  = [[plasma]],
				size         = 25,
				ttl          = 1,
			},
		},
		mid                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -2,
				sidetexture  = [[smoothtrail]],
				size         = 7,
				ttl          = 1,
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 7,
				sizegrowth   = -0.2,
				ttl          = 8,
			},
		},
		backtrail                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0 0 0 0.01  0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 2,
				sizegrowth   = -0.5,
				ttl          = 2,
			},
		},
	},
	["crab_plasma_trail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
		glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.3,
				alwaysvisible       = false,
				colormap            = [[0.1 0.07 0 0.01  0.1 0.07 0 0.01]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 15,
				particlespeed       = 0.4,
				sizegrowth          = 10,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 8,
				sizegrowth   = -0.8,
				ttl          = 8,
			},
		},
		backtrail                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 4,
				sizegrowth   = -0.5,
				ttl          = 2,
			},
		},
	},
	["cyclops_plasma_trail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
		glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.3,
				alwaysvisible       = false,
				colormap            = [[0.1 0.07 0 0.01  0.1 0.07 0 0.01]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 15,
				particlespeed       = 0.4,
				sizegrowth          = 10,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.18 0.1 0 0.01  0.09 0.05 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 10,
				sizegrowth   = -0.5,
				ttl          = 8,
			},
		},
	},
	
	["riot_cannon_trail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
		glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.1,
				alwaysvisible       = false,
				colormap            = [[0.1 0.07 0 0.01  0.1 0.07 0 0.01]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 10,
				particlespeed       = 0.1,
				sizegrowth          = 16,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 8,
				sizegrowth   = -0.3,
				ttl          = 5,
			},
		},
	},
	["light_arty_trail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
		glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.1,
				alwaysvisible       = false,
				colormap            = [[0.1 0.07 0 0.01  0.1 0.07 0 0.01]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 10,
				particlespeed       = 0.1,
				sizegrowth          = 16,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 8,
				sizegrowth   = -0.3,
				ttl          = 5,
			},
		},
	},
	["medium_arty_trail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
		glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.3,
				alwaysvisible       = false,
				colormap            = [[0.1 0.07 0 0.01  0.1 0.07 0 0.01]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 15,
				particlespeed       = 0.4,
				sizegrowth          = 10,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.015  0.05 0.045 0 0.015  0 0 0 0.015]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3.5,
				sidetexture  = [[smoothtrail]],
				size         = 16,
				sizegrowth   = -0.35,
				ttl          = 12,
			},
		},
		backtrail                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 5,
				sizegrowth   = -1,
				ttl          = 3,
			},
		},
	},
	["heavy_arty_trail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
		glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.3,
				alwaysvisible       = false,
				colormap            = [[0.1 0.07 0 0.01  0.1 0.07 0 0.01]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 30,
				particlespeed       = 0.4,
				sizegrowth          = 20,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
		front                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -1.5,
				sidetexture  = [[plasma]],
				size         = 25,
				ttl          = 1,
			},
		},
		mid                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -2,
				sidetexture  = [[smoothtrail]],
				size         = 7,
				ttl          = 1,
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 7,
				sizegrowth   = -0.2,
				ttl          = 10,
			},
		},
		backtrail                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0 0 0 0.01  0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 2,
				sizegrowth   = -0.2,
				ttl          = 4,
			},
		},
	},
	["tremor_arty_trail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
		glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.3,
				alwaysvisible       = false,
				colormap            = [[0.1 0.07 0 0.01  0.1 0.07 0 0.01]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 10,
				particlespeed       = 0.4,
				sizegrowth          = 6,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 9,
				sizegrowth   = -0.5,
				ttl          = 6,
			},
		},
		backtrail                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0 0 0 0.01 0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 2,
				sizegrowth   = -0.8,
				ttl          = 4,
			},
		},
	},
	["drp_trail_base"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
		glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.1,
				alwaysvisible       = false,
				colormap            = [[0.1 0.01 0.01 0.01  0.1 0.01 0.01 0.01]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 70,
				particlespeed       = 0.2,
				sizegrowth          = 20,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
		front                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.009 0.009 0.01  0.05 0.005 0.005 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -4,
				sidetexture  = [[plasma]],
				size         = 100,
				ttl          = 1,
			},
		},
		mid                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.009 0.009 0.01  0.05 0.005 0.005 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -5,
				sidetexture  = [[smoothtrail]],
				size         = 40,
				ttl          = 1,
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
        airdrag = 0,
				colormap     = [[0.09 0.009 0.009 0.01  0.05 0.005 0.005 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -7,
				sidetexture  = [[smoothtrail]],
				size         = 40,
				sizegrowth   = -0.18,
				ttl          = 22,
			},
		},
	},
}

local drpColors = {
	{1, 0.1, 0.1},
	{0.9, 0.3, 0},
	{0.7, 0.7, 0},
	{0.1, 1, 0.1},
	{0.1, 0.1, 1},
	{0.7, 0, 0.7},
}

local suMergeTable = Spring.Utilities.MergeTable
for i = 1, #drpColors do
	col = drpColors[i]
	local colSpec = {
		glare = {properties = {
			colormap = string.format("%.2f %.2f %.2f 0.01  %.2f %.2f %.2f 0.01", 0.15*col[1], 0.15*col[2], 0.15*col[3], 0.15*col[1], 0.15*col[2], 0.15*col[3])
		}},
		front = {properties = {
			colormap = string.format("%.2f %.2f %.2f 0.01  %.2f %.2f %.2f 0.01  0 0 0 0.01", 0.3*col[1], 0.3*col[2], 0.3*col[3], 0.2*col[1], 0.2*col[2], 0.2*col[3])
		}},
		mid = {properties = {
			colormap = string.format("%.2f %.2f %.2f 0.01  %.2f %.2f %.2f 0.01  0 0 0 0.01", 0.2*col[1], 0.2*col[2], 0.2*col[3], 0.1*col[1], 0.1*col[2], 0.1*col[3])
		}},
		shaft = {properties = {
			colormap = string.format("%.2f %.2f %.2f 0.01  %.2f %.2f %.2f 0.01  0 0 0 0.01", 0.09*col[1], 0.09*col[2], 0.09*col[3], 0.05*col[1], 0.05*col[2], 0.05*col[3])
		}},
	}
	trails["drp_trail_" .. i] = suMergeTable(colSpec, trails["drp_trail_base"], true)
end

return trails
