return {
  ["heavy_cannon_muzzle"] = {
	muzzle = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = 0,
        explosiongenerator = [[custom:RAIDMUZZLE]],
        pos                = [[0, 0, 0]],
		dir				   = [[dir]],
      },
    },
	muzzle2 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = 0,
        explosiongenerator = [[custom:LEVLRMUZZLE]],
        pos                = [[0, 0, 0]],
		dir				   = [[dir]],
      },
    },
  },
  ["heavy_cannon_muzzle_shell"] = {
	muzzle = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = 0,
        explosiongenerator = [[custom:RAIDMUZZLE]],
        pos                = [[0, 0, 0]],
		dir				   = [[dir]],
      },
    },
	muzzle2 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = 0,
        explosiongenerator = [[custom:LEVLRMUZZLE]],
        pos                = [[0, 0, 0]],
		dir				   = [[dir]],
      },
    },
	shell = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.75 0 0 1   0.75 0 0 1]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, -0.5, 0]],
        numparticles       = 1,
        particlelife       = 15,
        particlelifespread = 0,
        particlesize       = 6.0,
        particlesizespread = 0,
        particlespeed      = 3,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[shell]],
      },
    },
  },
  
	["light_plasma_trail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
    glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.3,
				alwaysvisible       = false,
				colormap            = [[0.1 0.07 0 0.01  0.1 0.07 0 0.01]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 10,
				particlespeed       = 0.4,
				sizegrowth          = 6,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 2,
				sizegrowth   = -2,
				ttl          = 2,
			},
		},
	},
	["medium_plasma_trail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
    glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.3,
				alwaysvisible       = false,
				colormap            = [[0.1 0.07 0 0.01  0.1 0.07 0 0.01]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 15,
				particlespeed       = 0.4,
				sizegrowth          = 10,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 3,
				sizegrowth   = -0.8,
				ttl          = 5,
			},
		},
	},
	["heavy_plasma_trail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
    glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.3,
				alwaysvisible       = false,
				colormap            = [[0.1 0.07 0 0.01  0.1 0.07 0 0.01]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 30,
				particlespeed       = 0.4,
				sizegrowth          = 20,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 4,
				sizegrowth   = -0.8,
				ttl          = 8,
			},
		},
		backtrail                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 0.5,
				sizegrowth   = -0.1,
				ttl          = 30,
			},
		},
	},
	["crab_plasma_trail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
    glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.3,
				alwaysvisible       = false,
				colormap            = [[0.1 0.07 0 0.01  0.1 0.07 0 0.01]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 15,
				particlespeed       = 0.4,
				sizegrowth          = 10,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 4,
				sizegrowth   = -0.8,
				ttl          = 8,
			},
		},
		backtrail                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 0.5,
				sizegrowth   = -0.1,
				ttl          = 20,
			},
		},
	},
	["cyclops_plasma_trail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
    glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.3,
				alwaysvisible       = false,
				colormap            = [[0.1 0.07 0 0.01  0.1 0.07 0 0.01]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 15,
				particlespeed       = 0.4,
				sizegrowth          = 10,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 4,
				sizegrowth   = -0.3,
				ttl          = 6,
			},
		},
	},
  
	["light_arty_trail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
    glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.3,
				alwaysvisible       = false,
				colormap            = [[0.1 0.07 0 0.01  0.1 0.07 0 0.01]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 10,
				particlespeed       = 0.4,
				sizegrowth          = 6,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 2,
				sizegrowth   = -0.8,
				ttl          = 4,
			},
		},
	},
	["medium_arty_trail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
    glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.3,
				alwaysvisible       = false,
				colormap            = [[0.1 0.07 0 0.01  0.1 0.07 0 0.01]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 15,
				particlespeed       = 0.4,
				sizegrowth          = 10,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 3,
				sizegrowth   = -1,
				ttl          = 10,
			},
		},
		backtrail                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 0.5,
				sizegrowth   = -0.2,
				ttl          = 10,
			},
		},
	},
	["heavy_arty_trail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
    glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.3,
				alwaysvisible       = false,
				colormap            = [[0.1 0.07 0 0.01  0.1 0.07 0 0.01]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 30,
				particlespeed       = 0.4,
				sizegrowth          = 20,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 4,
				sizegrowth   = -0.8,
				ttl          = 10,
			},
		},
		backtrail                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 0.5,
				sizegrowth   = -0.1,
				ttl          = 50,
			},
		},
	},
	["tremor_arty_trail"]          = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
    glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.3,
				alwaysvisible       = false,
				colormap            = [[0.1 0.07 0 0.01  0.1 0.07 0 0.01]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 10,
				particlespeed       = 0.4,
				sizegrowth          = 6,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 2,
				sizegrowth   = -0.8,
				ttl          = 4,
			},
		},
		backtrail                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 0.5,
				sizegrowth   = -0.2,
				ttl          = 10,
			},
		},
	},
}
