-- cyclops_hit

return {
  ["cyclops_hit"] = {
    air                = true,
    count              = 10,
    ground             = true,
    water              = true,
    sparks_wide = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = false,
        colormap           = [[0.75 0.15 0.75 0.01   0.01 0.01 0.005 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[dir]],
        gravity            = [[0, -0.25, 0]],
        numparticles       = [[45]],
        particlelife       = 40,
        particlelifespread = 40,
        particlesize       = [[10]],
        particlesizespread = 0.5,
        particlespeed      = 8,
        particlespeedspread = 8,
        pos                = [[-40 r80, 0 r80, -40 r80]],
        sizegrowth         = 0,
        sizemod            = 0.97,
        texture            = [[plasma]],
      },
    },
    sparks_core = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      unit               = 1,
      properties = {
        airdrag            = 0.9,
        alwaysvisible      = false,
        colormap           = [[1 0.7 1 0.01   0.01 0.01 0.005 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[dir]],
        gravity            = [[0, -0.25, 0]],
        numparticles       = [[32]],
        particlelife       = 40,
        particlelifespread = 40,
        particlesize       = [[10]],
        particlesizespread = 0.5,
        particlespeed      = 3,
        particlespeedspread = 20,
        pos                = [[-40 r80, -40 r80, -40 r80]],
        sizegrowth         = 0,
        sizemod            = 0.97,
        texture            = [[plasma]],
      },
    },
    sparks_snow = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 5,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.85,
        colormap           = [[1 0.7 1 0.01   0.01 0.01 0.005 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 30,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.15 i-0.05, 0]],
        numparticles       = 5,
        particlelife       = [[50 r25]],
        particlelifespread = 25,
        particlesize       = [[0.15 i0.1]],
        particlesizespread = 0.25,
        particlespeed      = 15,
        particlespeedspread = 15,
        pos                = [[10 r20, r20, 10 r20]],
        sizegrowth         = [[0.07]],
        sizemod            = 0.98,
        texture            = [[pinknovaexplo]],
      },
    },
    debris1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 20,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.98,
        colormap           = [[0.22 0.18 0.15 1   0.22 0.18 0.15 1	 0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 90,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.2, 0]],
        numparticles       = 5,
        particlelife       = [[50 i-0.5]],
        particlelifespread = 0,
        particlesize       = [[10 r10]],
        particlesizespread = 0,
        particlespeed      = 3,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = [[-0.1 i0.015]],
        sizemod            = 1.0,
        texture            = [[debris2]],
      },
    },
    debris2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 20,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.98,
        colormap           = [[0.22 0.18 0.15 1   0.22 0.18 0.15 1	 0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 20,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.2, 0]],
        numparticles       = 5,
        particlelife       = 150,
        particlelifespread = 0,
        particlesize       = [[1 r10]],
        particlesizespread = 0,
        particlespeed      = 5,
        particlespeedspread = 8,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[debris2]],
      },
    },
    dirt1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1 0.5 0.3 0.3  0.45 0.37 0.3 1  0.45 0.37 0.3 1	 0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 25,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 30,
        particlelife       = 18.5,
        particlelifespread = 5,
        particlesize       = 1.5,
        particlesizespread = 3,
        particlespeed      = 0,
        particlespeedspread = 19,
        pos                = [[0, 2, 0]],
        sizegrowth         = 3,
        sizemod            = 1.0,
        texture            = [[dirtplosion2]],
      },
    },
    dirt2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 0,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1 0.5 0.3 0.3	 0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 25,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 30,
        particlelife       = 8.5,
        particlelifespread = 5,
        particlesize       = 1.5,
        particlesizespread = 3,
        particlespeed      = 0,
        particlespeedspread = 19,
        pos                = [[0, 2, 0]],
        sizegrowth         = 3,
        sizemod            = 1.0,
        texture            = [[dirtplosion2]],
      },
    },
    dirt3 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 10,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[0 0 0 0.01  0.22 0.18 0.15 1	 0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 25,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.2, 0]],
        numparticles       = 1,
        particlelife       = 80,
        particlelifespread = 5,
        particlesize       = 1.5,
        particlesizespread = 3,
        particlespeed      = 5,
        particlespeedspread = 24,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 1.0,
        texture            = [[kfoam]],
      },
    },
    sphere = {
      air                = true,
      class              = [[CSpherePartSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 0.6,
        color              = [[0.7,0.1,0.9]],
        expansionspeed     = 5,
        ttl                = 5,
      },
    },
    glow = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 10,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        colormap           = [[1 1 1 1   1 0.5 1 0.5              0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[-0, 1, 0]],
        gravity            = [[0, 0.00, 0]],
        numparticles       = 1,
        particlelife       = 5,
        particlelifespread = 0,
        particlesize       = 60,
        particlesizespread = 10,
        particlespeed      = 1,
        particlespeedspread = 0,
        pos                = [[0, 2, 0]],
        sizegrowth         = -5,
        sizemod            = 0.5,
        texture            = [[diamondstar]],
      },
    },
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 0.125,
      flashalpha         = 2,
      flashsize          = 16,
      ttl                = 128,
      color = {
        [1]  = 0.5,
        [2]  = 0.1,
        [3]  = 0.9,
      },
    },
    cinder = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        alwaysvisible      = false,
        heat               = [[100]],
        heatfalloff        = 2,
        maxheat            = 100,
        pos                = 0,
        size               = [[16]],
        sizegrowth         = -1,
        speed              = [[0 0 0]],
        texture            = [[pinknovaexplo]],
      },
    },
    fanny = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = 60,
        explosiongenerator = [[custom:FANNY]],
        pos                = [[0, 0, 0]],
      },
    },
  },

}

