-- extra_large_muzzle_flash_flame
-- extra_large_muzzle_flash_smoke
-- vindiback_large
-- rocketboots_muzzle
return {
  ["extra_large_muzzle_flash_flame"] = {
    muzzleflame = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[0.9 0.8 0 0.01 0.9 0.9 0.9 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0.25,
        fronttexture       = [[muzzlefront]],
        length             = 64,
        sidetexture        = [[muzzleside]],
        size               = 24,
        sizegrowth         = 0.6,
        ttl                = 6,
      },
    },
  },
  ["extra_large_muzzle_flash_smoke"] = {
    muzzlesmoke = {
      air                = true,
      class              = [[CSmokeProjectile2]],
      count              = 12,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        agespeed           = 0.03125,
        glowfalloff        = 8,
        pos                = [[0, 0, 0]],
        size               = 9,
        speed              = [[r-2 r2, ri-0.20 ri0.20, r-2 r2]],
        wantedpos          = [[-32 r32, r32, -32 r32]],
      },
    },
  },
  ["vindiback_large"] = {
    fire = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        useairlos          = false,
        colormap           = [[1 1 0 0.9      1 0.8  0.3 08    0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 15,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 4,
        particlelife       = 6,
        particlelifespread = 0,
        particlesize       = 10,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[orangesmoke2]],
      },
    },
    fluffy = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        useairlos       = false,
        colormap           = [[1 1 1 1 0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 30,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 6,
        particlelife       = 3,
        particlelifespread = 5,
        particlesize       = 20,
        particlesizespread = 0,
        particlespeed      = 7,
        particlespeedspread = 6,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.2,
        sizemod            = 1.0,
        texture            = [[smokesmall]],
      },
    },
    takeoff1 = {
      air                = false,
      useairlos       = false,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater         = 0,
      water              = false,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0 0 0 0.001 0.04 0.04 0.04 0.2    0 0 0 0.001]],
        emitrot            = 90,
        emitrotspread      = 0,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 30,
        particlelife       = 40,
        particlelifespread = 0,
        particlesize       = 8,
        particlesizespread = 1,
        particlespeed      = 5,
        particlespeedspread = 0,
        pos                = [[15, 1, 0]],
        sizegrowth         = 0.3,
        sizemod            = 1.0,
        texture            = [[kfoam]],
      },
    },
    dirtypoof = {
      class              = [[dirt]],
      count              = 5,
      ground             = true,
      properties = {
        alphafalloff       = 2,
        color              = [[0.4, 0.2, 0.10]],
        pos                = [[-100 r200, 0, -100 r200]],
        size               = 10,
        speed              = [[0.5 r-1, 2, 0.5 r-1]],
      },
    },
  },
  
  ["dirtyfootstep"] = {
    dirtypoof = {
      class              = [[dirt]],
      count              = 40,
      ground             = true,
      properties = {
        alphafalloff       = 1,
        color              = [[0.4, 0.2, 0.10]],
        pos                = [[r-10 r10, 0, r-10 r10]],
        size               = 30,
        speed              = [[r-3 r3, r2, r-3 r3]],
      },
    },
  },
  
  ["rocketboots_muzzle"] = {
    muzzleflame = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[0.9 0.8 0 0.01 0.9 0.9 0.9 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0.25,
        fronttexture       = [[muzzlefront]],
        length             = 32,
        sidetexture        = [[muzzleside]],
        size               = 12,
        sizegrowth         = 0.6,
        ttl                = 1,
      },
    },
    fire = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = false,
      water              = false,
      properties = {
        airdrag            = 1.0,
        colormap           = [[0.7 0.7 0.7 0.01  1 0.3 0.3 0.5   0 0 0 0]],
        directional        = true,
        --emitmul            = [[0, 4, 0]],
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[r1 r-1, -10 -10, r1 r-1]],
        gravity            = [[0.2 r-0.4, 0.2, 0.2 r-0.4]],
        numparticles       = 1,
        particlelife       = 10,
        particlelifespread = 6,
        particlesize       = 10,
        particlesizespread = 7,
        particlespeed      = 0.4,
        particlespeedspread = 0.1,
        pos                = [[0 0, -20 , 0 0]],
        sizegrowth         = 1.5,
        sizemod            = 1.0,
        texture            = [[flame]],
      },
    },
    smokeair = {
      air                = true,
      class              = [[CSmokeProjectile2]],
      count              = 2,
      ground             = false,
      water              = false,
      properties = {
        agespeed           = 0.01,
        color               = 1.0,
        pos                = [[r-2 r2, r-100 -10, r-2 r2]],
        size               = 35,
        sizeexpansion      = 0.4,
        speed              = [[r-1.5 r1.5, -5 r-5.3, r-1.5 r1.5]],
        startsize          = 5,
        wantedpos          = [[r-128 r128, r-300, r-128 r128]],
        glowfalloff        = 6.0,
      },
    },
    smokeground = {
      air                = false,
      class              = [[CSmokeProjectile2]],
      count              = 100,
      ground             = true,
      water              = false,
      properties = {
        agespeed           = 0.01,
        color              = 1.0,
        pos                = [[r-1 r1, 0, r-1 r1]],
        size               = 10,
        sizeexpansion      = 0.8,
        speed              = [[r-5.5 r5.5, 0 r1, r-5.5 r5.5]],
        startsize          = 5,
        wantedpos          = [[r-100 r100, r50, r-100 r100]],
        glowfalloff        = 6.0,
      },
    },
    dirtypoof = {
      class              = [[dirt]],
      count              = 20,
      ground             = true,
      properties = {
        alphafalloff       = 1,
        color              = [[0.4, 0.2, 0.10]],
        pos                = [[r-5 r10, 0, r-5 r10]],
        size               = 10,
        speed              = [[r-5 r5, r5, r-5 r5]],
      },
    },
  },

}
