return {
	["heavy_disruptor_beam_hit"] = {
		usedefaultexplosions = false,
		airflash = {
			air                = true,
			class              = [[heatcloud]],
			count              = 3,
			ground             = true,
			water              = true,
			underwater         = 1,
			unit               = 1,
			properties = {
				alwaysvisible      = false,
				heat               = [[60]],
				heatfalloff        = 5,
				maxheat            = 40,
				pos                = 0,
				size               = [[5]],
				sizegrowth         = 3,
				speed              = [[-1 r2]],
				texture            = [[pinknovaexplo]],
			},
		},
		sparks = {
			class              = [[CSimpleParticleSystem]],
			count              = 1,
			ground             = true,
			air                = true,
			unit               = 1,
			water              = true,
			underwater         = true,
			properties = {
				airdrag            = 0.999,
				alwaysvisible      = false,
				colormap           = [[1 0.25 1 0.05   0.01 0.005 0.02 0.01]],
				directional        = false,
				emitrotspread      = 180,
				emitvector         = [[1 0 0]],
				gravity			   = [[0,-0.01,0]];
				numparticles       = 20,
				particlelife       = 20,
				particlelifespread = 10,
				particlesize       = 2,
				particlesizespread = 0.5,
				particlespeed      = 0.6,
				particlespeedspread = 0.2,
				pos                = [[0, 0, 0]],
				sizegrowth         = 0,
				sizemod            = 0.95,
				texture            = [[pinknovaexplo]],
			},
		},
		big_pike = {
			air                = true,
			class              = [[explspike]],
			count              = 7,
			ground             = true,
			water              = true,
			properties = {
				alpha              = 1,
				alphadecay         = 0.06,
				color              = [[1,0.25,1]],
				pos                = [[0, 5, 0]],
				dir                = [[r2 -1, r2 -1, r2 -1]],
				length             = 17,
				lengthgrowth       = 5,
				width              = 3,
			},
		},
		cinder = {
			air                = true,
			class              = [[heatcloud]],
			count              = 1,
			ground             = true,
			water              = true,
			underwater         = 1,
			unit               = 1,
			properties = {
				alwaysvisible      = false,
				heat               = [[100]],
				heatfalloff        = 1.5,
				maxheat            = 100,
				pos                = 0,
				size               = [[7]],
				sizegrowth         = -0.05,
				speed              = [[0 0 0]],
				texture            = [[pinknovaexplo]],
			},
		},
	}
}

