return {
  ["disruptor_missile_hit"] = {
    usedefaultexplosions = false,
    airflash = {
      air                = true,
      class              = [[heatcloud]],
      count              = 3,
      ground             = true,
      water              = true,
      underwater         = 1,
      unit               = 1,
      properties = {
        alwaysvisible      = false,
        heat               = [[40]],
        heatfalloff        = 5,
        maxheat            = 40,
        pos                = 0,
        size               = [[5]],
        sizegrowth         = 3,
        speed              = [[-1 r2]],
        texture            = [[pinknovaexplo]],
      },
    },
    groundflash = {
      circlealpha        = 1,
      circlegrowth       = 0.125,
      flashalpha         = 0.5,
      flashsize          = 16,
      ttl                = 64,
      color = {
        [1]  = 0.5,
        [2]  = 0.1,
        [3]  = 0.9,
      },
    },
    cinder = {
      air                = true,
      class              = [[heatcloud]],
      count              = 3,
      ground             = true,
      water              = true,
      underwater         = 1,
      unit               = 1,
      properties = {
        alwaysvisible      = false,
        heat               = [[100]],
        heatfalloff        = 2,
        maxheat            = 100,
        pos                = 0,
        size               = [[7]],
        sizegrowth         = -0.2,
        speed              = [[-0.1 r0.2]],
        texture            = [[pinknovaexplo]],
      },
    },
    steam = {
      class              = [[CExpGenSpawner]],
      count              = 2,
      nounit             = 1,
      properties = {
        delay              = [[i1]],
        dir                = [[dir]],
        explosiongenerator = [[custom:BEAMWEAPON_HIT_YELLOW_STEAM]],
        pos                = [[0, 0, 0]],
      },
    },
    sparks = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      air                = true,
      unit               = 1,
      water              = true,
      underwater         = true,
      properties = {
        airdrag            = 0.8,
        alwaysvisible      = false,
        colormap           = [[1 0.25 1 0.05   0.01 0.005 0.02 0.01]],
        directional        = true,
        emitrotspread      = 360,
        emitvector         = [[dir]],
        gravity			   = [[0,-0.1,0]];
        numparticles       = 20,
        particlelife       = 15,
        particlelifespread = 10,
        particlesize       = 2,
        particlesizespread = 1,
        particlespeed      = 5,
        particlespeedspread = 5,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 0.9,
        texture            = [[pinknovaexplo]],
      },
    },
    smoke = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        airdrag            = 0.9,
        colormap           = [[0.05 0.05 0.05 0.4  0 0 0 0.001]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 10,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.001, 0]],
        numparticles       = 5,
        particlelife       = 30,
        particlelifespread = 20,
        particlesize       = 2,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 1.5,
        sizemod            = 0.985,
        texture            = [[smoke]],
      },
    },
  },
}

