-- ffejector
-- ff_wingtips
-- ffmuzzle
-- ff_engine
-- ff_puff

return {
  ["ffejector"] = {
    usedefaultexplosions = false,
    shells = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.97,
        useairlos       = false,
        colormap           = [[1 1 1 1   1 1 1 1]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, -0.2, 0]],
        numparticles       = 1,
        particlelife       = 80,
        particlelifespread = 0,
        particlesize       = 2.5,
        particlesizespread = 0,
        particlespeed      = 0,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[shell]],
      },
    },
  },

  ["ff_wingtips"] = {
    fluffy = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        useairlos       = false,
        colormap           = [[1 1 1 1   0 0 0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 40,
        particlelifespread = 0,
        particlesize       = 3,
        particlesizespread = 1,
        particlespeed      = 3,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.8,
        sizemod            = 1.0,
        texture            = [[smokesmall]],
      },
    },
  },

  ["ffmuzzle"] = {
    bitmapmuzzleflame = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        useairlos       = false,
        colormap           = [[1 1 0 0.01	1 0.5 0 0.01	0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0.1,
        fronttexture       = [[flowerflash]],
        length             = 18,
        sidetexture        = [[plasma2]],
        size               = 12,
        sizegrowth         = 1,
        ttl                = 3,
      },
    },
    smoke = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        useairlos       = false,
        colormap           = [[0.5 0.5 0.5 1   0 0 0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 160,
        particlelifespread = 0,
        particlesize       = 6,
        particlesizespread = 2,
        particlespeed      = 0,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.01,
        sizemod            = 1.0,
        texture            = [[smokesmall]],
      },
    },
  },

  ["ff_engine"] = {
    sparks = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.97,
        useairlos       = false,
        colormap           = [[0.8 0.8 1 0.01   1 1 0 0.01   1 0.5 0 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 5,
        emitvector         = [[dir]],
        gravity            = [[0, -0.2, 0]],
        numparticles       = 10,
        particlelife       = 3,
        particlelifespread = 0,
        particlesize       = 8,
        particlesizespread = 0,
        particlespeed      = 3,
        particlespeedspread = 7,
        pos                = [[0, 1, 0]],
        sizegrowth         = -2.6,
        sizemod            = 1.0,
        texture            = [[plasma]],
      },
    },
  },

  ["ff_puff"] = {
    fluffy = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 10,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.9,
        useairlos       = false,
        colormap           = [[1 1 1 1  1 1 1 1 0 0 0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 4,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 60,
        particlelifespread = 0,
        particlesize       = [[20 i-1.8]],
        particlesizespread = 0,
        particlespeed      = [[2 i1.44]],
        particlespeedspread = 0.5,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.2,
        sizemod            = 1.0,
        texture            = [[smokesmall]],
      },
    },
  },

}

