-- queen_trail
-- queen_trail_fire
-- large_green_goo
-- green_goo
-- small_green_goo
-- spire_trail
-- blobber_goo
-- lobber_goo
-- small_red_goo
-- red_goo

return {
  ["queen_trail"] = {
    splashes = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.9,
        colormap           = [[0.2 0.6 0 1   0.2 0.6 0 1   0 0 0 0]],
        directional        = true,
        emitrot            = 1,
        emitrotspread      = -2,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 8,
        particlelifespread = 8,
        particlesize       = 6,
        particlesizespread = 6,
        particlespeed      = 0.05,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 2,
        sizemod            = 1,
        texture            = [[blooddropwhite]],
      },
    },
  },

  ["queen_trail_fire"] = {
    splashes = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.9,
        colormap           = [[0.8 0.4 0 1   0.8 0.4 0 1   0 0 0 0]],
        directional        = true,
        emitrot            = 1,
        emitrotspread      = -2,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 8,
        particlelifespread = 8,
        particlesize       = 6,
        particlesizespread = 6,
        particlespeed      = 0.05,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 2,
        sizemod            = 1,
        texture            = [[blooddropwhite]],
      },
    },
  },

  ["large_green_goo"] = {
    groundflash = {
      circlealpha        = .4,
      circlegrowth       = 0,
      flashalpha         = .3,
      flashsize          = 180,
      ttl                = 128,
      color = {
        [1]  = 0.20000000298023,
        [2]  = 0.60000002384186,
        [3]  = 0,
      },
    },
    pop = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      properties = {
        airdrag            = .9,
        colormap           = [[0.2 0.6 0 1   0.2 0.6 0 1   0 0 0 0]],
        directional        = false,
        emitrot            = 45,
        emitrotspread      = 30,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 32,
        particlelifespread = 0,
        particlesize       = 12,
        particlesizespread = 8,
        particlespeed      = 0,
        particlespeedspread = 0,
        pos                = [[0, 1.0, 0]],
        sizegrowth         = 6,
        sizemod            = 1,
        texture            = [[bloodblastwhite]],
      },
    },
    splashes = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      properties = {
        airdrag            = .96,
        colormap           = [[0.2 0.6 0 1   0.2 0.6 0 1   0 0 0 0]],
        directional        = true,
        emitrot            = 180,
        emitrotspread      = 80,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 12,
        particlelife       = 30,
        particlelifespread = 20,
        particlesize       = 24,
        particlesizespread = 8,
        particlespeed      = 2,
        particlespeedspread = 3,
        pos                = [[0, 1.0, 0]],
        sizegrowth         = -.1,
        sizemod            = 1,
        texture            = [[blooddropwhite]],
      },
    },
  },

  ["green_goo"] = {
    groundflash = {
      circlealpha        = .4,
      circlegrowth       = 0,
      flashalpha         = .3,
      flashsize          = 32,
      ttl                = 128,
      color = {
        [1]  = 0.20000000298023,
        [2]  = 0.60000002384186,
        [3]  = 0,
      },
    },
    pop = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      properties = {
        airdrag            = .9,
        colormap           = [[0.2 0.6 0 1   0.2 0.6 0 1   0 0 0 0]],
        directional        = false,
        emitrot            = 45,
        emitrotspread      = 30,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 16,
        particlelifespread = 0,
        particlesize       = 12,
        particlesizespread = 8,
        particlespeed      = 0,
        particlespeedspread = 0,
        pos                = [[0, 1.0, 0]],
        sizegrowth         = 3,
        sizemod            = 1,
        texture            = [[bloodblastwhite]],
      },
    },
    splashes = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      properties = {
        airdrag            = .96,
        colormap           = [[0.2 0.6 0 1   0.2 0.6 0 1   0 0 0 0]],
        directional        = true,
        emitrot            = 180,
        emitrotspread      = 80,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 5,
        particlelife       = 12,
        particlelifespread = 8,
        particlesize       = 12,
        particlesizespread = 8,
        particlespeed      = 1.5,
        particlespeedspread = 3,
        pos                = [[0, 1.0, 0]],
        sizegrowth         = -.1,
        sizemod            = 1,
        texture            = [[blooddropwhite]],
      },
    },
  },

  ["small_green_goo"] = {
    splashes = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.9,
        colormap           = [[0.2 0.6 0 1   0.2 0.6 0 1   0 0 0 0]],
        directional        = true,
        emitrot            = 1,
        emitrotspread      = -2,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 5,
        particlelifespread = 5,
        particlesize       = 4,
        particlesizespread = 4,
        particlespeed      = 0.05,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 2,
        sizemod            = 1,
        texture            = [[blooddropwhite]],
      },
    },
  },

  ["spire_trail"] = {
    splashes = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.9,
        colormap           = [[0.2 0.6 0 1 0.2 0.6 0 1]],
        directional        = true,
        emitrot            = 180,
        emitrotspread      = -60,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 8,
        particlelifespread = 8,
        particlesize       = 10,
        particlesizespread = 15,
        particlespeed      = 7,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 2,
        sizemod            = 1,
        texture            = [[bloodblastwhite]],
      },
    },
  },

  ["blobber_goo"] = {
    groundflash = {
      circlealpha        = .4,
      circlegrowth       = 0,
      flashalpha         = .3,
      flashsize          = 128,
      ttl                = 128,
      color = {
        [1]  = 0.20000000298023,
        [2]  = 0.60000002384186,
        [3]  = 0,
      },
    },
    pop = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      properties = {
        airdrag            = .9,
        colormap           = [[0.2 0.6 0 1   0.2 0.6 0 1   0 0 0 0]],
        directional        = false,
        emitrot            = 30,
        emitrotspread      = -60,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 32,
        particlelifespread = 0,
        particlesize       = 8,
        particlesizespread = 4,
        particlespeed      = 0,
        particlespeedspread = 0,
        pos                = [[0, 1.0, 0]],
        sizegrowth         = 6,
        sizemod            = 1,
        texture            = [[bloodblastwhite]],
      },
    },
    splashes = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      properties = {
        airdrag            = .96,
        colormap           = [[0.2 0.6 0 1   0.2 0.6 0 1   0 0 0 0]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = -180,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 6,
        particlelife       = 30,
        particlelifespread = 20,
        particlesize       = 12,
        particlesizespread = 8,
        particlespeed      = 2,
        particlespeedspread = 3,
        pos                = [[0, 1.0, 0]],
        sizegrowth         = -.1,
        sizemod            = 1,
        texture            = [[blooddropwhite]],
      },
    },
  },

  ["lobber_goo"] = {
    groundflash = {
      circlealpha        = .4,
      circlegrowth       = 0,
      flashalpha         = .3,
      flashsize          = 32,
      ttl                = 96,
      color = {
        [1]  = 0.20000000298023,
        [2]  = 0.60000002384186,
        [3]  = 0,
      },
    },
    pop = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      properties = {
        airdrag            = .9,
        colormap           = [[0.2 0.6 0 1   0.2 0.6 0 1   0 0 0 0]],
        directional        = false,
        emitrot            = 30,
        emitrotspread      = -60,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 32,
        particlelifespread = 0,
        particlesize       = 4,
        particlesizespread = 2,
        particlespeed      = 0,
        particlespeedspread = 0,
        pos                = [[0, 1.0, 0]],
        sizegrowth         = 6,
        sizemod            = 1,
        texture            = [[bloodblastwhite]],
      },
    },
  },

  ["small_red_goo"] = {
    splashes = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.9,
        colormap           = [[1 0 0 1   1 0 0 1   0 0 0 0]],
        directional        = true,
        emitrot            = 1,
        emitrotspread      = -2,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 5,
        particlelifespread = 5,
        particlesize       = 4,
        particlesizespread = 4,
        particlespeed      = 0.05,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 2,
        sizemod            = 1,
        texture            = [[blooddropwhite]],
      },
    },
  },

  ["red_goo"] = {
    groundflash = {
      circlealpha        = .4,
      circlegrowth       = 0,
      flashalpha         = .3,
      flashsize          = 32,
      ttl                = 128,
      color = {
        [1]  = 1,
        [2]  = 0,
        [3]  = 0,
      },
    },
    pop = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      properties = {
        airdrag            = .9,
        colormap           = [[1 0 0 1   1 0 0 1   0 0 0 0]],
        directional        = false,
        emitrot            = 45,
        emitrotspread      = 30,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 16,
        particlelifespread = 0,
        particlesize       = 12,
        particlesizespread = 8,
        particlespeed      = 0,
        particlespeedspread = 0,
        pos                = [[0, 1.0, 0]],
        sizegrowth         = 3,
        sizemod            = 1,
        texture            = [[bloodblastwhite]],
      },
    },
    splashes = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      properties = {
        airdrag            = .96,
        colormap           = [[1 0 0 1   1 0 0 1   0 0 0 0]],
        directional        = true,
        emitrot            = 180,
        emitrotspread      = 80,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 5,
        particlelife       = 12,
        particlelifespread = 8,
        particlesize       = 12,
        particlesizespread = 8,
        particlespeed      = 1.5,
        particlespeedspread = 3,
        pos                = [[0, 1.0, 0]],
        sizegrowth         = -.1,
        sizemod            = 1,
        texture            = [[blooddropwhite]],
      },
    },
  }
}

