-- factory_explosion

return {
  ["factory_explosion"] = {
    groundflash = {
      air                = true,
      alwaysvisible      = true,
      circlealpha        = 0.6,
      circlegrowth       = 6,
      flashalpha         = 0.9,
      flashsize          = 256,
      ground             = true,
      ttl                = 20,
      water              = true,
      color = {
        [1]  = 1,
        [2]  = 0.30000001192093,
        [3]  = 0,
      },
    },
    poof01 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.95,
        alwaysvisible      = true,
        colormap           = [[0.1 0.1 0.1 1.0	0.5 0.4 0.3 1.0		0 0 0 0.0]],
        directional        = true,
        emitrot            = 90,
        emitrotspread      = 0,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 180,
        particlelife       = 25,
        particlelifespread = 10,
        particlesize       = 15,
        particlesizespread = 5,
        particlespeed      = 1,
        particlespeedspread = 10,
        pos                = [[r-1 r1, 1, r-1 r1]],
        sizegrowth         = 1.2,
        sizemod            = 1.0,
        texture            = [[dirt]],
        useairlos          = true,
      },
    },
    pop1 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 2,
      ground             = true,
      water              = true,
      properties = {
        alwaysvisible      = true,
        heat               = 10,
        heatfalloff        = 0.8,
        maxheat            = 15,
        pos                = [[r-2 r2, 5, r-2 r2]],
        size               = 5,
        sizegrowth         = 15,
        speed              = [[0, 1 0, 0]],
        texture            = [[uglynovaexplo]],
      },
    },
    pop2 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 2,
      ground             = true,
      water              = true,
      properties = {
        alwaysvisible      = true,
        heat               = 10,
        heatfalloff        = 0.8,
        maxheat            = 15,
        pos                = [[r-2 r2, 5, r-2 r2]],
        size               = 5,
        sizegrowth         = 28,
        speed              = [[0, 1 0, 0]],
        texture            = [[flare]],
      },
    },
    smokeblack = {
      air                = true,
      class              = [[smoke]],
      count              = 22,
      ground             = true,
      water              = true,
      properties = {
        agespeed           = 0.01,
        alwaysvisible      = true,
        color              = 0.1,
        pos                = [[r-60 r60, 24, r-60 r60]],
        size               = 50,
        sizeexpansion      = 0.6,
        sizegrowth         = 15,
        speed              = [[r-4.0 r4.0, -1.5 r-1.0, r-4.0 r4.0]],
        startsize          = 10,
      },
    },
    smokegrey = {
      air                = true,
      class              = [[smoke]],
      count              = 8,
      ground             = true,
      water              = true,
      properties = {
        agespeed           = 0.02,
        alwaysvisible      = true,
        color              = 0.8,
        pos                = [[r-60 r60, 24, r-60 r60]],
        size               = 50,
        sizeexpansion      = 0.6,
        sizegrowth         = 15,
        speed              = [[r-3 r3, 1 r2.3, r-3 r3]],
        startsize          = 10,
      },
    },
  },

}

