-- klara
-- klara_smokejets

return {
  ["klara"] = {
    boom = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = [[0 i1]],
        explosiongenerator = [[custom:KLARA_SMOKEJETS]],
        pos                = [[0, 0,  0]],
      },
    },
  },

  ["klara_smokejets"] = {
    intense_center1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 20,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        colormap           = [[1 0.6 0 0.1    0.4 0.4 0.4 1    0.05 0.05 0.05 0.1]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[0.5, 1, 0.5]],
        gravity            = [[0.015 i-0.0015, -0.3 i+0.015,0.015 i-0.0015]],
        numparticles       = 1,
        particlelife       = [[50 i-0.5]],
        particlelifespread = 0,
        particlesize       = [[10 i0.8]],
        particlesizespread = 0,
        particlespeed      = [[5 i-0.25]],
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = [[-0.1 i0.015]],
        sizemod            = 1.0,
        texture            = [[smokesmall]],
      },
    },
    intense_center2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 20,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        colormap           = [[1 0.6 0 0.1    0.4 0.4 0.4 1    0.05 0.05 0.05 0.1]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[-0.8, 1, -0.2]],
        gravity            = [[-0.024 i+0.0024, -0.3 i+0.015,-0.006 i+0.0006]],
        numparticles       = 1,
        particlelife       = [[50 i-0.5]],
        particlelifespread = 0,
        particlesize       = [[10 i0.8]],
        particlesizespread = 0,
        particlespeed      = [[5 i-0.25]],
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = [[-0.1 i0.015]],
        sizemod            = 1.0,
        texture            = [[smokesmall]],
      },
    },
    intense_center3 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 20,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        colormap           = [[1 0.6 0 0.1    0.4 0.4 0.4 1    0.05 0.05 0.05 0.1]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[0.2, 1, -0.8]],
        gravity            = [[0.006 i-0.0006, -0.3 i+0.015,-0.024 i+0.0024]],
        numparticles       = 1,
        particlelife       = [[50 i-0.5]],
        particlelifespread = 0,
        particlesize       = [[10 i0.8]],
        particlesizespread = 0,
        particlespeed      = [[5 i-0.25]],
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = [[-0.1 i0.015]],
        sizemod            = 1.0,
        texture            = [[smokesmall]],
      },
    },
    star1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 5,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        colormap           = [[1 0.7 0.3 0.01    1 0.7 0.3 0.01    0.5 0.35 0.15 0.01    0.05 0.05 0.05 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[0.5, 1, 0.5]],
        gravity            = [[0.015 i-0.0015, -0.3 i+0.015,0.015 i-0.0015]],
        numparticles       = 2,
        particlelife       = [[50 i-0.5]],
        particlelifespread = 0,
        particlesize       = [[10 i0.8]],
        particlesizespread = 0,
        particlespeed      = [[5 i-0.25]],
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = [[-0.1 i0.015]],
        sizemod            = 1.0,
        texture            = [[plasma]],
      },
    },
    star2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 5,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        colormap           = [[1 0.7 0.3 0.01    1 0.7 0.3 0.01    0.5 0.35 0.15 0.01    0.05 0.05 0.05 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[-0.8, 1, -0.2]],
        gravity            = [[-0.024 i+0.0024, -0.3 i+0.015,-0.006 i+0.0006]],
        numparticles       = 2,
        particlelife       = [[50 i-0.5]],
        particlelifespread = 0,
        particlesize       = [[10 i0.8]],
        particlesizespread = 0,
        particlespeed      = [[5 i-0.25]],
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = [[-0.1 i0.015]],
        sizemod            = 1.0,
        texture            = [[plasma]],
      },
    },
    star3 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 7,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        colormap           = [[1 0.7 0.3 0.01    1 0.7 0.3 0.01    0.5 0.35 0.15 0.01    0.05 0.05 0.05 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[0.2, 1, -0.8]],
        gravity            = [[0.006 i-0.0006, -0.3 i+0.015,-0.024 i+0.0024]],
        numparticles       = 2,
        particlelife       = [[50 i-0.5]],
        particlelifespread = 0,
        particlesize       = [[10 i0.8]],
        particlesizespread = 0,
        particlespeed      = [[5 i-0.25]],
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = [[-0.1 i0.015]],
        sizemod            = 1.0,
        texture            = [[plasma]],
      },
    },
  },

}

