-- vulcanfx

return {
  ["vulcanfx"] = {
    usedefaultexplosions = false,
		
		
		
	exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        colormap           = [[1.0 0.8 0.5 0.1 0.15 0.15 0.15 0.2 0.0 0.0 0.0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 0.011,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 2,
        particlelife       = 17,
        particlelifespread = 15,
        particlesize       = 7,
        particlesizespread = 3,
        particlespeed      = 0.1,
        particlespeedspread = 0.5,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.16,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        colormap           = [[1.0 0.7 0.4 0.1 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = true,
        emitrot            = 0.006,
        emitrotspread      = 0.006,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 2,
        particlelife       = 17,
        particlelifespread = 15,
        particlesize       = 5,
        particlesizespread = 5,
        particlespeed      = 0.1,
        particlespeedspread = 0.5,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.16,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 3,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.16,
        color              = [[1.0, 0.8, 0.5]],
        dir                = [[-10 r20,-10 r20,-10 r20]],
        length             = 1,
        width              = 22,
        lengthGrowth       = 2,
      },
    },
	
	
    glare               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = true,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.3,
				alwaysvisible       = false,
				colormap            = [[0.45 0.25 0 0.01  0 0 0 0.01]],
				directional         = true,
				emitvector          = [[dir]],
				numparticles        = 1,
				particlelife        = 3,
				particlesize        = 60,
				particlespeed       = 0,
				sizegrowth          = 40,
				sizemod             = 1,
				texture             = [[glow]],
			},
		},
    
		front                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -1.5,
				sidetexture  = [[plasma]],
				size         = 90,
				ttl          = 1,
			},
		},
    
		mid                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -2,
				sidetexture  = [[smoothtrail]],
				size         = 20,
				ttl          = 1,
			},
		},
    
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0.09 0.05 0 0.01  0.05 0.045 0 0.01  0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[null]],
				length       = -3,
				sidetexture  = [[smoothtrail]],
				size         = 20,
				sizegrowth   = -0.2,
				ttl          = 10,
			},
		},
	},

}

