-- meteor_tag

return {
  ["meteor_tag"] = {
    usedefaultexplosions = false,
    fire = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.95,
        alwaysvisible      = true,
        colormap           = [[0.01 0.01 0.01 0.01  0.1 0.1 0.1 0.1  0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 5,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 30,
        particlelifespread = 5,
        particlesize       = 32,
        particlesizespread = 16,
        particlespeed      = 20,
        particlespeedspread = 8,
        pos                = [[0, 0, 0]],
        sizegrowth         = 3,
        sizemod            = 1,
        texture            = [[fireball]],
      },
    },
    pikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.1,
        alwaysvisible      = true,
        color              = [[1,0.5,0.125]],
        dir                = [[-16 r32, -16 r32, -16 r32]],
        length             = 1,
        lengthgrowth       = 1,
        width              = 64,
      },
    },
    smoke = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.95,
        alwaysvisible      = true,
        colormap           = [[0.02 0.01 0 0.01  0.2 0.1 0 0.1  0.2 0.1 0 0.2  0.2 0 0 0.2  0 0 0 0.2  0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 5,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 60,
        particlelifespread = 10,
        particlesize       = 24,
        particlesizespread = 16,
        particlespeed      = 20,
        particlespeedspread = 8,
        pos                = [[0, 0, 0]],
        sizegrowth         = 3,
        sizemod            = 1,
        texture            = [[smokesmall]],
      },
    },
  },

}

