-- missile_tag_white_10
-- missile_hit_sphere_120
-- missile_hit_pikes_160
-- missile_tag_white_40

return {
  ["missile_tag_white_10"] = {
    smoketrail = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.9,
        colormap           = [[1 1 0 0.6  1 0.25 0 0.4  1 1 1 0.2  0 0 0 0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 2,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 10,
        particlelifespread = 5,
        particlesize       = 4,
        particlesizespread = 4,
        particlespeed      = 20,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 1,
        sizemod            = 1,
        texture            = [[smokesmall]],
      },
    },
  },

  ["missile_hit_sphere_120"] = {
    usedefaultexplosions = false,
    mainhit = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        heat               = 15,
        heatfalloff        = 1,
        maxheat            = 15,
        pos                = [[0, 1, 0]],
        size               = 1,
        sizegrowth         = 8,
        speed              = [[0, 1, 0]],
        texture            = [[bigexplo]],
      },
    },
    pikes = {
      air                = true,
      class              = [[explspike]],
      count              = 32,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.05,
        color              = [[1,0.5,0]],
        dir                = [[-12 r12 r12, -12 r12 r12, -12 r12 r12]],
        length             = 1,
        lengthgrowth       = 1,
        width              = 6,
      },
    },
    sphere = {
      air                = true,
      class              = [[CSpherePartSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 0.5,
        color              = [[1,0.5,0]],
        expansionspeed     = 10,
        ttl                = 10,
      },
    },
  },

  ["missile_hit_pikes_160"] = {
    usedefaultexplosions = false,
    pikes = {
      air                = true,
      class              = [[explspike]],
      count              = 16,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.05,
        color              = [[1,0.5,0]],
        dir                = [[-8 r8 r8, -8 r8 r8, -8 r8 r8]],
        length             = 1,
        lengthgrowth       = 1,
        width              = 4,
      },
    },
    sparks = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[1 1 1 0.01  1 0.75 0 0.01  0 0 0 0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.2, 0]],
        numparticles       = 64,
        particlelife       = 20,
        particlelifespread = 5,
        particlesize       = 4,
        particlesizespread = 2,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[plasma]],
      },
    },
  },

  ["missile_tag_white_40"] = {
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.3 0.2 0.01 0.4 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[frontside]],
        length             = -70,
        sidetexture        = [[muzzleside]],
        size               = -15,
        sizegrowth         = 0.75,
        ttl                = 1,
      },
    },
    smoketrail = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.85 0.85 0.85 0.4    0.5 0.25 0 0.3     0 0 0 0.4  0 0 0 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 2,
        particlelife       = 20,
        particlelifespread = 40,
        particlesize       = 4,
        particlesizespread = 6,
        particlespeed      = 1,
        particlespeedspread = 10,
        pos                = [[r5, r5, r5]],
        sizegrowth         = 1.6,
        sizemod            = 1,
        texture            = [[smoke]],
      },
    },
  },

}

