-- missiletrailredsmall
-- missiletrailred
-- missiletrailyellow
-- missiletrailblue
-- missiletrailbluebig
-- chainsawtrail
-- cruisetrail
-- tactrail
-- bigemptrail
-- emptrail
-- raventrail
-- banishertrail
-- bdtrail
-- voidtrail

return {
  ["missiletrailredsmall"] = {
    alwaysvisible      = false,
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1 0.3 0.1 0.01 1 0.3 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -20,
        sidetexture        = [[muzzleside]],
        size               = -6,
        sizegrowth         = 0.75,
        ttl                = 2,
      },
    },

  },

  ["missiletrailred"] = {
    alwaysvisible      = false,
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1 0.3 0.1 0.01 1 0.3 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -20,
        sidetexture        = [[muzzleside]],
        size               = -6,
        sizegrowth         = 0.75,
        ttl                = 3,
      },
    },

    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.25,
        color              = [[0.8, 0.1, 0]],
        dir                = [[-6 r12,-6 r12,-6 r12]],
        length             = 9,
        width              = 6,
      },
    },
	
  },

  ["missiletrailyellow"] = {
    alwaysvisible      = false,
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[0.9 0.9 0.4 0.01 0.8 0.8 0.3 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -20,
        sidetexture        = [[muzzleside]],
        size               = -6,
        sizegrowth         = 0.75,
        ttl                = 1,
      },
    },

    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.5,
        color              = [[0.9, 0.9, 0.5]],
        dir                = [[-6 r12,-6 r12,-6 r12]],
        length             = 5,
        width              = 3,
      },
    },
  },

  ["missiletrailblue"] = {
    alwaysvisible      = false,
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[0.5 0.2 0.9 0.01 0.6 0.2 0.4 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -20,
        sidetexture        = [[muzzleside]],
        size               = -9,
        sizegrowth         = 0.75,
        ttl                = 1,
      },
    },

    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.3,
        color              = [[0.6, 0.6, 0.9]],
        dir                = [[-6 r12,-6 r12,-6 r12]],
        length             = 4,
        width              = 4,
      },
    },

 },
 
  ["missiletrailbluebig"] = {
    alwaysvisible      = false,
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[0.5 0.2 0.9 0.01 0.6 0.2 0.4 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -20,
        sidetexture        = [[muzzleside]],
        size               = -18,
        sizegrowth         = 0.75,
        ttl                = 1,
      },
    },

    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.3,
        color              = [[0.6, 0.6, 0.9]],
        dir                = [[-6 r12,-6 r12,-6 r12]],
        length             = 8,
        width              = 8,
      },
    },
 },
 
  ["chainsawtrail"] = {
    alwaysvisible      = false,
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[0.5 0.2 0.9 0.01 0.6 0.2 0.4 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -20,
        sidetexture        = [[muzzleside]],
        size               = -9,
        sizegrowth         = 0.75,
        ttl                = 1,
      },
    },

    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.3,
        color              = [[0.6, 0.6, 0.9]],
        dir                = [[-6 r12,-6 r12,-6 r12]],
        length             = 4,
        width              = 4,
      },
    },
	
    smoketrail = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.9,
        colormap           = [[0.65 0.65 0.85 0.4    0.3 0.2 0.5 0.3     1 1 1 0.1  0 0 0 0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 2,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 10,
        particlelifespread = 5,
        particlesize       = 4,
        particlesizespread = 4,
        particlespeed      = 20,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 1,
        sizemod            = 1,
        texture            = [[smokesmall]],
      },
    },
  },
 
["screamertrail"] = {
    alwaysvisible      = false,
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[0.5 0.2 0.9 0.01 0.6 0.2 0.4 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -20,
        sidetexture        = [[muzzleside]],
        size               = -18,
        sizegrowth         = 0.75,
        ttl                = 1,
      },
    },

    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.3,
        color              = [[0.6, 0.6, 0.9]],
        dir                = [[-6 r12,-6 r12,-6 r12]],
        length             = 8,
        width              = 8,
      },
    },
	
    smoketrail = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.65 0.65 0.85 0.4    0.8 0.8 0.9 0.2     1 1 1 0.1  0 0 0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 2,
        particlelife       = 20,
        particlelifespread = 40,
        particlesize       = 4,
        particlesizespread = 6,
        particlespeed      = 5,
        particlespeedspread = 5,
        pos                = [[r5, r5, r5]],
        sizegrowth         = 1.6,
        sizemod            = 1,
        texture            = [[smoke]],
      },
    },
  },

  ["cruisetrail"] = {
    alwaysvisible      = false,
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1 0.3 0.1 0.01 0.4 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -33,
        sidetexture        = [[muzzleside]],
        size               = -6,
        sizegrowth         = 0.75,
        ttl                = 5,
      },
    },

    smoke_front = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[0.8 0.4 0.1 0.4 0.3 0.3 0.3 0.6 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 50,
        emitvector         = [[dir]],
        gravity            = [[0.05 r-0.1, 0.05 r-0.1, 0.05 r-0.1]],
        numparticles       = 2,
        particlelife       = 20,
        particlelifespread = 0,
        particlesize       = 6,
        particlesizespread = 2,
        particlespeed      = 8,
        particlespeedspread = -4,
        pos                = [[0, 1, 3]],
        sizegrowth         = 1.5,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
	
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.25,
        color              = [[0.8, 0.1, 0]],
        dir                = [[-6 r12,-6 r12,-6 r12]],
        length             = 22,
        width              = 10,
      },
    },
  },
  
  ["tactrail"] = {
    alwaysvisible      = false,
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1 0.3 0.1 0.01 0.4 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -45,
        sidetexture        = [[muzzleside]],
        size               = -8,
        sizegrowth         = 0.75,
        ttl                = 8,
      },
    },

    smoke_front = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[0.8 0.4 0.1 0.4 0.3 0.3 0.3 0.6 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 50,
        emitvector         = [[dir]],
        gravity            = [[0.05 r-0.1, 0.05 r-0.1, 0.05 r-0.1]],
        numparticles       = 2,
        particlelife       = 30,
        particlelifespread = 0,
        particlesize       = 8,
        particlesizespread = 2,
        particlespeed      = 10,
        particlespeedspread = -4,
        pos                = [[0, 1, 3]],
        sizegrowth         = 1.5,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
	
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.25,
        color              = [[0.8, 0.1, 0]],
        dir                = [[-6 r12,-6 r12,-6 r12]],
        length             = 33,
        width              = 15,
      },
    },
  },
  
  ["bigemptrail"] = {
    alwaysvisible      = false,
    usedefaultexplosions = false,
    
    largeflash = {
      air                   = true,
      class                 = [[CBitmapMuzzleFlame]],
      count                 = 1,
      ground                = true,
      underwater            = 1,
      water                 = true,
      properties = {
        colormap            = [[1 1 0.25 0.01  0.5 0.5 0.1 0.01  0 0 0 0.01]],
        dir                 = [[dir]],
        frontoffset         = 0,
        fronttexture        = [[muzzlefront]],
        length              = -42,
        sidetexture         = [[muzzleside]],
        size                = -7,
        sizegrowth          = 0.75,
        ttl                 = 5,
      },
    },

    smoke_front = {
      air                   = true,
      class                 = [[CSimpleParticleSystem]],
      count                 = 1,
      ground                = true,
      water                 = true,
      properties = {
        airdrag             = 0.8,
        colormap            = [[0.8 0.8 0.4 0.8  0.5 0.5 0.3 0.7  0.0 0.0 0.0 0.01]],
        directional         = false,
        emitrot             = 0,
        emitrotspread       = 50,
        emitvector          = [[dir]],
        gravity             = [[0.05 r-0.1, 0.05 r-0.1, 0.05 r-0.1]],
        numparticles        = 3,
        particlelife        = 15,
        particlelifespread  = 0,
        particlesize        = 6,
        particlesizespread  = 3,
        particlespeed       = 8,
        particlespeedspread = -4,
        pos                 = [[0, 1, 3]],
        sizegrowth          = 1.03,
        sizemod             = 1.1,
        texture             = [[smoke]],
      },
    },
    
    sparks = {
      air                   = true,
      class                 = [[CSimpleParticleSystem]],
      count                 = 1,
      ground                = true,
      water                 = true,
      properties = {
        airdrag             = 0.97,
        colormap            = [[1 1 0.2 0.01   1 1 0.4 0.01   0.0 0.0 0 0.01]],
        directional         = true,
        emitrot             = 0,
        emitrotspread       = 60,
        emitvector          = [[0, 1, 0]],
        gravity             = [[0, 0, 0]],
        numparticles        = 2,
        particlelife        = 17,
        particlelifespread  = 7,
        particlesize        = 7,
        particlesizespread  = 0,
        particlespeed       = 5,
        particlespeedspread = 0,
        pos                 = [[0, 0, 0]],
        sizegrowth          = 0,
        sizemod             = 1.0,
        texture             = [[spark]],
      },
    },

    spikes = {
      air                   = true,
      class                 = [[explspike]],
      count                 = 4,
      ground                = true,
      water                 = true,
      properties = {
        alpha               = 1,
        alphadecay          = 0.25,
        color               = [[0.9, 0.8, 0.4]],
        dir                 = [[-6 r12,-6 r12,-6 r12]],
        length              = 24,
        width               = 8,
      },
    },
  },
  
  ["emptrail"] = {
    alwaysvisible           = false,
    usedefaultexplosions    = false,
    
    smoke_front = {
      air                   = true,
      class                 = [[CSimpleParticleSystem]],
      count                 = 1,
      ground                = true,
      water                 = true,
      properties = {
        airdrag             = 0.8,
        colormap            = [[0.8 0.8 0.4 0.8  0.5 0.5 0.3 0.7  0.0 0.0 0.0 0.01]],
        directional         = false,
        emitrot             = 0,
        emitrotspread       = 50,
        emitvector          = [[dir]],
        gravity             = [[0.05 r-0.1, 0.05 r-0.1, 0.05 r-0.1]],
        numparticles        = 2,
        particlelife        = 10,
        particlelifespread  = 0,
        particlesize        = 6,
        particlesizespread  = 2,
        particlespeed       = 4,
        particlespeedspread = -4,
        pos                 = [[0, 1, 3]],
        sizegrowth          = 1.3,
        sizemod             = 1.0,
        texture             = [[smoke]],
      },
    },
    
    sparks = {
      air                   = true,
      class                 = [[CSimpleParticleSystem]],
      count                 = 1,
      ground                = true,
      water                 = true,
      properties = {
        airdrag             = 0.97,
        colormap            = [[1 1 0.2 0.01   1 1 0.4 0.01   0.0 0.0 0 0.01]],
        directional         = true,
        emitrot             = 0,
        emitrotspread       = 60,
        emitvector          = [[0, 1, 0]],
        gravity             = [[0, 0, 0]],
        numparticles        = 1,
        particlelife        = 12,
        particlelifespread  = 5,
        particlesize        = 5,
        particlesizespread  = 0,
        particlespeed       = 3,
        particlespeedspread = 0,
        pos                 = [[0, 0, 0]],
        sizegrowth          = 0,
        sizemod             = 1.0,
        texture             = [[spark]],
      },
    },
   
    spikes = {
      air                   = true,
      class                 = [[explspike]],
      count                 = 4,
      ground                = true,
      water                 = true,
      properties = {
        alpha               = 1,
        alphadecay          = 0.25,
        color               = [[0.9, 0.8, 0.4]],
        dir                 = [[-6 r12,-6 r12,-6 r12]],
        length              = 16,
        width               = 5,
      },
    },
  },

  ["raventrail"] = {
    alwaysvisible      = false,
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1 0.3 0.1 0.01 0.4 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -33,
        sidetexture        = [[muzzleside]],
        size               = -6,
        sizegrowth         = 0.75,
        ttl                = 5,
      },
    },

    smoke_front = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[0.8 0.4 0.1 0.4 0.3 0.3 0.3 0.6 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 50,
        emitvector         = [[dir]],
        gravity            = [[0.05 r-0.1, 0.05 r-0.1, 0.05 r-0.1]],
        numparticles       = 2,
        particlelife       = 20,
        particlelifespread = 0,
        particlesize       = 6,
        particlesizespread = 2,
        particlespeed      = 8,
        particlespeedspread = -4,
        pos                = [[0, 1, 3]],
        sizegrowth         = 1.5,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.25,
        color              = [[0.8, 0.1, 0]],
        dir                = [[-6 r12,-6 r12,-6 r12]],
        length             = 22,
        width              = 10,
      },
    },
  },

  ["banishertrail"] = {
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[0.9 0.9 0.4 0.01 0.8 0.8 0.3 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -25,
        sidetexture        = [[muzzleside]],
        size               = -4,
        sizegrowth         = 0.75,
        ttl                = 8,
      },
    },
    smoke_back = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[0.9 0.9 0.4 0.01   0.7 0.7 0.7 0.01  0.7 0.7 0.7 0.01 0 0 0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, 0.05, 0]],
        numparticles       = 5,
        particlelife       = 6,
        particlelifespread = 5,
        particlesize       = 1,
        particlesizespread = 0.5,
        particlespeed      = -2,
        particlespeedspread = -12,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.05,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    smoke_front = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        colormap           = [[0.9 0.9 0.4 0.01   0.7 0.7 0.7 0.01  0.7 0.7 0.7 0.01 0 0 0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 20,
        emitvector         = [[dir]],
        gravity            = [[0.05 r-0.1, 0.05 r-0.1, 0.05 r-0.1]],
        numparticles       = 5,
        particlelife       = 3,
        particlelifespread = 1,
        particlesize       = 4,
        particlesizespread = 2,
        particlespeed      = 1,
        particlespeedspread = -2,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.01,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.25,
        color              = [[0.9, 0.9, 0.5]],
        dir                = [[-6 r12,-6 r12,-6 r12]],
        length             = 1,
        width              = 10,
      },
    },
  },


  ["bdtrail"] = {
    usedefaultexplosions = false,
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1 0.3 0.1 0.01  1 0.3 0.1 0.01  0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -25,
        sidetexture        = [[muzzleside]],
        size               = -4,
        sizegrowth         = 0.75,
        ttl                = 8,
      },
    },
    smoke_back = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.8,
        colormap           = [[1 0.3 0.1 0.01  0.1 0 0 0.01  0.1 0 0 0.01  0 0 0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 10,
        emitvector         = [[dir]],
        gravity            = [[0, 0.05, 0]],
        numparticles       = 5,
        particlelife       = 6,
        particlelifespread = 5,
        particlesize       = 1,
        particlesizespread = 0.5,
        particlespeed      = -2,
        particlespeedspread = -12,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.05,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    smoke_front = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        colormap           = [[1 0.3 0.1 0.01  0.1 0 0 0.01  0.1 0 0 0.01  0 0 0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 20,
        emitvector         = [[dir]],
        gravity            = [[0.05 r-0.1, 0.05 r-0.1, 0.05 r-0.1]],
        numparticles       = 5,
        particlelife       = 3,
        particlelifespread = 1,
        particlesize       = 4,
        particlesizespread = 2,
        particlespeed      = 1,
        particlespeedspread = -2,
        pos                = [[0, 1, 3]],
        sizegrowth         = 0.01,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    spikes = {
      air                = true,
      class              = [[explspike]],
      count              = 4,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.25,
        color              = [[0.8, 0.1, 0]],
        dir                = [[-6 r12,-6 r12,-6 r12]],
        length             = 1,
        width              = 10,
      },
    },
  },
  ["voidtrail"] = {
    alwaysvisible        = false,
    usedefaultexplosions = false,
  },
}


