-- nuke_30_seacloud
-- nuke_30_landcloud_ring
-- nuke_30_landcloud
-- nuke_30_landcloud_topcap
-- nuke_30_landcloud_cap
-- nuke_30_seacloud_topcap
-- nuke_30_seacloud_ring
-- nuke_30
-- nuke_30_seacloud_cap
-- nuke_30_seacloud_pillar
-- nuke_30_landcloud_pillar

return {
  ["nuke_30_seacloud"] = {
    usedefaultexplosions = false,
    cap = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 24,
      ground             = true,
      water              = true,
	  underwater		 = true,
      properties = {
        delay              = [[i1]],
        dir                = [[dir]],
        explosiongenerator = [[custom:NUKE_30_SEACLOUD_CAP]],
        pos                = [[0, i1.6, 0]],
      },
    },
    pillar = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 32,
      ground             = true,
      water              = true,
	  underwater		 = true,
      properties = {
        delay              = [[i1]],
        dir                = [[dir]],
        explosiongenerator = [[custom:NUKE_30_SEACLOUD_PILLAR]],
        pos                = [[0, i1.6, 0]],
      },
    },
    ring = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
	  underwater		 = true,
      properties = {
        delay              = 16,
        dir                = [[dir]],
        explosiongenerator = [[custom:NUKE_30_SEACLOUD_RING]],
        pos                = [[0, 25.6, 0]],
      },
    },
    topcap = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 8,
      ground             = true,
      water              = true,
	  underwater		 = true,
      properties = {
        delay              = [[24 i1]],
        dir                = [[dir]],
        explosiongenerator = [[custom:NUKE_30_SEACLOUD_TOPCAP]],
        pos                = [[0, 38.4 i1.6, 0]],
      },
    },
  },

  ["nuke_30_landcloud_ring"] = {
    land = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.9,
        alwaysvisible      = true,
        colormap           = [[0 0 0 0  1 1 0.75 1  1 0.75 0.5 1  0.75 0.75 0.75 1  0 0 0 0]],
        directional        = false,
        emitrot            = 90,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.04, 0]],
        numparticles       = 30,
        particlelife       = 60,
        particlelifespread = 10,
        particlesize       = 1,
        particlesizespread = 1,
        particlespeed      = 3,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 8,
        sizemod            = 0.5,
        texture            = [[smokesmall]],
      },
    },
  },

  ["nuke_30_landcloud"] = {
    usedefaultexplosions = false,
    cap = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 24,
      ground             = true,
      water              = true,
      properties = {
        delay              = [[i1]],
        dir                = [[dir]],
        explosiongenerator = [[custom:NUKE_30_LANDCLOUD_CAP]],
        pos                = [[0, i1.6, 0]],
      },
    },
    pillar = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 32,
      ground             = true,
      water              = true,
      properties = {
        delay              = [[i1]],
        dir                = [[dir]],
        explosiongenerator = [[custom:NUKE_30_LANDCLOUD_PILLAR]],
        pos                = [[0, i1.6, 0]],
      },
    },
    ring = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        delay              = 16,
        dir                = [[dir]],
        explosiongenerator = [[custom:NUKE_30_LANDCLOUD_RING]],
        pos                = [[0, 25.6, 0]],
      },
    },
    topcap = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 8,
      ground             = true,
      water              = true,
      properties = {
        delay              = [[24 i1]],
        dir                = [[dir]],
        explosiongenerator = [[custom:NUKE_30_LANDCLOUD_TOPCAP]],
        pos                = [[0, 38.4 i1.6, 0]],
      },
    },
  },

  ["nuke_30_landcloud_topcap"] = {
    land = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.9,
        alwaysvisible      = true,
        colormap           = [[0 0 0 0  1 1 0 1  1 1 1 0.75  0.25 0.25 0.25 0.5  0 0 0 0]],
        directional        = false,
        emitrot            = 90,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.04, 0]],
        numparticles       = 4,
        particlelife       = 60,
        particlelifespread = 10,
        particlesize       = 1,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 4,
        sizemod            = 0.75,
        texture            = [[fireball]],
      },
    },
  },

  ["nuke_30_landcloud_cap"] = {
    land = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.9,
        alwaysvisible      = true,
        colormap           = [[0 0 0 0  1 1 0 1  1 1 1 0.75  0.25 0.25 0.25 0.5  0 0 0 0]],
        directional        = false,
        emitrot            = 90,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.04, 0]],
        numparticles       = 4,
        particlelife       = 15,
        particlelifespread = 5,
        particlesize       = 1,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 4,
        sizemod            = 0.75,
        texture            = [[fireball]],
      },
    },
  },

  ["nuke_30_seacloud_topcap"] = {
    cloud = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
	  underwater		 = true,
      properties = {
        airdrag            = 0.9,
        alwaysvisible      = true,
        colormap           = [[0 0 0 0  0.8 0.8 1 1  0.8 0.8 1 0.75  0.8 0.8 1 0.5  0 0 0 0]],
        directional        = false,
        emitrot            = 90,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.04, 0]],
        numparticles       = 4,
        particlelife       = 60,
        particlelifespread = 10,
        particlesize       = 1,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 4,
        sizemod            = 0.75,
        texture            = [[smokesmall]],
      },
    },
  },

  ["nuke_30_seacloud_ring"] = {
    cloud = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
	  underwater		 = true,
      properties = {
        airdrag            = 0.9,
        alwaysvisible      = true,
        colormap           = [[0 0 0 0  0.8 0.8 1 1  0.8 0.8 1 0.75  0.8 0.8 1 0.5  0 0 0 0]],
        directional        = false,
        emitrot            = 90,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.04, 0]],
        numparticles       = 128,
        particlelife       = 60,
        particlelifespread = 10,
        particlesize       = 1,
        particlesizespread = 1,
        particlespeed      = 4,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 2,
        sizemod            = 0.5,
        texture            = [[smokesmall]],
      },
    },
  },

  ["nuke_30"] = {
    usedefaultexplosions = false,
    groundflash = {
      alwaysvisible      = true,
      circlealpha        = 1,
      circlegrowth       = 4,
      flashalpha         = 0.5,
      flashsize          = 150,
      ttl                = 15,
      color = {
        [1]  = 1,
        [2]  = 0.5,
        [3]  = 0,
      },
    },
    landcloud = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      properties = {
        delay              = 15,
        dir                = [[dir]],
        explosiongenerator = [[custom:NUKE_30_LANDCLOUD]],
        pos                = [[0, 0, 0]],
      },
    },
    landdirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.95,
        alwaysvisible      = true,
        colormap           = [[0 0 0 0  0.5 0.4 0.3 1  0.6 0.4 0.2 0.75  0.5 0.4 0.3 0.5  0 0 0 0]],
        directional        = false,
        emitrot            = 85,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.03, 0]],
        numparticles       = 64,
        particlelife       = 30,
        particlelifespread = 5,
        particlesize       = 2,
        particlesizespread = 2,
        particlespeed      = 1,
        particlespeedspread = 3,
        pos                = [[0, 0, 0]],
        sizegrowth         = 2,
        sizemod            = 0.75,
        texture            = [[dirt]],
      },
    },
    pikes = {
      air                = true,
      class              = [[explspike]],
      count              = 32,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.025,
        alwaysvisible      = true,
        color              = [[1,0.5,0.1]],
        dir                = [[-2 r4, -2 r4, -2 r4]],
        length             = 1,
        lengthgrowth       = 1,
        width              = 64,
      },
    },
    seacloud = {
      class              = [[CExpGenSpawner]],
      count              = 1,
      water              = true,
	  underwater		 = true,
      properties = {
        delay              = 15,
        dir                = [[dir]],
        explosiongenerator = [[custom:NUKE_30_SEACLOUD]],
        pos                = [[0, 0, 0]],
      },
    },
    sphere = {
      air                = true,
      class              = [[CSpherePartSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
	  underwater		 = true,
      properties = {
        alpha              = 0.5,
        color              = [[1,1,0.5]],
        expansionspeed     = 4,
        ttl                = 20,
      },
    },
    watermist = {
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      water              = true,
	  underwater		 = true,
      properties = {
        airdrag            = 0.99,
        alwaysvisible      = true,
        colormap           = [[0 0 0 0  0.8 0.8 1 1  0.8 0.8 1 0.75  0.8 0.8 1 0.5  0 0 0 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 90,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.04, 0]],
        numparticles       = 16,
        particlelife       = 30,
        particlelifespread = 5,
        particlesize       = 1,
        particlesizespread = 1,
        particlespeed      = 2,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 1,
        sizemod            = 1,
        texture            = [[smokesmall]],
      },
    },
  },

  ["nuke_30_seacloud_cap"] = {
    cloud = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
	  underwater		 = true,
      properties = {
        airdrag            = 0.9,
        alwaysvisible      = true,
        colormap           = [[0 0 0 0  0.8 0.8 1 1  0.8 0.8 1 0.75  0.8 0.8 1 0.5  0 0 0 0]],
        directional        = false,
        emitrot            = 90,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.04, 0]],
        numparticles       = 4,
        particlelife       = 15,
        particlelifespread = 5,
        particlesize       = 1,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 4,
        sizemod            = 0.75,
        texture            = [[smokesmall]],
      },
    },
  },

  ["nuke_30_seacloud_pillar"] = {
    cloud = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
	  underwater		 = true,
      properties = {
        airdrag            = 0.9,
        alwaysvisible      = true,
        colormap           = [[0 0 0 0  0.8 0.8 1 1  0.8 0.8 1 0.75  0.8 0.8 1 0.5  0 0 0 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 90,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.04, 0]],
        numparticles       = 1,
        particlelife       = 60,
        particlelifespread = 10,
        particlesize       = 1,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 4,
        sizemod            = 0.75,
        texture            = [[smokesmall]],
      },
    },
  },

  ["nuke_30_landcloud_pillar"] = {
    land = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.9,
        alwaysvisible      = true,
        colormap           = [[0 0 0 0  1 1 0.5 1  1 0.75 0.5 0.75  0.25 0.25 0.25 0.5  0 0 0 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 90,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.04, 0]],
        numparticles       = 1,
        particlelife       = 60,
        particlelifespread = 10,
        particlesize       = 1,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 4,
        sizemod            = 0.75,
        texture            = [[smokesmall]],
      },
    },
  },

}

