-- plasma_hit_32
-- plasma_hit_96

return {
  ["plasma_hit_32"] = {
    usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 0.25,
      circlegrowth       = 4,
      flashalpha         = 0.5,
      flashsize          = 32,
      ttl                = 8,
      color = {
        [1]  = 1,
        [2]  = 0.5,
        [3]  = 0,
      },
    },
    mainhit = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        heat               = 8,
        heatfalloff        = 1,
        maxheat            = 8,
        pos                = [[0, 1, 0]],
        size               = 1,
        sizegrowth         = 2,
        speed              = [[0, 1, 0]],
        texture            = [[fireyexplo]],
      },
    },
    pikes = {
      air                = true,
      class              = [[explspike]],
      count              = 16,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.125,
        color              = [[1,0.5,0]],
        dir                = [[-4 r8, -4 r8, -4 r8]],
        length             = 1,
        width              = 8,
      },
    },
    sphere = {
      air                = true,
      class              = [[CSpherePartSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 0.125,
        alwaysvisible      = false,
        color              = [[1,1,1]],
        expansionspeed     = 4,
        ttl                = 8,
      },
    },
  },

  ["plasma_hit_96"] = {
    usedefaultexplosions = false,
    groundflash = {
      circlealpha        = 0.25,
      circlegrowth       = 6,
      flashalpha         = 0.5,
      flashsize          = 96,
      ttl                = 16,
      color = {
        [1]  = 1,
        [2]  = 0.5,
        [3]  = 0,
      },
    },
    landdirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.04 0.03 0.02 0.05  0.4 0.3 0.2 0.5  0.04 0.03 0.02 0.05]],
        directional        = false,
        emitrot            = 85,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 16,
        particlelife       = 16,
        particlelifespread = 4,
        particlesize       = 4,
        particlesizespread = 4,
        particlespeed      = 4,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 6,
        sizemod            = 0.75,
        texture            = [[dirt]],
      },
    },
    mainhit = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        heat               = 16,
        heatfalloff        = 1,
        maxheat            = 16,
        pos                = [[0, 1, 0]],
        size               = 1,
        sizegrowth         = 3,
        speed              = [[0, 1, 0]],
        texture            = [[fireyexplo]],
      },
    },
    mainhit2 = {
      air                = true,
      class              = [[heatcloud]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        heat               = 16,
        heatfalloff        = 1,
        maxheat            = 16,
        pos                = [[0, 1, 0]],
        size               = 1,
        sizegrowth         = 3,
        speed              = [[0, 1, 0]],
        texture            = [[uglynovaexplo]],
      },
    },
    pikes = {
      air                = true,
      class              = [[explspike]],
      count              = 16,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.06,
        color              = [[1,0.5,0]],
        dir                = [[-6 r12, -6 r12, -6 r12]],
        length             = 1,
        width              = 24,
      },
    },
    sphere = {
      air                = true,
      class              = [[CSpherePartSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 0.125,
        alwaysvisible      = false,
        color              = [[1,1,1]],
        expansionspeed     = 3,
        ttl                = 16,
      },
    },
    watermist = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      water              = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0.04 0.04 0.05 0.05  0.4 0.4 0.5 0.5  0.04 0.04 0.05 0.05]],
        directional        = false,
        emitrot            = 85,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 16,
        particlelife       = 16,
        particlelifespread = 4,
        particlesize       = 4,
        particlesizespread = 4,
        particlespeed      = 4,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 6,
        sizemod            = 0.75,
        texture            = [[smokesmall]],
      },
    },
  },

}

