return {
	["plasma_cannon_muzzle_blue"] = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[1 1 1 0.025 0 0.1 1 0.01    0 0.1 1 0.01    0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[muzzlefront]],
				length       = 24,
				sidetexture  = [[muzzleside]],
				size         = 16,
				sizegrowth   = -0.5,
				ttl          = 16,
			},
		},
	},
	["plasmatrail_yellow_small"]  = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
		head                 = {
			air        = true,
			class      = [[heatcloud]],
			count      = 2,
			ground     = true,
			water      = true,
			underwater = 1,
			unit       = 1,
			properties = {
				alwaysvisible = false,
				heat          = 100,
				heatfalloff   = 15,
				maxheat       = 100,
				pos           = [[0 0 0]],
				size          = 10,
				sizegrowth    = -2.5,
				speed         = [[0 0 0]],
				texture       = [[redexplo]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[1 0.7 0.2 0.01    1 0.7 0.2 0.01    0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[muzzlefront]],
				length       = -3,
				sidetexture  = [[muzzleside]],
				size         = 4,
				sizegrowth   = -0.3,
				ttl          = 4,
			},
		},
		sparks               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = 1,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.7,
				alwaysvisible       = false,
				colormap            = [[1 0.7 0.2 0.01    1 0.7 0.2 0.01    0 0 0 0.01]],
				directional         = true,
				emitrotspread       = 0.1,
				emitvector          = [[dir]],
				gravity             = [[0 -0.01 0]];
				numparticles        = 2,
				particlelife        = 10,
				particlelifespread  = 10,
				particlesize        = 2.5,
				particlesizespread  = 0.5,
				particlespeed       = -0.25,
				particlespeedspread = 0.2,
				pos                 = [[-2r4 -2r4 -2r4]],
				sizegrowth          = 0,
				sizemod             = 0.95,
				texture             = [[redexplo]],
			},
		},
	},
	["plasmatrail_blue_small"]    = {
		alwaysvisible        = false,
		usedefaultexplosions = false,
		head                 = {
			air        = true,
			class      = [[heatcloud]],
			count      = 2,
			ground     = true,
			water      = true,
			underwater = 1,
			unit       = 1,
			properties = {
				alwaysvisible = false,
				directional   = true,
				heat          = 100,
				heatfalloff   = 50,
				maxheat       = 100,
				pos           = [[0 0 0]],
				size          = [[6 r4]],
				sizegrowth    = -1,
				speed         = [[dir]],
				texture       = [[bluenovaexplo]],
			},
		},
		shaft                = {
			air        = true,
			class      = [[CBitmapMuzzleFlame]],
			count      = 1,
			ground     = true,
			underwater = 1,
			water      = true,
			properties = {
				colormap     = [[0 0.1 1 0.01    0 0.1 1 0.01    0 0 0 0.01]],
				dir          = [[dir]],
				frontoffset  = 0,
				fronttexture = [[muzzlefront]],
				length       = -4,
				sidetexture  = [[muzzleside]],
				size         = 4,
				sizegrowth   = -0.3,
				ttl          = 5,
			},
		},
		sparks               = {
			class      = [[CSimpleParticleSystem]],
			count      = 1,
			ground     = true,
			air        = true,
			unit       = 1,
			water      = true,
			underwater = true,
			properties = {
				airdrag             = 0.7,
				alwaysvisible       = false,
				colormap            = [[0 0.1 1 0.01    0 0.1 1 0.01    0 0 0 0.01]],
				directional         = true,
				emitrotspread       = 0.1,
				emitvector          = [[dir]],
				gravity             = [[0 -0.01 0]];
				numparticles        = [[r3]],
				particlelife        = 10,
				particlelifespread  = 10,
				particlesize        = 2.5,
				particlesizespread  = 0.5,
				particlespeed       = 1,
				particlespeedspread = 0.2,
				pos                 = [[-2r4 -2r4 -2r4]],
				sizegrowth          = 0.1,
				sizemod             = 0.99,
				texture             = [[bluenovaexplo]],
			},
		},
	}
}

