-- chloe

return {
  ["chloe"] = {
    glow = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 20,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        colormap           = [[1 0.5 0 1      1 1 0.5 1    0.3 0.3 0.3 0     0 0 0 0.01  ]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 90,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.0005, 0]],
        numparticles       = 1,
        particlelife       = [[5 i5]],
        particlelifespread = 10,
        particlesize       = 3,
        particlesizespread = 0,
        particlespeed      = 0.1,
        particlespeedspread = 0.1,
        pos                = [[0, 0, 0]],
        sizegrowth         = [[3 i-0.04]],
        sizemod            = 1.0,
        texture            = [[ksquareblur]],
      },
    },
    meteors = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 20,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 1,
        colormap           = [[1 1 1 1      1 1 1 1    1 1 1 1     0 0 0 0.01  ]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 90,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 40,
        particlelifespread = 1,
        particlesize       = 2,
        particlesizespread = 2,
        particlespeed      = 2,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0,
        sizemod            = 1.0,
        texture            = [[kthinmeteor]],
      },
    },
  },

}

