-- vindimuzzle
-- vindiback
-- uw_vindiback
-- uw_amphlift

return {
  ["vindimuzzle"] = {
    fluffy = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        useairlos       = false,
        colormap           = [[1 1 1 1 0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 15,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 3,
        particlelifespread = 5,
        particlesize       = 10,
        particlesizespread = 0,
        particlespeed      = 8,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.2,
        sizemod            = 1.0,
        texture            = [[smokesmall]],
      },
    },
  },

  ["vindiback"] = {
    fire = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        useairlos       = false,
        colormap           = [[1 1 0 0.9      1 0.8  0.3 08    0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 15,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 2,
        particlelife       = 6,
        particlelifespread = 0,
        particlesize       = 5,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 2,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[orangesmoke2]],
      },
    },
    fluffy = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.6,
        useairlos       = false,
        colormap           = [[1 1 1 1 0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 30,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 3,
        particlelife       = 3,
        particlelifespread = 5,
        particlesize       = 10,
        particlesizespread = 0,
        particlespeed      = 7,
        particlespeedspread = 6,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.2,
        sizemod            = 1.0,
        texture            = [[smokesmall]],
      },
    },
    takeoff1 = {
      air                = false,
      useairlos       = false,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater         = 0,
      water              = false,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0 0 0 0.001 0.04 0.04 0.04 0.2    0 0 0 0.001]],
        emitrot            = 90,
        emitrotspread      = 0,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.1, 0]],
        numparticles       = 15,
        particlelife       = 40,
        particlelifespread = 0,
        particlesize       = 4,
        particlesizespread = 1,
        particlespeed      = 5,
        particlespeedspread = 0,
        pos                = [[15, 1, 0]],
        sizegrowth         = 0.3,
        sizemod            = 1.0,
        texture            = [[kfoam]],
      },
    },
  },

  ["uw_vindiback"] = {
    fire = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
	  underwater         = true,
      properties = {
        airdrag            = 0.6,
        useairlos       = false,
        colormap           = [[1 1 0 0.9      1 0.8  0.3 08    0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 15,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 2,
        particlelife       = 12,
        particlelifespread = 0,
        particlesize       = 5,
        particlesizespread = 0,
        particlespeed      = 1,
        particlespeedspread = 1,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.5,
        sizemod            = 1.0,
        texture            = [[orangesmoke2]],
      },
    },
    fluffy = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      underwater         = true,
      properties = {
        airdrag            = 0.6,
        useairlos       = false,
        colormap           = [[1 1 1 1 0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 30,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 3,
        particlelife       = 6,
        particlelifespread = 10,
        particlesize       = 10,
        particlesizespread = 0,
        particlespeed      = 3.5,
        particlespeedspread = 3,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.2,
        sizemod            = 1.0,
        texture            = [[smokesmall]],
      },
    },
    takeoff1 = {
      air                = false,
      useairlos       = false,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = false,
      underwater         = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0 0 0 0.001 0.04 0.04 0.04 0.2    0 0 0 0.001]],
        emitrot            = 90,
        emitrotspread      = 0,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.005, 0]],
        numparticles       = 15,
        particlelife       = 80,
        particlelifespread = 0,
        particlesize       = 4,
        particlesizespread = 1,
        particlespeed      = 2.5,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.3,
        sizemod            = 1.0,
        texture            = [[kfoam]],
      },
    },
  },

  ["uw_amphlift"] = {
    takeoff1 = {
      air                = false,
      useairlos       = false,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = false,
      underwater         = true,
      properties = {
        airdrag            = 0.95,
        colormap           = [[0 0 0 0.001 0.04 0.04 0.04 0.2    0 0 0 0.001]],
        emitrot            = 90,
        emitrotspread      = 0,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.005, 0]],
        numparticles       = 15,
        particlelife       = 80,
        particlelifespread = 0,
        particlesize       = 4,
        particlesizespread = 1,
        particlespeed      = 2.5,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 0.3,
        sizemod            = 1.0,
        texture            = [[kfoam]],
      },
    },
  },
}

