-- small_nuke_explosion_fx

return {
  ["small_nuke_explosion_fx"] = {
    usedefaultexplosions = false,
    g_blast = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.87,
        colormap           = [[1 0.25 0 0.01		0.4 0.3 0.2 0.01 	0 0 0 0.01	 0 0 0 0.01]],
        directional        = true,
        emitrot            = 80,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 150,
        particlelife       = 60,
        particlelifespread = 30,
        particlesize       = 32,
        particlesizespread = 10,
        particlespeed      = 17,
        particlespeedspread = 18,
        pos                = [[3 r-3, 1 r-2, 3 r-3]],
        sizegrowth         = 0.14,
        sizemod            = 1.0,
        texture            = [[splash]],
      },
    },
    g_blast11 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.88,
        colormap           = [[0 0 0 0.01 0.2 0.2 0.2 0.9 0 0 0 0.01]],
        directional        = true,
        emitrot            = 80,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 50,
        particlelife       = 180,
        particlelifespread = 30,
        particlesize       = 48,
        particlesizespread = 24,
        particlespeed      = 1,
        particlespeedspread = 32,
        pos                = [[3 r-3, 1 r-2, 3 r-3]],
        sizegrowth         = 0.14,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    g_blast2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.87,
        colormap           = [[1 0.25 0 0.01 		0.3 0.2 0.1 0.01 	0 0 0 0.01 	0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 80,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 200,
        particlelife       = 60,
        particlelifespread = 30,
        particlesize       = 32,
        particlesizespread = 13,
        particlespeed      = 17,
        particlespeedspread = 15,
        pos                = [[3 r-3, 1 r-2, 3 r-3]],
        sizegrowth         = 0.14,
        sizemod            = 1.0,
        texture            = [[splash]],
      },
    },
    g_blast22 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.88,
        colormap           = [[0 0 0 0.01 0.1 0.1 0.1 0.5 0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 80,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 50,
        particlelife       = 180,
        particlelifespread = 30,
        particlesize       = 48,
        particlesizespread = 24,
        particlespeed      = 1,
        particlespeedspread = 32,
        pos                = [[3 r-3, 1 r-2, 3 r-3]],
        sizegrowth         = 0.14,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    g_smokewave1 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.92,
        colormap           = [[1 0.3 0.2 0.01 	1 0.5 0.2 0.01 	0.1 0.1 0.1 0.01 	0.1 0.1 0.1 0.01 	0 0 0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 35,
        particlelife       = 38,
        particlelifespread = 15,
        particlesize       = 13,
        particlesizespread = 1,
        particlespeed      = 20,
        particlespeedspread = 1,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.16,
        sizemod            = 1.0,
        texture            = [[YELLOWBLAST]],
      },
    },
    g_smokewave2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.92,
        colormap           = [[1 0.3 0.2 0.01 	1 0.5 0.2 0.01	 0.1 0.1 0.1 0.01 	0.1 0.1 0.1 0.01 	0 0 0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 35,
        particlelife       = 38,
        particlelifespread = 15,
        particlesize       = 13,
        particlesizespread = 1,
        particlespeed      = 20,
        particlespeedspread = 1,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.16,
        sizemod            = 1.0,
        texture            = [[YELLOWBLAST1]],
      },
    },
    g_smokewave3 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.92,
        colormap           = [[1 0.3 0.2 0.01 	1 0.5 0.2 0.01 	0.1 0.1 0.1 0.01 	0.1 0.1 0.1 0.01 	0 0 0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 35,
        particlelife       = 38,
        particlelifespread = 15,
        particlesize       = 13,
        particlesizespread = 1,
        particlespeed      = 20,
        particlespeedspread = 1,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.16,
        sizemod            = 1.0,
        texture            = [[YELLOWBLAST2]],
      },
    },
    g_smokewave4 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.92,
        colormap           = [[1 0.3 0.2 0.01 	1 0.5 0.2 0.01	 0.1 0.1 0.1 0.01 	0.1 0.1 0.1 0.01 	0 0 0 0.01]],
        directional        = false,
        emitrot            = 80,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 35,
        particlelife       = 38,
        particlelifespread = 15,
        particlesize       = 13,
        particlesizespread = 1,
        particlespeed      = 20,
        particlespeedspread = 1,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.16,
        sizemod            = 1.0,
        texture            = [[YELLOWBLAST3]],
      },
    },
    spikesofhell = {
      air                = true,
      class              = [[explspike]],
      count              = 30,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 1,
        alphadecay         = 0.05,
        color              = [[1.0, 0.7, 0.2]],
        dir                = [[-25 r50,-25 r50,-25 r50]],
        length             = 1,
        width              = 40,
      },
    },
    windsphere = {
      air                = true,
      class              = [[CSpherePartSpawner]],
      count              = 3,
      ground             = true,
      water              = true,
      properties = {
        alpha              = 0.22,
        color              = [[1.0, 0.8, 0.1]],
        expansionspeed     = [[10 r4]],
        ttl                = 27,
      },
    },
  },

}

