-- kbotrockettrail

return {
  ["kbotrockettrail"] = {
    usedefaultexplosions = false,
    exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      properties = {
        airdrag            = 0.97,
        colormap           = [[0.7 0.5 0.4 0.01 0.1 0.1 0.1 0.18 0.0 0.0 0.0 0.01]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 20,
        emitvector         = [[dir]],
        gravity            = [[0, 0, 0]],
        numparticles       = 2,
        particlelife       = 30,
        particlelifespread = 4.2,
        particlesize       = 3,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 2,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.65,
        sizemod            = 1.0,
        texture            = [[smoke]],
      },
    },
    groundflash = {
      air                = true,
      circlealpha        = 0,
      circlegrowth       = 0,
      flashalpha         = 0.40,
      flashsize          = 120,
      ground             = true,
      ttl                = 5,
      water              = true,
      color = {
        [1]  = 0.33000001311302,
        [2]  = 0.20000000298023,
        [3]  = 0.20000000298023,
      },
    },
    largeflash = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      water              = true,
      properties = {
        colormap           = [[1.0 0.3 0.2 0.01 0.4 0.2 0.1 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 0,
        fronttexture       = [[muzzlefront]],
        length             = -24,
        sidetexture        = [[muzzleside]],
        size               = -5,
        sizegrowth         = 0.75,
        ttl                = 1,
      },
    },
    trail_underwater = {
      class              = [[CSimpleParticleSystem]],
      count              = 2,
      ground             = false,
      underwater         = true,
      water              = false,
      unit               = true,
      properties = {
        airdrag            = 0.65,
        alwaysvisible      = false,
        colormap           = [[1 1 1 0.01   0.01 0.01 0.005 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[-1 r2 -1 r2 -1 r2]],
        gravity            = [[0, 0.1, 0]],
        numparticles       = [[3 r2]],
        particlelife       = [[40]],
        particlelifespread = 20,
        particlesize       = 1.8,
        particlesizespread = 1,
        particlespeed      = 0.6,
        particlespeedspread = 0.5,
        pos                = [[r10 -5, r10 -5, r10 -5]],
        sizegrowth         = 0,
        sizemod            = 0.99,
        texture            = [[bubble]],
      },
    },
	waterpop = {
      air                = false,
      class              = [[CBitmapMuzzleFlame]],
      count              = 2,
      ground             = false,
      water              = true,
      unit               = false,
      underwater         = true,
      properties = {
        colormap           = [[0.9 0.9 0.9 0.01 0.8 0.8 0.8 0.01 0 0 0 0.01]],
        dir                = [[dir]],
        frontoffset        = 1,
        fronttexture       = [[wake]],
        length             = 5,
        sidetexture        = [[wake]],
        size               = 3,
        sizegrowth         = 0.4,
        ttl                = 15,
      },
    },
  },

}

