return {
	pwn     = 'Award for dealing the most damage.',
	navy    = 'Award for successful ship usage.',
	air     = 'Award for exceptional play with airborne units.',
	nux     = 'Award for employing superweapons.',
	shell   = 'Award for effective use of defence.',
	fire    = 'Award for dealing fire damage.',
	emp     = 'Award for dealing EMP damage.',
	slow    = 'Award for applying slow damage.',
	disarm  = 'Award for disarming enemy units.',
	t3      = 'Award for experimental engineering.',
	cap     = 'Award for capturing enemy units.',
	share   = 'Award for sharing units to allies.',
	terra   = 'Award for excessive terraforming.',
	reclaim = 'Award for efficient usage of reclaim.',
	rezz    = 'Award for resurrecting wreckage.',
	vet     = 'Award for extremely efficient usage of a single unit.',
	ouch    = 'Award for receiving the most health damage.',
	kam     = 'Award for heroic usage of self-destructing units.',
	comm    = 'Award for using your commander like a boss.',
	mex     = 'Award for building metal extractors.',
	mexkill = 'Award for raiding enemy metal extractors.',
	rage    = 'Award for rage inducing.',
	head    = 'Award for eliminating enemy commanders.',
	dragon  = 'Award for eliminating Chicken Dragons.',
	heart   = 'Award for killing the Chicken Queen.',
	sweeper = 'Award for destroying Chicken Roosts.',
}
