return {
	pwn     = WG.Translate("interface", "awards_ta"),
	navy    = WG.Translate("interface", "awards_admiral"),
	air     = WG.Translate("interface", "awards_ace"),
	nux     = WG.Translate("interface", "awards_nuxbaron"),
	shell   = WG.Translate("interface", "awards_turtle"),
	fire    = WG.Translate("interface", "awards_firewiz"),
	emp     = WG.Translate("interface", "awards_empwiz"),
	slow    = WG.Translate("interface", "awards_slowwiz"),
	t3      = WG.Translate("interface", "awards_eng"),
	cap     = WG.Translate("interface", "awards_cap"),
	share   = WG.Translate("interface", "awards_sharebear"),
	terra   = WG.Translate("interface", "awards_tera"),
	reclaim = WG.Translate("interface", "awards_rec"),
	rezz    = WG.Translate("interface", "awards_res"),
	vet     = WG.Translate("interface", "awards_vet"),
	ouch    = WG.Translate("interface", "awards_punchbag"),
	kam     = WG.Translate("interface", "awards_kami"),
	comm    = WG.Translate("interface", "awards_com"),
	mex     = WG.Translate("interface", "awards_ecoman"),
	mexkill = WG.Translate("interface", "awards_raider"),
	rage    = WG.Translate("interface", "awards_rage"),
	head    = WG.Translate("interface", "awards_comsniper"),
	dragon  = WG.Translate("interface", "awards_dragonslayer"),
	heart   = WG.Translate("interface", "awards_queenslayer"),
	sweeper = WG.Translate("interface", "awards_pestcontrol"),
}
