return {
	pwn     = 'Dealing the most damage.',
	navy    = 'Successful ship usage.',
	air     = 'Exceptional play with airborne units.',
	nux     = 'Employing superweapons.',
	shell   = 'Effective use of defence.',
	fire    = 'Dealing fire damage.',
	emp     = 'Dealing EMP damage.',
	slow    = 'Applying slow damage.',
	disarm  = 'Disarming enemy units.',
	t3      = 'Experimental engineering.',
	cap     = 'Capturing enemy units.',
	share   = 'Sharing units to allies.',
	terra   = 'Excessive terraforming.',
	reclaim = 'Efficient usage of reclaim.',
	rezz    = 'Resurrecting wreckage.',
	vet     = 'Extremely efficient usage of a single unit.',
	ouch    = 'Receiving the most health damage.',
	kam     = 'Heroic usage of self-destructing units.',
	comm    = 'Using your commander like a boss.',
	mex     = 'Building metal extractors.',
	mexkill = 'Raiding enemy metal extractors.',
	rage    = 'Rage inducing.',
	head    = 'Eliminating enemy commanders.',
	dragon  = 'Eliminating Chicken Dragons.',
	heart   = 'Killing the Chicken Queen.',
	sweeper = 'Destroying Chicken Roosts.',
}
