return {
	pwn     = 'Dealt the most damage',
	navy    = 'Dealt exceptional damage with ships',
	air     = 'Dealt exceptional damage with flying units',
	nux     = 'Dealt exceptional damage with stratigic nukes or superweapons',
	shell   = 'Dealt exceptional damage with static defenses',
	fire    = 'Dealt exceptional fire damage',
	emp     = 'Dealt exceptional EMP damage',
	slow    = 'Dealt exceptional slow damage',
	disarm  = 'Dealt exceptional disarm damage',
	t3      = 'Dealt exceptional damage with striders',
	cap     = 'Captured many enemy units',
	share   = 'Shared many units to allies',
	terra   = 'Built the most terraform',
	reclaim = 'Reclaimed the most metal',
	rezz    = 'Resurrected the most wreckage',
	vet     = 'Highest veterancy unit (damage dealt per cost)',
	ouch    = 'Lost the most health',
	kam     = 'Dealt exceptional damage with self-destructing units',
	comm    = 'Dealt exceptional damage with their commander',
	mex     = 'Built many metal extractors',
	mexkill = 'Killed many enemy metal extractors',
	rage    = 'Rage inducing',
	head    = 'Killed the most enemy commanders',
	dragon  = 'Killed the most Chicken Dragons',
	heart   = 'Killed the Chicken Queen',
	sweeper = 'Destroyed the most Chicken Roosts',
}
