local SUC = Spring.Utilities.CMD

local stateCommands = {
	[CMD.ONOFF] = true,
	[SUC.WANT_ONOFF] = true,
	[CMD.FIRE_STATE] = true,
	[CMD.MOVE_STATE] = true,
	[CMD.REPEAT] = true,
	[CMD.CLOAK] = true,
	[CMD.STOCKPILE] = true,
	[CMD.TRAJECTORY] = true,
	[CMD.IDLEMODE] = true,
	[SUC.GLOBAL_BUILD] = true,
	[SUC.FACTORY_GUARD] = true,
	[SUC.STEALTH] = true,
	[SUC.CLOAK_SHIELD] = true,
	[SUC.UNIT_FLOAT_STATE] = true,
	[SUC.PRIORITY] = true,
	[SUC.MISC_PRIORITY] = true,
	[SUC.RETREAT] = true,
	[SUC.UNIT_BOMBER_DIVE_STATE] = true,
	[SUC.AP_FLY_STATE] = true,
	[SUC.AP_AUTOREPAIRLEVEL] = true,
	[SUC.UNIT_SET_TARGET] = true,
	[SUC.UNIT_CANCEL_TARGET] = true,
	[SUC.UNIT_SET_TARGET_CIRCLE] = true,
	[SUC.ABANDON_PW] = true,
	[SUC.RECALL_DRONES] = true,
	[SUC.UNIT_KILL_SUBORDINATES] = true,
	[SUC.GOO_GATHER] = true,
	[SUC.PUSH_PULL] = true,
	[SUC.UNIT_AI] = true,
	[SUC.WANT_CLOAK] = true,
	[SUC.DONT_FIRE_AT_RADAR] = true,
	[SUC.AIR_STRAFE] = true,
	[SUC.PREVENT_OVERKILL] = true,
	[SUC.PREVENT_BAIT] = true,
	[SUC.FIRE_AT_SHIELD] = true,
	[SUC.TOGGLE_DRONES] = true,
	[SUC.AUTO_CALL_TRANSPORT] = true,
	[SUC.SELECTION_RANK] = true,
}

return stateCommands
