return "commweapon_chickenspores",{
    name                    = [[Spores]],
    areaOfEffect            = 24,
    avoidFriendly           = false,
    burst                   = 8,
    burstrate               = 0.1,
    collideFriendly         = false,
    craterBoost             = 0,
    craterMult              = 0,
    
    customParams            = {
		is_unit_weapon = 1,
      light_radius = 0,
    },

    damage                  = {
      default = 85,
      planes  = 85*2,
    },

    dance                   = 60,
    explosionGenerator      = [[custom:NONE]],
    fireStarter             = 0,
    flightTime              = 5,
    groundbounce            = 1,
    heightmod               = 0.5,
    impactOnly              = true,
    impulseBoost            = 0,
    impulseFactor           = 0.4,
    interceptedByShieldType = 2,
    model                   = [[chickeneggpink.s3o]],
    noSelfDamage            = true,
    range                   = 300,
    reloadtime              = 4,
    smokeTrail              = true,
    startVelocity           = 100,
    texture1                = [[]],
    texture2                = [[sporetrail]],
    tolerance               = 10000,
    tracks                  = true,
    turnRate                = 24000,
    turret                  = true,
    waterweapon             = true,
    weaponAcceleration      = 100,
    weaponType              = [[MissileLauncher]],
    weaponVelocity          = 500,
    wobble                  = 32000,
  }