unitDef = {
  unitname              = [[arm_starter]],
  name                  = [[Starter]],
  description           = [[Starter Unit]],
  acceleration          = 0.18,
  activateWhenBuilt     = false,
  amphibious            = [[1]],
  autoHeal              = 5,
  bmcode                = [[1]],
  brakeRate             = 0.375,
  buildCostEnergy       = 3000,
  buildCostMetal        = 3000,
  buildDistance         = 120,
  buildPic              = [[armcom.png]],
  buildTime             = 3000,
  canMove               = true,
  canstop               = [[1]],
  category              = [[UNARMED FIREPROOF LAND]],
  commander             = true,
  corpse                = [[DEAD]],

  customParams          = {
    fireproof = [[1]],
  },

  defaultmissiontype    = [[Standby]],
  energyUse             = 0,
  explodeAs             = [[EMPDEATH]],
  footprintX            = 2,
  footprintZ            = 2,
  hideDamage            = true,
  iconType              = [[armcommander]],
  idleAutoHeal          = 5,
  idleTime              = 1800,
  immunetoparalyzer     = [[1]],
  maneuverleashlength   = [[640]],
  mass                  = 1250,
  maxDamage             = 2000,
  maxSlope              = 36,
  maxVelocity           = 1.45,
  maxWaterDepth         = 5000,
  minCloakDistance      = 100,
  movementClass         = [[AKBOT2]],
  noChaseCategory       = [[TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK]],
  norestrict            = [[1]],
  objectName            = [[ARMCOM]],
  radarDistance         = 700,
  reclaimable           = false,
  seismicSignature      = 4,
  selfDestructAs        = [[EMPDEATH]],
  selfDestructCountdown = 10,

  sfxtypes              = {

    explosiongenerators = {
      [[custom:COMGATE]],
    },

  },

  showPlayerName        = true,
  side                  = [[ARM]],
  sightDistance         = 500,
  smoothAnim            = true,
  sonarDistance         = 300,
  steeringmode          = [[2]],
  TEDClass              = [[COMMANDER]],
  terraformSpeed        = 600,
  turnRate              = 1148,
  upright               = true,
  workerTime            = 12,

  weaponDefs            = {

    invisible_laser = {
      name                    = [[lazer]],
      areaOfEffect            = 10,
      beamWeapon              = true,
      collideFriendly         = false,
      craterBoost             = 0,
      craterMult              = 0,

      damage                  = {
        default = 40,
      },

      duration                = 0.0025,
      energypershot           = 0,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      intensity               = 0,
      interceptedByShieldType = 0,
      lineOfSight             = true,
      noradar                 = [[1]],
      noSelfDamage            = true,
      range                   = 150,
      reloadtime              = 1.5,
      renderType              = 7,
      rgbColor                = [[1 0 0]],
      targetMoveError         = 0.2,
      thickness               = 0,
      turret                  = true,
      weaponType              = [[LightningCannon]],
      weaponVelocity          = 450,
    },


    lightning       = {
      name                    = [[EMP]],
      areaOfEffect            = 140,
      beamWeapon              = true,
      collideFriendly         = false,
      color                   = 128,
      color2                  = 130,
      craterBoost             = 0,
      craterMult              = 0,

      damage                  = {
        default        = 400,
        commanders     = 40,
        empresistant75 = 100,
        empresistant99 = 400,
      },

      duration                = 8,
      energypershot           = 3,
      explosionGenerator      = [[custom:ELECTRIC_EXPLOSION]],
      fireStarter             = 0,
      impulseBoost            = 0,
      impulseFactor           = 0,
      interceptedByShieldType = 0,
      lineOfSight             = true,
      noSelfDamage            = true,
      paralyzer               = true,
      paralyzeTime            = 3,
      range                   = 150,
      reloadtime              = 2,
      renderType              = 7,
      soundHit                = [[OTAunit/Lashit]],
      soundStart              = [[OTAunit/LGHTHVY1]],
      soundTrigger            = true,
      targetMoveError         = 0.2,
      turret                  = true,
      weaponType              = [[LightningCannon]],
      weaponVelocity          = 450,
    },

  },


  featureDefs           = {

    DEAD      = {
      description      = [[Wreckage - Starter]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 2000,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[20]],
      hitdensity       = [[100]],
      metal            = 1200,
      object           = [[ARMCOM_DEAD]],
      reclaimable      = true,
      reclaimTime      = 1200,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2     = {
      description      = [[Debris - Starter]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 2000,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      hitdensity       = [[100]],
      metal            = 1200,
      object           = [[debris2x2a.s3o]],
      reclaimable      = true,
      reclaimTime      = 1200,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP      = {
      description      = [[Debris - Starter]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 2000,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      hitdensity       = [[100]],
      metal            = 600,
      object           = [[debris2x2a.s3o]],
      reclaimable      = true,
      reclaimTime      = 600,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    RIOT_HEAP = {
      description      = [[Commander Debris]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 20000,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 300,
      object           = [[debris2x2a.s3o]],
      reclaimable      = true,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ arm_starter = unitDef })
