unitDef = {
  unitname            = [[armamph]],
  name                = [[Pelican]],
  description         = [[Torpedo Amph]],
  acceleration        = 0.12,
  bmcode              = [[1]],
  brakeRate           = 0.188,
  buildCostEnergy     = 280,
  buildCostMetal      = 280,
  builder             = false,
  buildPic            = [[ARMAMPH.png]],
  buildTime           = 280,
  canAttack           = true,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canstop             = [[1]],
  category            = [[LAND]],
  corpse              = [[DEAD]],

  customParams        = {
    description_fr = [[Amphibien Torpilleur]],
    description_pl = [[Amfibia z torpedami]],
    helptext       = [[The Pelican is a multipurpose unit that can swim underwater and run on land. Capable of defending itself on land and submerged, it is armed with torpedoes and lasers.]],
    helptext_fr    = [[Le Pelican est une unit? multir?le qui peu nager sous l'eau ou courrir sur terre. Il est capable de se d?fendre dans ces deux ?l?ments avec des torpilles ou  ses canons laser.]],
    helptext_pl    = [[Pelican jest wielozadaniow? jednostk? mog?c? chodzi? po l?dzie i p?ywa? pod wod?. Na l?dzie atakuje przy pomocy lasera, pod wod? przy pomocy wyrzutni torped.]],
  },

  defaultmissiontype  = [[Standby]],
  explodeAs           = [[BIG_UNITEX]],
  floater             = false,
  footprintX          = 3,
  footprintZ          = 3,
  iconType            = [[hoverraider]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  maneuverleashlength = [[640]],
  mass                = 140,
  maxDamage           = 750,
  maxSlope            = 36,
  maxVelocity         = 2.4,
  maxWaterDepth       = 5000,
  minCloakDistance    = 75,
  movementClass       = [[AKBOT2]],
  noAutoFire          = false,
  noChaseCategory     = [[TERRAFORM SATELLITE]],
  objectName          = [[ARMAMPH]],
  seismicSignature    = 4,
  selfDestructAs      = [[BIG_UNITEX]],
  side                = [[ARM]],
  sightDistance       = 660,
  smoothAnim          = true,
  sonarDistance       = 300,
  stealth             = true,
  steeringmode        = [[2]],
  TEDClass            = [[KBOT]],
  turninplace         = 0,
  turnRate            = 960,
  upright             = true,
  workerTime          = 0,

  weapons             = {

    {
      def                = [[LASER]],
      onlyTargetCategory = [[FIXEDWING LAND SINK SHIP SWIM FLOAT GUNSHIP HOVER]],
    },


    {
      def                = [[TORPEDO]],
      badTargetCategory  = [[FIXEDWING]],
      onlyTargetCategory = [[SWIM FIXEDWING LAND SUB SINK FLOAT SHIP GUNSHIP]],
    },

  },


  weaponDefs          = {

    LASER   = {
      name                    = [[Laser]],
      areaOfEffect            = 8,
      beamlaser               = 1,
      beamTime                = 0.12,
      coreThickness           = 0.5,
      craterBoost             = 0,
      craterMult              = 0,

      damage                  = {
        default = 11,
        planes  = 11,
        subs    = 0.55,
      },

      endsmoke                = [[0]],
      explosionGenerator      = [[custom:FLASH1green]],
      impactOnly              = true,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 1,
      largeBeamLaser          = true,
      laserFlareSize          = 3.29,
      lineOfSight             = true,
      minIntensity            = 1,
      noSelfDamage            = true,
      range                   = 275,
      reloadtime              = 0.1,
      renderType              = 0,
      rgbColor                = [[0 1 0]],
      soundHit                = [[OTAunit/BURN02]],
      soundStart              = [[OTAunit/BUILD2]],
      startsmoke              = [[0]],
      sweepfire               = false,
      texture1                = [[largelaser]],
      texture2                = [[flare]],
      texture3                = [[flare]],
      texture4                = [[smallflare]],
      thickness               = 3.29061164527205,
      tolerance               = 10000,
      turret                  = true,
      weaponType              = [[BeamLaser]],
      weaponVelocity          = 500,
    },


    TORPEDO = {
      name                    = [[Torpedo]],
      areaOfEffect            = 16,
      avoidFriendly           = false,
      burnblow                = true,
      collideFriendly         = false,
      craterBoost             = 0,
      craterMult              = 0,

      damage                  = {
        default = 125,
        subs    = 125,
      },

      explosionGenerator      = [[custom:TORPEDO_HIT]],
      guidance                = true,
      impactOnly              = true,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 1,
      lineOfSight             = true,
      model                   = [[torpedo]],
      noSelfDamage            = true,
      propeller               = [[1]],
      range                   = 400,
      reloadtime              = 4,
      renderType              = 1,
      selfprop                = true,
      soundHit                = [[OTAunit/XPLODEP1]],
      soundStart              = [[OTAunit/TORPEDO1]],
      startVelocity           = 100,
      tolerance               = 32000,
      tracks                  = true,
      turnRate                = 16000,
      turret                  = false,
      waterWeapon             = true,
      weaponAcceleration      = 50,
      weaponTimer             = 4,
      weaponType              = [[TorpedoLauncher]],
      weaponVelocity          = 200,
    },

  },


  featureDefs         = {

    DEAD  = {
      description      = [[Wreckage - Pelican]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 750,
      energy           = 0,
      featureDead      = [[DEAD2]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[20]],
      hitdensity       = [[100]],
      metal            = 112,
      object           = [[ARMAMPH_DEAD]],
      reclaimable      = true,
      reclaimTime      = 112,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Pelican]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 750,
      energy           = 0,
      featureDead      = [[HEAP]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 112,
      object           = [[debris3x3b.s3o]],
      reclaimable      = true,
      reclaimTime      = 112,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Pelican]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 750,
      energy           = 0,
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 56,
      object           = [[debris3x3b.s3o]],
      reclaimable      = true,
      reclaimTime      = 56,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ armamph = unitDef })
