unitDef = {
  unitname                      = [[armalab]],
  name                          = [[Tactical Walker Factory]],
  description                   = [[Produces Specialized Walkers, Builds at 6 m/s]],
  acceleration                  = 0,
  bmcode                        = [[0]],
  brakeRate                     = 0,
  buildCostEnergy               = 550,
  buildCostMetal                = 550,
  builder                       = true,
  buildingGroundDecalDecaySpeed = 30,
  buildingGroundDecalSizeX      = 7,
  buildingGroundDecalSizeY      = 7,
  buildingGroundDecalType       = [[armalab_aoplane.dds]],

  buildoptions                  = {
    [[arm_spider]],
    [[armfast]],
    [[arm_venom]],
    [[armsptk]],
    [[armzeus]],
    [[armsnipe]],
    [[armcrabe]],
    [[armscab]],
    [[armaak]],
    [[armspy]],
    [[armaser]],
  },

  buildPic                      = [[ARMALAB.png]],
  buildTime                     = 550,
  canMove                       = true,
  canPatrol                     = true,
  canstop                       = [[1]],
  category                      = [[SINK UNARMED]],
  collisionVolumeTest           = 1,
  corpse                        = [[DEAD]],

  customParams                  = {
    description_es = [[Fábrica táctica de caminantes]],
    description_fi = [[Taktinen robottitehdas. Rakentaa erikoistuneita robotteja 6m/s nopeudella]],
    description_it = [[Fabbrica tattica di camminatori]],
    helptext       = [[The choice of the discerning commander, the Tactical Walker Factory is a strictly cloak-and-dagger operation. Paralysers, cloaking fields, all-terrain spiders and jammers abound in this fine collection of deceptively deadly special operations units. Key Units: Zeus, Venom, Recluse, Eraser, Sharpshooter, Crabe]],
    helptext_es    = [[La selcción del comandante perspicaz, la Fábrica táctica de caminantes es estrictamente operaciones de intriga. Paralizadores, campos de ocultamiento, ara?as all-terrain, y unidades para interferir con radar abundan en esta fina colección de unidades enga?osamente letales.Unidades llave: Zeus, Venom, Recluse, Eraser, Sharpshooter, Crabe.]],
    helptext_fi    = [[Tuottaa pitk?lti erikoistuneita tai jalkav?kirobotteja raskaampia yksik?it?. Esimerkiksi EMP, n?kym?tt?myys ja maastokelpoisuus ovat joidenkin t?m?n tehtaan tuotoksien erikoisuuksia.]],
    helptext_it    = [[La scelta del comandante perspicace, la fabbrica tattica di camminatori é strettamente per operazioni cappa e spada. Paralizzatori, campi di occultamento, ragni all-terrain, ed unitá per interferire con radar abbondano in questa fine collezione d'unitá ingannevolmente micidiali. Unitá chiave: Zues, Venom, Recluse, Eraser, Sharpshooter, Crabe.]],
    sortName       = [[5]],
  },

  energyMake                    = 0.3,
  energyUse                     = 0,
  explodeAs                     = [[LARGE_BUILDINGEX]],
  footprintX                    = 6,
  footprintZ                    = 6,
  iconType                      = [[facwalker]],
  idleAutoHeal                  = 5,
  idleTime                      = 1800,
  mass                          = 275,
  maxDamage                     = 4000,
  maxSlope                      = 15,
  maxVelocity                   = 0,
  maxWaterDepth                 = 0,
  metalMake                     = 0.3,
  minCloakDistance              = 150,
  noAutoFire                    = false,
  objectName                    = [[ARMALAB]],
  seismicSignature              = 4,
  selfDestructAs                = [[LARGE_BUILDINGEX]],
  showNanoSpray                 = false,
  side                          = [[ARM]],
  sightDistance                 = 273,
  smoothAnim                    = true,
  TEDClass                      = [[PLANT]],
  turnRate                      = 0,
  useBuildingGroundDecal        = true,
  workerTime                    = 6,
  yardMap                       = [[occccooccccooccccooccccooccccoocccco]],

  featureDefs                   = {

    DEAD  = {
      description      = [[Wreckage - Tactical Walker Factory]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 4000,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 5,
      footprintZ       = 6,
      height           = [[20]],
      hitdensity       = [[100]],
      metal            = 220,
      object           = [[ARMALAB_DEAD]],
      reclaimable      = true,
      reclaimTime      = 220,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Tactical Walker Factory]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 4000,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 5,
      footprintZ       = 5,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 220,
      object           = [[debris4x4a.s3o]],
      reclaimable      = true,
      reclaimTime      = 220,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Tactical Walker Factory]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 4000,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 5,
      footprintZ       = 5,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 110,
      object           = [[debris4x4a.s3o]],
      reclaimable      = true,
      reclaimTime      = 110,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ armalab = unitDef })
