unitDef = {
  unitname            = [[armbull]],
  name                = [[Bulldog]],
  description         = [[Assault Tank]],
  acceleration        = 0.03,
  bmcode              = [[1]],
  brakeRate           = 0.066,
  buildCostEnergy     = 800,
  buildCostMetal      = 800,
  builder             = false,
  buildPic            = [[ARMBULL.png]],
  buildTime           = 800,
  canAttack           = true,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canstop             = [[1]],
  category            = [[LAND]],
  corpse              = [[DEAD]],

  customParams        = {
    description_bp = [[Tanque de assalto]],
    description_fr = [[Tank d'Assaut]],
    helptext       = [[The Bulldog is Nova's heaviest tank. It's very heavily armored, however the low rate of fire of its plasma cannon makes it vulnerable to swarms of small units if not protected by units with more firepower.]],
    helptext_bp    = [[Bulldog é o tanque mais pesado de Nova. ? muito resistente, mas sua baixa velocidade de disparo o torna vulnerável a grupos de unidades pequenas se n?o for protegido por unidades com maior poder de fogo.]],
    helptext_fr    = [[Le Bulldog est le plus lourd des tank Nova. Tr?s lourdement blind? mais aussi tr?s lent, il est cependant incapable de se d?fendre seul contre des hordes de petits adversaire trop rapides pour son canon ? plasma lourd.]],
  },

  defaultmissiontype  = [[Standby]],
  explodeAs           = [[BIG_UNITEX]],
  footprintX          = 4,
  footprintZ          = 4,
  iconType            = [[tankassault]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  leaveTracks         = true,
  maneuverleashlength = [[640]],
  mass                = 400,
  maxDamage           = 5728,
  maxSlope            = 18,
  maxVelocity         = 2.3,
  maxWaterDepth       = 22,
  minCloakDistance    = 75,
  movementClass       = [[TANK4]],
  noAutoFire          = false,
  noChaseCategory     = [[TERRAFORM FIXEDWING SATELLITE SUB]],
  objectName          = [[ARMBULL]],
  seismicSignature    = 4,
  selfDestructAs      = [[BIG_UNITEX]],
  side                = [[ARM]],
  sightDistance       = 506,
  smoothAnim          = true,
  steeringmode        = [[1]],
  TEDClass            = [[TANK]],
  trackOffset         = 8,
  trackStrength       = 10,
  trackStretch        = 1,
  trackType           = [[StdTank]],
  trackWidth          = 40,
  turninplace         = 0,
  turnRate            = 450,
  workerTime          = 0,

  weapons             = {

    {
      def                = [[PLASMA]],
      badTargetCategory  = [[FIXEDWING]],
      onlyTargetCategory = [[FIXEDWING LAND SINK SHIP SWIM FLOAT GUNSHIP HOVER]],
    },

  },


  weaponDefs          = {

    PLASMA = {
      name                    = [[Medium Plasma Cannon]],
      areaOfEffect            = 16,
      burst                   = 2,
      burstRate               = 0.1,
      craterBoost             = 0,
      craterMult              = 0,

      damage                  = {
        default = 166,
        planes  = 166,
        subs    = 9.25,
      },

      explosionGenerator      = [[custom:DEFAULT]],
      impactOnly              = true,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 1,
      noSelfDamage            = true,
      range                   = 360,
      reloadtime              = 2,
      renderType              = 4,
      soundHit                = [[OTAunit/XPLOMED2]],
      soundStart              = [[OTAunit/CANNON3]],
      startsmoke              = [[1]],
      turret                  = true,
      weaponType              = [[Cannon]],
      weaponVelocity          = 255,
    },

  },


  featureDefs         = {

    DEAD  = {
      description      = [[Wreckage - Bulldog]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 5728,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[20]],
      hitdensity       = [[100]],
      metal            = 320,
      object           = [[ARMBULL_DEAD]],
      reclaimable      = true,
      reclaimTime      = 320,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Bulldog]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 5728,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 320,
      object           = [[debris3x3c.s3o]],
      reclaimable      = true,
      reclaimTime      = 320,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Bulldog]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 5728,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 160,
      object           = [[debris3x3c.s3o]],
      reclaimable      = true,
      reclaimTime      = 160,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ armbull = unitDef })
