unitDef = {
  unitname            = [[armcs]],
  name                = [[Coral]],
  description         = [[Construction Ship, Builds at 12 m/s]],
  acceleration        = 0.05103,
  bmcode              = [[1]],
  brakeRate           = 0.05,
  buildCostEnergy     = 240,
  buildCostMetal      = 240,
  buildDistance       = 300,
  builder             = true,

  buildoptions        = {
  },

  buildPic            = [[ARMCS.png]],
  buildTime           = 240,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canreclamate        = [[1]],
  canstop             = [[1]],
  category            = [[SHIP UNARMED]],
  corpse              = [[DEAD]],

  customParams        = {
    description_bp = [[Construction Ship, Builds at 12 m/s]],
    description_fr = [[Navire de Construction, Construit ? 12 m/s]],
    helptext       = [[Although expensive, the Construction Ship boasts extremely high nano power, combined with tough armor and good speed.]],
    helptext_bp    = [[Although expensive, the Construction Ship boasts extremely high nano power, combined with tough armor and good speed.]],
    helptext_fr    = [[Assez cher, le Shipcon ? cependant une puissance de construtcion exceptionnelle, ainsi qu'un blindage effectif.]],
  },

  defaultmissiontype  = [[Standby]],
  energyMake          = 0.3,
  energyUse           = 0,
  explodeAs           = [[SMALL_UNITEX]],
  floater             = true,
  footprintX          = 3,
  footprintZ          = 3,
  iconType            = [[builder]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  maneuverleashlength = [[640]],
  mass                = 120,
  maxDamage           = 1105,
  maxVelocity         = 2.7,
  metalMake           = 0.3,
  minCloakDistance    = 75,
  minWaterDepth       = 5,
  movementClass       = [[BOAT3]],
  noAutoFire          = false,
  noChaseCategory     = [[TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK]],
  objectName          = [[ARMCS]],
  seismicSignature    = 4,
  selfDestructAs      = [[SMALL_UNITEX]],
  showNanoSpray       = false,
  side                = [[ARM]],
  sightDistance       = 325,
  smoothAnim          = true,
  steeringmode        = [[1]],
  TEDClass            = [[SHIP]],
  terraformSpeed      = 600,
  turninplace         = 0,
  turnRate            = 448,
  workerTime          = 12,

  featureDefs         = {

    DEAD  = {
      description      = [[Wreckage - Coral]],
      blocking         = false,
      category         = [[corpses]],
      damage           = 1105,
      energy           = 0,
      featureDead      = [[DEAD2]],
      footprintX       = 5,
      footprintZ       = 5,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 96,
      object           = [[ARMCS_DEAD]],
      reclaimable      = true,
      reclaimTime      = 96,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Coral]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 1105,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 4,
      footprintZ       = 4,
      hitdensity       = [[100]],
      metal            = 96,
      object           = [[debris4x4c.s3o]],
      reclaimable      = true,
      reclaimTime      = 96,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Coral]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 1105,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 4,
      footprintZ       = 4,
      hitdensity       = [[100]],
      metal            = 48,
      object           = [[debris4x4c.s3o]],
      reclaimable      = true,
      reclaimTime      = 48,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ armcs = unitDef })
