unitDef = {
  unitname            = [[armcybr]],
  name                = [[Licho]],
  description         = [[Plasma Strike Bomber (Anti-Heavy)]],
  amphibious          = true,
  --autoheal			  = 25,
  buildCostEnergy     = 1500,
  buildCostMetal      = 1500,
  builder             = false,
  buildPic            = [[ARMCYBR.png]],
  buildTime           = 1500,
  canAttack           = true,
  canFly              = true,
  canGuard            = true,
  canLoopbackAttack   = false,
  canMove             = true,
  canPatrol           = true,
  canSubmerge         = false,
  category            = [[FIXEDWING]],
  collide             = false,
  collisionVolumeOffsets = [[-2 0 0]],
  collisionVolumeScales  = [[32 12 40]],
  collisionVolumeTest    = 1,
  collisionVolumeType    = [[box]],
  corpse              = [[DEAD]],
  crashDrag           = 0.02,
  cruiseAlt           = 250,

  customParams        = {
    helptext       = [[The Licho fires a lethal plasma bomb at a single target. It is sturdy enough to penetrate moderate AA and escape to repair, but should not be used recklessly - it's too expensive for that.]],
    --description_bp = [[Bombardeiro de implos?o]],
    --description_de = [[Implosion Bomber]],
    --description_fr = [[Bombardier r Implosion]],
    --description_pl = [[Bombowiec Implozyjny]],
    --helptext_bp    = [[]],
    --helptext_de    = [[Licho ist ein mächtiger Bomber, der alles in Schutt und Asche legt. Seine Schlagkraft und Ausdauer ist riesig, doch muss er nach jedem Angriff Munition nachladen, was ihn eher für Angriffe auf einzelne Ziele prädestiniert.]],
    --helptext_fr    = [[Le Licho est tout simplement la mort venue du ciel. Ce bombardier lourdement blindé et relativement lent transporte une tete nucléaire tactique r implosion. Capable de faire des ravages dans les lignes ennemies, ou de détruire des structures lourdement blindées. Tout simplement mortel utilisé en petites escadres.]],
    --helptext_pl    = [[Licho spuszcza pojedyncz�?niszczycielsk�?bomb�?o dużej sile i obszarze rażenia, która może rozrzuci�?mniejsze jednostki wokó�? Jest też wystarczaj�?o wytrzymały, by lata�?wśród umiarkowanej ilości obrony przeciwlotniczej. Jest jednak bardzo drogi, co nie pozwala na lekkomyślne używanie.]],
    modelradius    = [[10]],
  },

  explodeAs           = [[GUNSHIPEX]],
  floater             = true,
  footprintX          = 3,
  footprintZ          = 3,
  iconType            = [[bombernuke]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  maneuverleashlength = [[1280]],
  mass                = 460,
  maxAcc              = 0.75,
  maxDamage           = 2200,
  maxFuel             = 1000000,
  maxVelocity         = 9,
  minCloakDistance    = 75,
  mygravity           = 1,
  noAutoFire          = false,
  noChaseCategory     = [[TERRAFORM FIXEDWING SATELLITE GUNSHIP SUB]],
  objectName          = [[ARMCYBR]],
  --refuelTime		  = 16,
  script			  = [[armcybr.lua]],
  seismicSignature    = 0,
  selfDestructAs      = [[GUNSHIPEX]],
  side                = [[ARM]],
  sightDistance       = 660,
  smoothAnim          = true,
  workerTime          = 0,

  weapons             = {

    {
      def                = [[ARM_PIDR]],
	  badTargetCategory	 = [[GUNSHIP FIXEDWING]],
      onlyTargetCategory = [[SWIM LAND SINK TURRET FLOAT SHIP HOVER GUNSHIP FIXEDWING]],
    },

  },


  weaponDefs          = {

    ARM_PIDR = {
      name                    = [[Plasma Bomb]],
      areaOfEffect            = 48,
      avoidFeature            = false,
      avoidFriendly           = false,
	  burnblow                = true,
	  cegTag                  = [[raventrail]],
      collideFriendly         = false,
   
      craterBoost             = 1,
      craterMult              = 2,

      damage                  = {
        default = 2500,
        planes  = 2500,
        subs    = 125,
      },

      edgeEffectiveness       = 0.5,
      explosionGenerator      = [[custom:greencannonimpact]],
      fireStarter             = 100,
      flightTime              = 4,
      impulseBoost            = 0,
      impulseFactor           = 0,
      interceptedByShieldType = 2,
      model                   = [[wep_m_deathblow.s3o]],
      pitchtolerance          = [[16000]],
      range                   = 500,
      reloadtime              = 8,
      renderType              = 1,
      shakeduration           = [[2]],
      shakemagnitude          = [[18]],
      smokedelay              = [[0.2]],
      smokeTrail              = false,
      soundHit                = [[weapon/laser/heavy_laser6]],
      soundStart              = [[weapon/missile/liche_fire]],
      startsmoke              = [[1]],
      startVelocity           = 300,
      tolerance               = 16000,
      tracks                  = false,
      turnRate                = 30000,
	  weaponAcceleration      = 200,
      weaponTimer             = 6,
      weaponType              = [[MissileLauncher]],
      weaponVelocity          = 400,
    },

  },


  featureDefs         = {

    DEAD  = {
      description      = [[Wreckage - Licho]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 2200,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[40]],
      hitdensity       = [[100]],
      metal            = 600,
      object           = [[licho_d.s3o]],
      reclaimable      = true,
      reclaimTime      = 600,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

    HEAP  = {
      description      = [[Debris - Licho]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 2200,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 300,
      object           = [[debris3x3b.s3o]],
      reclaimable      = true,
      reclaimTime      = 300,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ armcybr = unitDef })
