unitDef = {
  unitname            = [[armdfly]],
  name                = [[Dragonfly]],
  description         = [[Stealthy Armed Transport]],
  acceleration        = 0.2,
  amphibious          = true,
  bankscale           = [[1]],
  bmcode              = [[1]],
  brakeRate           = 6.25,
  buildCostEnergy     = 500,
  buildCostMetal      = 500,
  builder             = false,
  buildPic            = [[ARMDFLY.png]],
  buildTime           = 500,
  canAttack           = true,
  canFly              = true,
  canGuard            = true,
  canload             = [[1]],
  canMove             = true,
  canPatrol           = true,
  canstop             = [[1]],
  canSubmerge         = false,
  category            = [[GUNSHIP]],
  collide             = false,
  corpse              = [[HEAP]],
  cruiseAlt           = 250,

  customParams        = {
    description_bp = [[Transporte armado invisível a radar]],
    description_fr = [[Transport Armé Furtif]],
    helptext       = [[Not only can the Dragonfly haul any land unit in the game, it is also armed with a paralyzer cannon to support its airdrops. If intercepted midflight, it will eject its cargo, which falls to the ground - potentially squashing anything underneath.]],
    helptext_bp    = [[Dragonfly é capaz de carregar qualquer unidade terrestre no jogo e é armado com um canh?o de PEM para auxiliar a aterrisagem em território inimigo. Se for interceptado durante o voo ejetará sua carga que caíra no ch?o, potencialmente danificando aquilo sobre o que cair.]],
    helptext_fr    = [[Le Dragonfly est un transporteur lourd, indétectable au radar et armé de puissants canons EMP, permettant de se protéger d'attaques aériennes ou de couvrir sa zone d'atterrissage.]],
  },

  defaultmissiontype  = [[VTOL_standby]],
  explodeAs           = [[GUNSHIPEX]],
  floater             = true,
  footprintX          = 4,
  footprintZ          = 4,
  hoverAttack         = true,
  iconType            = [[airtransport]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  maneuverleashlength = [[1280]],
  mass                = 250,
  maxDamage           = 1100,
  maxVelocity         = 8,
  minCloakDistance    = 75,
  noAutoFire          = false,
  noChaseCategory     = [[TERRAFORM FIXEDWING SATELLITE GUNSHIP SUB]],
  objectName          = [[ARMDFLY]],
  radarDistanceJam    = 75,
  releaseHeld         = true,
  scale               = [[1]],
  seismicSignature    = 0,
  selfDestructAs      = [[GUNSHIPEX]],
  side                = [[ARM]],
  sightDistance       = 572,
  smoothAnim          = true,
  steeringmode        = [[1]],
  TEDClass            = [[VTOL]],
  transportCapacity   = 1,
  transportSize       = 25,
  turnInPlace         = 0,
  turnRate            = 420,
  verticalSpeed       = 30,
  workerTime          = 0,

  weapons             = {

    {
      def                = [[ARMDFLY_PARALYZER]],
      onlyTargetCategory = [[SWIM LAND SINK FLOAT SHIP HOVER FIXEDWING GUNSHIP]],
    },

  },


  weaponDefs          = {

    ARMDFLY_PARALYZER = {
      name                    = [[Electro-Stunner]],
      areaOfEffect            = 32,
      collideFriendly         = false,
      craterBoost             = 0,
      craterMult              = 0,

      damage                  = {
        default        = 3250,
        commanders     = 325,
        empresistant75 = 812.5,
        empresistant99 = 32.5,
      },

      duration                = 0.01,
      endsmoke                = [[0]],
      explosionGenerator      = [[custom:YELLOW_LIGHTNING_BOMB]],
      heightMod               = 1,
      impulseBoost            = 0,
      impulseFactor           = 0,
      intensity               = 12,
      interceptedByShieldType = 1,
      lineOfSight             = true,
      minbarrelangle          = [[0]],
      minIntensity            = 1,
      noSelfDamage            = true,
      paralyzer               = true,
      paralyzeTime            = 8,
      pitchtolerance          = [[12000]],
      range                   = 520,
      reloadtime              = 5,
      renderType              = 7,
      rgbColor                = [[1 1 0.25]],
      soundHit                = [[OTAunit/Lashit]],
      soundStart              = [[hackshot]],
      soundTrigger            = true,
      startsmoke              = [[0]],
      targetMoveError         = 0.3,
      texture1                = [[lightning]],
      thickness               = 1.25,
      tolerance               = 6000,
      turret                  = false,
      weaponType              = [[LightningCannon]],
      weaponVelocity          = 1000,
    },

  },


  featureDefs         = {

    DEAD  = {
      description      = [[Wreckage - Dragonfly]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 1100,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[40]],
      hitdensity       = [[100]],
      metal            = 200,
      object           = [[ARMHAM_DEAD]],
      reclaimable      = true,
      reclaimTime      = 200,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Dragonfly]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 1100,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 200,
      object           = [[debris3x3b.s3o]],
      reclaimable      = true,
      reclaimTime      = 200,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Dragonfly]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 1100,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 100,
      object           = [[debris3x3b.s3o]],
      reclaimable      = true,
      reclaimTime      = 100,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ armdfly = unitDef })
