unitDef = {
  unitname            = [[armfav]],
  name                = [[Jeffy]],
  description         = [[Raider/Scout Vehicle]],
  acceleration        = 0.158,
  bmcode              = [[1]],
  brakeRate           = 0.165,
  buildCostEnergy     = 30,
  buildCostMetal      = 30,
  builder             = false,
  buildPic            = [[ARMFAV.png]],
  buildTime           = 30,
  canAttack           = true,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canstop             = [[1]],
  category            = [[LAND]],
  corpse              = [[DEAD]],

  customParams        = {
    description_bp = [[Veículo batedor/agressor]],
    description_fr = [[Véhicule Pilleur/Éclaireur]],
    helptext       = [[Cheap and fast, the Jeffy is deadly in the first minutes of the game if your opponent is caught off-guard. Can morph into area and pitfall mines. Use missile towers, LLTs or any quick units to stop them.]],
    helptext_bp    = [[Jeffy é um batedor ou agressor rápido e barato. ? letal nos primeiros minutos do jogo se o oponente for pego de surpresa. Use torres de misseis, torres de laser levels ou suas própias unidades para paralos.]],
    helptext_fr    = [[Rapide et peut couteux, le Jeffy peut etre mortel durant les premieres minute du jeux si votre opposant est pris par surprise. Pour les contrer, utilisez des tour missile, des LLT ou des unités rapide. ]],
  },

  defaultmissiontype  = [[Standby]],
  explodeAs           = [[SMALL_UNITEX]],
  footprintX          = 2,
  footprintZ          = 2,
  iconType            = [[vehiclescout]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  leaveTracks         = true,
  maneuverleashlength = [[640]],
  mass                = 15,
  maxDamage           = 80,
  maxSlope            = 18,
  maxVelocity         = 6.6,
  maxWaterDepth       = 22,
  minCloakDistance    = 75,
  movementClass       = [[TANK2]],
  moveState           = 0,
  noAutoFire          = false,
  noChaseCategory     = [[TERRAFORM FIXEDWING SATELLITE SUB]],
  objectName          = [[jeffy.s3o]],
  seismicSignature    = 4,
  selfDestructAs      = [[SMALL_UNITEX]],
  side                = [[ARM]],
  sightDistance       = 550,
  smoothAnim          = true,
  steeringmode        = [[1]],
  TEDClass            = [[TANK]],
  trackOffset         = -3,
  trackStrength       = 3,
  trackStretch        = 1,
  trackType           = [[StdTank]],
  trackWidth          = 25,
  turninplace         = 0,
  turnInPlace         = 0,
  turnRate            = 1144,
  workerTime          = 0,

  weapons             = {

    {
      def                = [[ARM_LASER]],
      badTargetCategory  = [[FIXEDWING]],
      onlyTargetCategory = [[FIXEDWING LAND SINK SHIP SWIM FLOAT GUNSHIP HOVER]],
    },

  },


  weaponDefs          = {

    ARM_LASER = {
      name                    = [[Laser]],
      areaOfEffect            = 8,
      beamlaser               = 1,
      beamTime                = 0.1,
      coreThickness           = 0.5,
      craterBoost             = 0,
      craterMult              = 0,

      damage                  = {
        default = 40,
        planes  = 40,
        subs    = 2,
      },

      duration                = 0.02,
      energypershot           = 0.2,
      explosionGenerator      = [[custom:FLASH1yellow2]],
      fireStarter             = 50,
      impactOnly              = true,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 1,
      laserFlareSize          = 6.71,
      lineOfSight             = true,
      minIntensity            = 1,
      noSelfDamage            = true,
      range                   = 180,
      reloadtime              = 1,
      renderType              = 0,
      rgbColor                = [[1 1 0.4]],
      soundHit                = [[laserhit]],
      soundStart              = [[OTAunit/LASRFIR1]],
      soundTrigger            = true,
      targetMoveError         = 0.2,
      thickness               = 4.47213595499958,
      tolerance               = 10000,
      turret                  = true,
      weaponType              = [[BeamLaser]],
      weaponVelocity          = 800,
    },

  },


  featureDefs         = {

    DEAD  = {
      description      = [[Wreckage - Jeffy]],
      blocking         = false,
      category         = [[corpses]],
      damage           = 80,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 12,
      object           = [[wreck2x2a.s3o]],
      reclaimable      = true,
      reclaimTime      = 12,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Jeffy]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 80,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 12,
      object           = [[debris2x2c.s3o]],
      reclaimable      = true,
      reclaimTime      = 12,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Jeffy]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 80,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 6,
      object           = [[debris2x2c.s3o]],
      reclaimable      = true,
      reclaimTime      = 6,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ armfav = unitDef })
