unitDef = {
  unitname            = [[armhawk2]],
  name                = [[KingRaptor]],
  description         = [[Ace Stealth Interceptor]],
  amphibious          = true,
  autoheal            = 20,
  buildCostEnergy     = 600,
  buildCostMetal      = 600,
  buildPic            = [[armhawk2.png]],
  buildTime           = 600,
  canAttack           = true,
  canDropFlare        = false,
  canFly              = true,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canstop             = [[1]],
  canSubmerge         = false,
  category            = [[FIXEDWING]],
  collide             = false,
  corpse              = [[HEAP]],
  cruiseAlt           = 300,

  customParams        = {
    helptext = [[The undisputed master of the air, KingRaptor the Valiant slays evil aircraft with his burning lasers of justice to ensure a safe sky for all to admire, travel, and have sex in.]],
  },

  defaultmissiontype  = [[VTOL_standby]],
  explodeAs           = [[BIG_UNITEX]],
  floater             = true,
  footprintX          = 2,
  footprintZ          = 2,
  frontToSpeed        = 0,
  iconType            = [[stealthfighter]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  maneuverleashlength = [[1280]],
  mass                = 300,
  maxAcc              = 0.5,
  maxAileron          = 0.03,
  maxDamage           = 1925,
  maxElevator         = 0.02,
  maxRudder           = 0.01,
  maxVelocity         = 15.5,
  minCloakDistance    = 75,
  noChaseCategory     = [[TERRAFORM LAND SINK SHIP SWIM FLOAT SUB HOVER]],
  objectName          = [[helix.s3o]],
  seismicSignature    = 0,
  selfDestructAs      = [[BIG_UNITEX]],
  side                = [[ARM]],
  sightDistance       = 810,
  smoothAnim          = true,
  speedToFront        = 0,
  stealth             = true,
  TEDClass            = [[VTOL]],

  weapons             = {

    {
      def                = [[LASER]],
      badTargetCategory  = [[GUNSHIP]],
      mainDir            = [[0 0 1]],
      maxAngleDif        = 120,
      onlyTargetCategory = [[FIXEDWING GUNSHIP]],
    },

  },


  weaponDefs          = {

    LASER = {
      name                    = [[Rapid-Fire Anti-Air Laser Battery]],
      areaOfEffect            = 12,
      beamDecay               = 0.736,
      beamlaser               = 1,
      beamTime                = 0.01,
      beamttl                 = 15,
      canattackground         = false,
      coreThickness           = 0.5,
      craterBoost             = 0,
      craterMult              = 0,
      cylinderTargetting      = 1,

      damage                  = {
        default = 2.5,
        planes  = 25,
        subs    = 1.25,
      },

      energypershot           = 0.15,
      explosionGenerator      = [[custom:flash_teal7]],
      fireStarter             = 100,
      impactOnly              = true,
      impulseFactor           = 0,
      interceptedByShieldType = 1,
      laserFlareSize          = 4.19,
      lineOfSight             = true,
      minIntensity            = 1,
      noSelfDamage            = true,
      pitchtolerance          = 8192,
      range                   = 1200,
      reloadtime              = 0.1,
      renderType              = 0,
      rgbColor                = [[0 1 1]],
      soundStart              = [[OTAunit/LASRFIR2]],
      soundStartVolume        = 3,
      thickness               = 2.79508497187474,
      tolerance               = 8192,
      turret                  = true,
      weaponType              = [[BeamLaser]],
      weaponVelocity          = 2200,
    },

  },


  featureDefs         = {

    DEAD  = {
      description      = [[Wreckage - KingRaptor]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 1925,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[40]],
      hitdensity       = [[100]],
      metal            = 240,
      object           = [[ARMHAM_DEAD]],
      reclaimable      = true,
      reclaimTime      = 240,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - KingRaptor]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 1925,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 240,
      object           = [[debris2x2c.s3o]],
      reclaimable      = true,
      reclaimTime      = 240,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - KingRaptor]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 1925,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 120,
      object           = [[debris2x2c.s3o]],
      reclaimable      = true,
      reclaimTime      = 120,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ armhawk2 = unitDef })
