unitDef = {
  unitname            = [[armpt2]],
  name                = [[Skeeter]],
  description         = [[Patrol Boat (Scout/Minesweeper)]],
  acceleration        = 0.096,
  bmcode              = [[1]],
  brakeRate           = 0.025,
  buildCostEnergy     = 75,
  buildCostMetal      = 75,
  builder             = false,
  buildPic            = [[ARMPT.png]],
  buildTime           = 75,
  canAttack           = true,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canstop             = [[1]],
  category            = [[SHIP]],
  corpse              = [[DEAD]],

  customParams        = {
    helptext = [[Cheap, fast, and fragile, this Patrol Boat is good for light raiding and spotting for longer-ranged ships. Although it is armed with a small laser, it is easily destroyed by any armed resistance. It can also paralyze mines in a large area by attacking.]],
  },

  defaultmissiontype  = [[Standby]],
  explodeAs           = [[SMALL_UNITEX]],
  floater             = true,
  footprintX          = 3,
  footprintZ          = 3,
  iconType            = [[scoutboat]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  maneuverleashlength = [[640]],
  mass                = 37.5,
  maxDamage           = 295,
  maxVelocity         = 5.5,
  minCloakDistance    = 75,
  minWaterDepth       = 5,
  movementClass       = [[BOAT3]],
  noAutoFire          = false,
  noChaseCategory     = [[TERRAFORM FIXEDWING SATELLITE SUB]],
  objectName          = [[armpt.s3o]],
  seismicSignature    = 4,
  selfDestructAs      = [[SMALL_UNITEX]],
  side                = [[ARM]],
  sightDistance       = 845,
  smoothAnim          = true,
  steeringmode        = [[1]],
  TEDClass            = [[SHIP]],
  turnRate            = 644,
  workerTime          = 0,

  weapons             = {

    {
      def                = [[LASER]],
      badTargetCategory  = [[FIXEDWING]],
      onlyTargetCategory = [[FIXEDWING LAND SINK SHIP SWIM FLOAT GUNSHIP HOVER]],
    },


    {
      def                = [[MINESWEEP]],
      onlyTargetCategory = [[NONE]],
    },

  },


  weaponDefs          = {

    ARMPT_MISSILE = {
      name                    = [[Missiles]],
      areaOfEffect            = 48,
      craterBoost             = 1,
      craterMult              = 1,

      damage                  = {
        default = 65,
        subs    = 3.25,
      },

      explosionGenerator      = [[custom:FLASH2]],
      fireStarter             = 70,
      guidance                = true,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 2,
      lineOfSight             = true,
      metalpershot            = 0,
      model                   = [[missile]],
      noSelfDamage            = true,
      range                   = 500,
      reloadtime              = 2.6,
      renderType              = 1,
      selfprop                = true,
      smokedelay              = [[0.1]],
      smokeTrail              = true,
      soundHit                = [[OTAunit/XPLOSML2]],
      soundStart              = [[OTAunit/ROCKLIT1]],
      startsmoke              = [[1]],
      startVelocity           = 400,
      toAirWeapon             = true,
      tolerance               = 9000,
      tracks                  = true,
      trajectoryHeight        = 1,
      turnRate                = 40000,
      turret                  = true,
      weaponAcceleration      = 250,
      weaponVelocity          = 850,
      wobble                  = 50000,
    },


    LASER         = {
      name                    = [[Laser]],
      areaOfEffect            = 8,
      beamlaser               = 1,
      beamTime                = 0.1,
      coreThickness           = 0.5,
      craterBoost             = 0,
      craterMult              = 0,

      damage                  = {
        default = 40,
        planes  = 40,
        subs    = 2,
      },

      duration                = 0.02,
      energypershot           = 0.2,
      explosionGenerator      = [[custom:FLASH1yellow2]],
      fireStarter             = 50,
      impactOnly              = true,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 1,
      laserFlareSize          = 7.19,
      lineOfSight             = true,
      minIntensity            = 1,
      noSelfDamage            = true,
      range                   = 220,
      reloadtime              = 1,
      renderType              = 0,
      rgbColor                = [[1 1 0]],
      soundHit                = [[laserhit]],
      soundStart              = [[OTAunit/LASRFIR1]],
      soundTrigger            = true,
      targetMoveError         = 0.2,
      thickness               = 4.79583152331272,
      tolerance               = 10000,
      turret                  = true,
      weaponType              = [[BeamLaser]],
      weaponVelocity          = 750,
    },


    MINESWEEP     = {
      name                    = [[MineSweep]],
      areaOfEffect            = 512,
      avoidFeature            = false,
      avoidFriendly           = false,
      collideFeature          = false,
      collideFriendly         = false,
      craterBoost             = 0,
      craterMult              = 0,

      damage                  = {
        default = 11,
      },

      edgeEffectiveness       = 1,
      explosionGenerator      = [[custom:MINESWEEP]],
      impulseFactor           = 0,
      intensity               = 0,
      interceptedByShieldType = 1,
      lineOfSight             = false,
      noSelfDamage            = true,
      paralyzer               = true,
      paralyzeTime            = 10,
      range                   = 300,
      reloadtime              = 3,
      renderType              = 4,
      tolerance               = 32367,
      turret                  = false,
      weaponTimer             = 0.1,
      weaponType              = [[Cannon]],
      weaponVelocity          = 1024,
    },

  },


  featureDefs         = {

    DEAD  = {
      description      = [[Wreckage - Skeeter]],
      blocking         = false,
      category         = [[corpses]],
      damage           = 295,
      energy           = 0,
      featureDead      = [[DEAD2]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 30,
      object           = [[ARMPT_DEAD]],
      reclaimable      = true,
      reclaimTime      = 30,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Skeeter]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 295,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 4,
      footprintZ       = 4,
      hitdensity       = [[100]],
      metal            = 30,
      object           = [[debris4x4a.s3o]],
      reclaimable      = true,
      reclaimTime      = 30,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Skeeter]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 295,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 4,
      footprintZ       = 4,
      hitdensity       = [[100]],
      metal            = 15,
      object           = [[debris4x4a.s3o]],
      reclaimable      = true,
      reclaimTime      = 15,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ armpt2 = unitDef })
