unitDef = {
  unitname            = [[armpb]],
  name                = [[Pit Bull]],
  description         = [[Ambush Laser Turret]],
  acceleration        = 0,
  bmcode              = [[0]],
  brakeRate           = 0,
  buildCostEnergy     = 450,
  buildCostMetal      = 450,
  builder             = false,
  buildPic            = [[ARMPB.png]],
  buildTime           = 450,
  canAttack           = true,
  canstop             = [[1]],
  category            = [[SINK]],
  collisionVolumeTest = 1,
  corpse              = [[DEAD]],

  customParams        = {
    description_fr = [[Canon Gauss Ambusqué]],
    helptext       = [[The Pit Bull is a compact, resilent turret with a rapid-fire laser. When popped down, it is very difficult to destroy, making it a good choice when the enemy is using artillery.]],
    helptext_fr    = [[Le Pit Bull s'enterre et profite de son camouflage radar et optique pour attendre la bonne occasion. L'ennemi de le verra pas avant qu'il ne soit trop tard. Son canon Gauss r haute cadence fait des ravages sur tous tupes d'unités, mais il ne faut pas éspcrer percer un blindage lourd du premier coup.]],
  },

  damageModifier      = 0.2,
  defaultmissiontype  = [[GUARD_NOMOVE]],
  digger              = [[1]],
  explodeAs           = [[SMALL_BUILDINGEX]],
  footprintX          = 3,
  footprintZ          = 3,
  iconType            = [[defense]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  levelGround         = false,
  mass                = 250,
  maxDamage           = 2250,
  maxSlope            = 18,
  maxVelocity         = 0,
  maxWaterDepth       = 0,
  noAutoFire          = false,
  noChaseCategory     = [[FIXEDWING LAND SHIP SATELLITE SWIM GUNSHIP SUB HOVER]],
  objectName          = [[ARMPB]],
  seismicSignature    = 16,
  selfDestructAs      = [[SMALL_BUILDINGEX]],
  side                = [[ARM]],
  sightDistance       = 660,
  smoothAnim          = true,
  stealth             = true,
  TEDClass            = [[FORT]],
  turnRate            = 0,
  yardMap             = [[ooooooooo]],

  weapons             = {

    {
      def                = [[LASER]],
      badTargetCategory  = [[FIXEDWING]],
      onlyTargetCategory = [[LAND SINK SHIP SWIM FLOAT GUNSHIP HOVER]],
    },

  },


  weaponDefs          = {

    LASER = {
      name                    = [[Pulse Laser]],
      areaOfEffect            = 8,
      beamlaser               = 1,
      beamTime                = 0.1,
      coreThickness           = 0.5,
      craterBoost             = 0,
      craterMult              = 0,

      damage                  = {
        default = 60,
        planes  = 60,
        subs    = 3,
      },

      energypershot           = 1,
      explosionGenerator      = [[custom:FLASH1green]],
      fireStarter             = 50,
      impactOnly              = true,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 1,
      laserFlareSize          = 3.22,
      lineOfSight             = true,
      minIntensity            = 1,
      noSelfDamage            = true,
      range                   = 520,
      reloadtime              = 0.5,
      renderType              = 0,
      rgbColor                = [[0 0.9 0.4]],
      soundStart              = [[weapon/laser/small_laser_fire2]],
      soundTrigger            = true,
      targetMoveError         = 0.1,
      thickness               = 2.5,
      tolerance               = 10000,
      turret                  = true,
      weaponType              = [[BeamLaser]],
      weaponVelocity          = 600,
    },

  },


  featureDefs         = {

    DEAD  = {
      description      = [[Wreckage - Pit Bull]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 2250,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[15]],
      hitdensity       = [[100]],
      metal            = 180,
      object           = [[wreck3x3b.s3o]],
      reclaimable      = true,
      reclaimTime      = 180,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Pit Bull]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 2250,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 180,
      object           = [[debris3x3b.s3o]],
      reclaimable      = true,
      reclaimTime      = 180,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Pit Bull]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 2250,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 90,
      object           = [[debris3x3b.s3o]],
      reclaimable      = true,
      reclaimTime      = 90,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

	buildingGroundDecalDecaySpeed=30,
	buildingGroundDecalSizeX=5,
	buildingGroundDecalSizeY=5,
	useBuildingGroundDecal = true,
	buildingGroundDecalType=[[armpb_aoplane.dds]],
}

return lowerkeys({ armpb = unitDef })
