unitDef = {
  unitname          = [[armsonar]],
  name              = [[Sonar Station]],
  description       = [[Locates Water Units]],
  acceleration      = 0,
  activateWhenBuilt = true,
  bmcode            = [[0]],
  brakeRate         = 0,
  buildAngle        = 8192,
  buildCostEnergy   = 40,
  buildCostMetal    = 40,
  builder           = false,
  buildPic          = [[ARMSONAR.png]],
  buildTime         = 40,
  canAttack         = false,
  category          = [[UNARMED FLOAT]],
  corpse            = [[DEAD]],
  energyUse         = 0.5,
  explodeAs         = [[SMALL_BUILDINGEX]],
  floater           = true,
  footprintX        = 2,
  footprintZ        = 2,
  iconType          = [[sonar]],
  idleAutoHeal      = 5,
  idleTime          = 1800,
  mass              = 104,
  maxangledif1      = [[1]],
  maxDamage         = 300,
  maxSlope          = 18,
  maxVelocity       = 0,
  minCloakDistance  = 150,
  minWaterDepth     = 10,
  noAutoFire        = false,
  objectName        = [[novasonar.s3o]],
  onoffable         = true,
  seismicSignature  = 4,
  selfDestructAs    = [[SMALL_BUILDINGEX]],
  side              = [[ARM]],
  sightDistance     = 500,
  smoothAnim        = true,
  sonarDistance     = 600,
  TEDClass          = [[WATER]],
  turnRate          = 0,
  waterLine         = 0,
  workerTime        = 0,
  yardMap           = [[oooo]],
  
  customParams                  = {
    description_de = [[Ortet Einheiten unter Wasser]],
    description_pl = [[Wykrywa Jednostki Podwodne]],
    helptext       = [[The docile Sonar Station provides one of the few means of locating underwater targets.]],
    helptext_de    = [[Das Sonar ortet nach dem Echoprinzip von Radaranlagen feindliche Einheiten unter Wasser. Dazu strahlen sie selbst ein Signal aus und empfangen das entsprechende Echo, aus dessen Laufzeit auf die Entfernung zu den Einheiten geschlossen wird.]],
    helptext_pl    = [[Sonar jest odpowiednikiem radaru dzia³aj¹cym pod wod¹. Jest niezbêdny do wykrywania (a zatem i niszczenia) okrêtów podwodnych i amfibii nieprzyjaciela.]],
  },

  featureDefs       = {

    DEAD  = {
      description      = [[Wreckage - Sonar Station]],
      blocking         = false,
      category         = [[corpses]],
      damage           = 300,
      energy           = 0,
      featureDead      = [[DEAD2]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 16,
      object           = [[novasonar_dead.s3o]],
      reclaimable      = true,
      reclaimTime      = 16,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Sonar Station]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 300,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      hitdensity       = [[100]],
      metal            = 16,
      object           = [[debris2x2a.s3o]],
      reclaimable      = true,
      reclaimTime      = 16,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Sonar Station]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 300,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      hitdensity       = [[100]],
      metal            = 8,
      object           = [[debris2x2a.s3o]],
      reclaimable      = true,
      reclaimTime      = 8,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ armsonar = unitDef })
