unitDef = {
  unitname          = [[armsonar]],
  name              = [[Sonar Station]],
  description       = [[Locates Water Units]],
  acceleration      = 0,
  activateWhenBuilt = true,
  bmcode            = [[0]],
  brakeRate         = 0,
  buildAngle        = 8192,
  buildCostEnergy   = 120,
  buildCostMetal    = 120,
  builder           = false,
  buildPic          = [[ARMSONAR.png]],
  buildTime         = 120,
  canAttack         = false,
  category          = [[UNARMED FLOAT]],
  corpse            = [[DEAD]],
  energyUse         = 0.5,
  explodeAs         = [[SMALL_BUILDINGEX]],
  floater           = true,
  footprintX        = 2,
  footprintZ        = 2,
  iconType          = [[building]],
  idleAutoHeal      = 5,
  idleTime          = 1800,
  mass              = 104,
  maxangledif1      = [[1]],
  maxDamage         = 250,
  maxSlope          = 18,
  maxVelocity       = 0,
  minCloakDistance  = 150,
  minWaterDepth     = 10,
  noAutoFire        = false,
  objectName        = [[novasonar.s3o]],
  onoffable         = true,
  seismicSignature  = 4,
  selfDestructAs    = [[SMALL_BUILDINGEX]],
  side              = [[ARM]],
  sightDistance     = 500,
  smoothAnim        = true,
  sonarDistance     = 1600,
  TEDClass          = [[WATER]],
  turnRate          = 0,
  waterLine         = 0,
  workerTime        = 0,
  yardMap           = [[oooo]],
  
  customParams                  = {
    description_de = [[Ortet Einheiten unter Wasser]],
	helptext		= [[The docile Sonar Station provides one of the few means of locating underwater targets.]],
	helptext_de    = [[Das Sonar ortet nach dem Echoprinzip von Radaranlagen feindliche Einheiten unter Wasser. Dazu strahlen sie selbst ein Signal aus und empfangen das entsprechende Echo, aus dessen Laufzeit auf die Entfernung zu den Einheiten geschlossen wird.]],
  },

  featureDefs       = {

    DEAD  = {
      description      = [[Wreckage - Sonar Station]],
      blocking         = false,
      category         = [[corpses]],
      damage           = 250,
      energy           = 0,
      featureDead      = [[DEAD2]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 48,
      object           = [[novasonar_dead.s3o]],
      reclaimable      = true,
      reclaimTime      = 48,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Sonar Station]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 250,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      hitdensity       = [[100]],
      metal            = 48,
      object           = [[debris2x2a.s3o]],
      reclaimable      = true,
      reclaimTime      = 48,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Sonar Station]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 250,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      hitdensity       = [[100]],
      metal            = 24,
      object           = [[debris2x2a.s3o]],
      reclaimable      = true,
      reclaimTime      = 24,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ armsonar = unitDef })
