unitDef = {
  unitname            = [[armsaber]],
  name                = [[Sabre]],
  description         = [[Seaplane Gunship]],
  acceleration        = 0.288,
  amphibious          = true,
  bankscale           = [[1]],
  bmcode              = [[1]],
  brakeRate           = 4.613,
  buildCostEnergy     = 380,
  buildCostMetal      = 380,
  builder             = false,
  buildPic            = [[ARMSABER.png]],
  buildTime           = 380,
  canAttack           = true,
  canFly              = true,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canstop             = [[1]],
  canSubmerge         = false,
  category            = [[GUNSHIP]],
  collide             = false,
  corpse              = [[HEAP]],
  cruiseAlt           = 100,
  defaultmissiontype  = [[VTOL_standby]],
  explodeAs           = [[BIG_UNITEX]],
  floater             = true,
  footprintX          = 3,
  footprintZ          = 3,
  hoverAttack         = true,
  iconType            = [[gunship]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  maneuverleashlength = [[1280]],
  mass                = 190,
  maxDamage           = 1088,
  maxVelocity         = 6.83,
  minCloakDistance    = 75,
  moverate1           = [[10]],
  noAutoFire          = false,
  noChaseCategory     = [[TERRAFORM FIXEDWING SATELLITE GUNSHIP SUB]],
  objectName          = [[ARMSABER]],
  scale               = [[1]],
  seismicSignature    = 0,
  selfDestructAs      = [[BIG_UNITEX]],
  side                = [[ARM]],
  sightDistance       = 595,
  smoothAnim          = true,
  steeringmode        = [[1]],
  TEDClass            = [[VTOL]],
  turnRate            = 931,
  workerTime          = 0,

  weapons             = {

    {
      def                = [[LASER]],
      badTargetCategory  = [[FIXEDWING GUNSHIP]],
      onlyTargetCategory = [[FIXEDWING LAND SINK SHIP SWIM FLOAT GUNSHIP HOVER]],
    },

  },


  weaponDefs          = {

    LASER = {
      name                    = [[High-Energy Laser Battery]],
      areaOfEffect            = 12,
      avoidFeature            = false,
      beamlaser               = 1,
      beamTime                = 0.2,
      collideFriendly         = false,
      coreThickness           = 0.5,
      craterBoost             = 0,
      craterMult              = 0,

      damage                  = {
        default = 120,
        planes  = 12,
        subs    = 6,
      },

      energypershot           = 4,
      explosionGenerator      = [[custom:FLASH1blue]],
      fireStarter             = 100,
      impactOnly              = true,
      impulseFactor           = 0,
      interceptedByShieldType = 1,
      largeBeamLaser          = true,
      laserFlareSize          = 8.01,
      lineOfSight             = true,
      minIntensity            = 1,
      noSelfDamage            = true,
      pitchtolerance          = 12000,
      range                   = 420,
      reloadtime              = 1.2,
      renderType              = 0,
      rgbColor                = [[0 0 1]],
      soundStart              = [[medlaser]],
      targetMoveError         = 0.2,
      texture1                = [[largelaser]],
      texture2                = [[flare]],
      texture3                = [[flare]],
      texture4                = [[smallflare]],
      thickness               = 8.00780868902348,
      tolerance               = 18000,
      turret                  = false,
      weaponType              = [[BeamLaser]],
      weaponVelocity          = 2200,
    },

  },


  featureDefs         = {

    DEAD  = {
      description      = [[Wreckage - Sabre]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 1088,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[40]],
      hitdensity       = [[100]],
      metal            = 152,
      object           = [[ARMHAM_DEAD]],
      reclaimable      = true,
      reclaimTime      = 152,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Sabre]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 1088,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 152,
      object           = [[debris2x2c.s3o]],
      reclaimable      = true,
      reclaimTime      = 152,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Sabre]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 1088,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 76,
      object           = [[debris2x2c.s3o]],
      reclaimable      = true,
      reclaimTime      = 76,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ armsaber = unitDef })
