unitDef = {
  unitname            = [[armscab]],
  name                = [[Scarab]],
  description         = [[Mobile Anti-missile Defense]],
  acceleration        = 0.018,
  activateWhenBuilt   = true,
  antiweapons         = [[1]],
  bmcode              = [[1]],
  brakeRate           = 0.034,
  buildCostEnergy     = 2500,
  buildCostMetal      = 2500,
  builder             = false,
  buildPic            = [[ARMSCAB.png]],
  buildTime           = 2500,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canstop             = [[1]],
  category            = [[LAND]],
  corpse              = [[DEAD]],

  customParams        = {
    description_bp = [[Defesa móvel contra mísseis.]],
    description_es = [[Defensa Anti-misil Móvil]],
    description_fi = [[Mannertenv?listen ohjusten torjuntarobotti]],
    description_fr = [[D?fense Anti-missile Mobile]],
    description_it = [[Difesa Anti-missile Mobile]],
    helptext       = [[The Scarab is Nova's mobile antinuke system. Its all-terrain capability allows it to hide on the sides of cliffs, where it can be much harder to find and destroy.]],
    helptext_bp    = [[Scarab é o sistema anti-míssies atômicos móvel de Nova. É escalador, podendo se esconder no lado de colinas onde é muito mais difícil de achar e destruir. Só atira contra mísseis atômicos.]],
    helptext_es    = [[El Scarab es el sistema anti-nuclear móvil Nova. La capacidad all-terrain suya le permite treparse en los lados de los montes, donde es mucho más difícil encontrarlo y destruirlo.]],
    helptext_fi    = [[Scarab on liikkuva ydink?rkien torjuntaan erikoistunut robotti, joka pystyy liikkumaan vaikeimmassakin maastossa ja t?ten piileksim??n esimerkiksi vuoristossa vihollisen saavuttamattomissa.]],
    helptext_fr    = [[Le Scarab est la d?fense antimissile mobile des Novas. Ses capacit? de marcheur tout terrain permettent de cacher cette contre-mesure indispensable dans des lieux inaccessibles. ]],
    helptext_it    = [[Il Scarab é il sistema mobile antinucleare dei Nova. La sua capacitá all-terrain gli permette di nascondersi sui lati dei monti, dove é molto piu difficile da trovare e distruggere.]],
  },

  damageModifier      = 0.5,
  defaultmissiontype  = [[Standby]],
  explodeAs           = [[LARGE_BUILDINGEX]],
  footprintX          = 3,
  footprintZ          = 3,
  iconType            = [[spiderantinuke]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  maneuverleashlength = [[640]],
  mass                = 1250,
  maxDamage           = 780,
  maxSlope            = 72,
  maxVelocity         = 1.83,
  maxWaterDepth       = 22,
  minCloakDistance    = 75,
  movementClass       = [[TKBOT3]],
  moveState           = 0,
  objectName          = [[ARMSCAB]],
  radarDistance       = 1000,
  seismicSignature    = 4,
  selfDestructAs      = [[LARGE_BUILDINGEX]],
  side                = [[ARM]],
  sightDistance       = 660,
  smoothAnim          = true,
  steeringmode        = [[1]],
  TEDClass            = [[TANK]],
  turninplace         = 0,
  turnRate            = 473,
  workerTime          = 0,

  weapons             = {

    {
      def = [[ARMSCAB_WEAPON]],
    },

  },


  weaponDefs          = {

    ARMSCAB_WEAPON = {
      name                    = [[Anti-Nuke Missile]],
      areaOfEffect            = 96,
      collideFriendly         = false,
      coverage                = 1000,
      craterBoost             = 1,
      craterMult              = 2,

      damage                  = {
        default = 500,
        subs    = 25,
      },

      explosionGenerator      = [[custom:ANTINUKE]],
      fireStarter             = 100,
      flighttime              = 100,
      guidance                = true,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 1,
      interceptor             = 1,
      lineOfSight             = true,
      model                   = [[amdrocket]],
      noautorange             = [[1]],
      noSelfDamage            = true,
      range                   = 3000,
      reloadtime              = 12,
      renderType              = 1,
      selfprop                = true,
      smokedelay              = [[0.1]],
      smokeTrail              = true,
      soundHit                = [[OTAunit/XPLOMED4]],
      soundStart              = [[OTAunit/ROCKHVY1]],
      startsmoke              = [[1]],
      startVelocity           = 400,
      tolerance               = 4000,
      tracks                  = true,
      turnrate                = 65535,
      twoPhase                = true,
      vlaunch                 = true,
      weaponAcceleration      = 400,
      weaponTimer             = 0.2,
      weaponType              = [[StarburstLauncher]],
      weaponVelocity          = 1300,
    },

  },


  featureDefs         = {

    DEAD  = {
      description      = [[Wreckage - Scarab]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 780,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[20]],
      hitdensity       = [[100]],
      metal            = 1000,
      object           = [[ARMSCAB_DEAD]],
      reclaimable      = true,
      reclaimTime      = 1000,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Scarab]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 780,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 1000,
      object           = [[debris3x3b.s3o]],
      reclaimable      = true,
      reclaimTime      = 1000,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Scarab]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 780,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 500,
      object           = [[debris3x3b.s3o]],
      reclaimable      = true,
      reclaimTime      = 500,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ armscab = unitDef })
