unitDef = {
  unitname              = [[armspy]],
  name                  = [[Infiltrator]],
  description           = [[Spy, Anti-Heavy]],
  acceleration          = 0.3,
  activateWhenBuilt     = true,
  amphibious            = [[1]],
  bmcode                = [[1]],
  brakeRate             = 0.3,
  buildCostEnergy       = 280,
  buildCostMetal        = 280,
  builder               = false,
  buildPic              = [[armspy.png]],
  buildTime             = 280,
  canAttack             = false,
  canGuard              = false,
  canMove               = true,
  canPatrol             = true,
  canstop               = [[1]],
  category              = [[LAND]],
  cloakCost             = 4,
  cloakCostMoving       = 12,
  corpse                = [[DEAD]],

  customParams          = {
    description_bp = [[Espi?o invisível a radar]],
    description_fi = [[N?kym?t?n vakoilija]],
    description_fr = [[Espion, contre les unités lourdes]],
	description_de = [[Spion, Anti-Heavy]],
    helptext       = [[The Infiltrator is useful in two ways. Firstly it is an excellent scout, and very difficult to detect. It can penetrate deep into enemy lines. It also has the capacity to shoot a paralyzing bolt that will freeze any one target, good against heavy enemies and enemy infrastructure.]],
    helptext_bp    = [[O Infiltrador é útil de várias formas. Pode ser um batedor invisível e indetectável por radar para espiar o inimigo, ou detona-lo como uma bomba de PEM contra o inimigo.]],
    helptext_fi    = [[Tutkassakin n?kym?t?n Infiltrator pystyy piileksim??n vihollisen alueella tulematta havaituksi ker?ten hy?dyllist? informaatiota t?m?n toiminnasta. Laukaisee tuhoutuessaan EMP-pommin.]],
    helptext_fr    = [[L'infiltrator peut être utile de plusieur manières. Il peut être un éclaireur invisible et furtif permettant d'espioner la base enemie sans se faire repérer. Il peut aussi libérer une décharge EMP pour paralyser une cible, utile contre les unités lourdes et l'infrastructure.]],
	helptext_de    = [[Der Infiltrator ist für zwei Dinge nützlich. Erstens ist er ein exzellenter Aufklärer und sehr schwer zu entdecken. Er kann sich tief hinter die feindlichen Linien begeben. Außerdem besitzt er die Eigentschaft einen paralysierenden Bolzen abzuschießen, der jedes Ziel einfriert, was gegen schwere Einheiten und feindliche Infrastruktur sehr nützlich ist.]],
  },

  defaultmissiontype    = [[Standby]],
  explodeAs             = [[BIG_UNITEX]],
  fireState             = 0,
  footprintX            = 2,
  footprintZ            = 2,
  iconType              = [[walkerscout]],
  idleAutoHeal          = 5,
  idleTime              = 1800,
  leaveTracks           = true,
  initCloaked           = true,
  maneuverleashlength   = [[640]],
  mass                  = 130,
  maxDamage             = 270,
  maxSlope              = 36,
  maxVelocity           = 2.55,
  maxWaterDepth         = 22,
  minCloakDistance      = 60,
  movementClass         = [[TKBOT3]],
  moveState             = 0,
  noAutoFire            = false,
  noChaseCategory       = [[TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK TURRET]],
  objectName            = [[infiltrator.s3o]],
  script                = [[armspy.lua]],
  seismicSignature      = 16,
  selfDestructAs        = [[BIG_UNITEX]],
  selfDestructCountdown = 1,
  side                  = [[ARM]],
  sightDistance         = 550,
  smoothAnim            = true,
  steeringmode          = [[2]],
  TEDClass              = [[KBOT]],
  trackOffset           = 0,
  trackStrength         = 8,
  trackStretch          = 1,
  trackType             = [[ChickenTrackPointyShort]],
  trackWidth            = 45,
  turnRate              = 1800,
  workerTime            = 0,

  weapons               = {

    {
      def                = [[spy]],
      onlyTargetCategory = [[SWIM LAND SINK TURRET FLOAT SHIP HOVER FIXEDWING GUNSHIP]],
    },

  },


  weaponDefs            = {

    spy = {
      name                    = [[Electro-Stunner]],
      areaOfEffect            = 8,
      collideFriendly         = false,
      craterBoost             = 0,
      craterMult              = 0,

      damage                  = {
        default        = 8000,
        empresistant75 = 2000,
        empresistant99 = 80,
      },

      duration                = 8,
      explosionGenerator      = [[custom:YELLOW_LIGHTNINGPLOSION]],
      fireStarter             = 0,
      heightMod               = 1,
      impactOnly              = true,
      impulseBoost            = 0,
      impulseFactor           = 0,
      intensity               = 12,
      interceptedByShieldType = 1,
      paralyzer               = true,
      paralyzeTime            = 30,
      range                   = 100,
      reloadtime              = 35,
      renderType              = 7,
      rgbColor                = [[1 1 0.25]],
      soundStart              = [[weapon/LightningBolt]],
      soundTrigger            = true,
      targetborder            = 1,
      targetMoveError         = 0.2,
      texture1                = [[lightning]],
      thickness               = 10,
      tolerance               = 10000,
      turret                  = true,
      weaponType              = [[LightningCannon]],
      weaponVelocity          = 450,
    },

  },


  featureDefs           = {

    DEAD = {
      description      = [[Wreckage - Infiltrator]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 270,
      energy           = 0,
      featureDead      = [[HEAP]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[20]],
      hitdensity       = [[100]],
      metal            = 112,
      object           = [[behespy_dead.s3o]],
      reclaimable      = true,
      reclaimTime      = 112,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP = {
      description      = [[Debris - Infiltrator]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 270,
      energy           = 0,
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 56,
      object           = [[debris2x2a.s3o]],
      reclaimable      = true,
      reclaimTime      = 56,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ armspy = unitDef })
