unitDef = {
  unitname            = [[armsam]],
  name                = [[Samson]],
  description         = [[Ranged Support/AA Trike (must stop to fire)]],
  acceleration        = 0.026,
  bmcode              = [[1]],
  brakeRate           = 0.012,
  buildCostEnergy     = 130,
  buildCostMetal      = 130,
  builder             = false,
  buildPic            = [[ARMSAM.png]],
  buildTime           = 130,
  canAttack           = true,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canstop             = [[1]],
  category            = [[LAND]],
  corpse              = [[DEAD]],

  customParams        = {
    description_bp = [[veículo escaramuçador/anti-aéreo]],
    description_fr = [[Ranged Support/AA Trike (must stop to fire)]],
    helptext       = [[Keep the Samson at maximum range to harass the opponent's units. The Samson's beam laser is ideal against crawling bombs. It is able to hit both air and land, allowing you to counter an enemy who is using both. Cannot fire over terraform walls, and does poorly if an enemy is allowed to close range. Unlike normal skirmishers, the Samson cannot fire while moving.]],
    helptext_bp    = [[Samson é um veículo escaramuçador. Mantenha-o a distância máxima e continue a pressionar as unidades inimigas ou comandante. Seu raio de energia é ideal contra bombas rastejantes. Pode acertar tanto unidades terrestres tanto aéreas, permitindo a voç? lutar contra um inimigo que esteja usando ambas. N?o pode atirar sobre muros de terra e luta mal de perto.]],
    helptext_fr    = [[Gardez le Samson a distance de tir maximal pour harasser l'enemis. Le faisceau laser du Samson est id?al contre les bombe rampante. Il est capable d'attaquer aussi bien les unit? a?riennes que t?riennes, vous permettant de contrer un enemis utilisant les deux. Il ne peut pas tirer au dessus des murs t?rraform?s, et est tres mauvais en combat raproch?. Contrairement ? la majorit? des tirailleurs, le Samson ne peut pas tirer lorsqu'il bouge.]],
  },

  defaultmissiontype  = [[Standby]],
  explodeAs           = [[BIG_UNITEX]],
  footprintX          = 3,
  footprintZ          = 3,
  iconType            = [[vehiclesupport]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  leaveTracks         = true,
  maneuverleashlength = [[640]],
  mass                = 65,
  maxDamage           = 500,
  maxSlope            = 18,
  maxVelocity         = 2.5,
  maxWaterDepth       = 22,
  minCloakDistance    = 75,
  movementClass       = [[TANK3]],
  moveState           = 0,
  noAutoFire          = false,
  noChaseCategory     = [[TERRAFORM SATELLITE SUB]],
  objectName          = [[samson.s3o]],
  pushResistant       = 1,
  seismicSignature    = 4,
  selfDestructAs      = [[BIG_UNITEX]],

  sfxtypes            = {

    explosiongenerators = {
      [[custom:STORMMUZZLE]],
      [[custom:STORMBACK]],
    },

  },

  side                = [[ARM]],
  sightDistance       = 660,
  smoothAnim          = true,
  steeringmode        = [[1]],
  TEDClass            = [[TANK]],
  trackOffset         = -6,
  trackStrength       = 5,
  trackStretch        = 1,
  trackType           = [[StdTank]],
  trackWidth          = 32,
  turninplace         = 0,
  turnInPlace         = 0,
  turnRate            = 400,
  workerTime          = 0,

  weapons             = {

    {
      def                = [[LASER]],
      badTargetCategory  = [[UNARMED]],
      onlyTargetCategory = [[FIXEDWING LAND SINK SHIP SWIM FLOAT GUNSHIP HOVER]],
    },

  },


  weaponDefs          = {

    ARMTRUCK_MISSILE = {
      name                    = [[Missiles]],
      areaOfEffect            = 48,
      burst                   = 2,
      burstrate               = 0.25,
      craterBoost             = 1,
      craterMult              = 1,
      cylinderTargetting      = 1,

      damage                  = {
        default = 16.8,
        subs    = 0.84,
      },

      explosionGenerator      = [[custom:FLASH2]],
      fireStarter             = 70,
      flightTime              = 3,
      heightMod               = 0.1,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 2,
      lineOfSight             = true,
      metalpershot            = 0,
      model                   = [[missile]],
      noSelfDamage            = true,
      range                   = 600,
      reloadtime              = 0.75,
      renderType              = 1,
      selfprop                = true,
      smokedelay              = [[0.1]],
      smokeTrail              = true,
      soundHit                = [[OTAunit/XPLOMED2]],
      soundStart              = [[OTAunit/ROCKHVY2]],
      startsmoke              = [[1]],
      startVelocity           = 450,
      tolerance               = 8000,
      tracks                  = true,
      turnRate                = 33000,
      turret                  = true,
      weaponAcceleration      = 109,
      weaponTimer             = 5,
      weaponType              = [[MissileLauncher]],
      weaponVelocity          = 545,
    },


    LASER            = {
      name                    = [[Laser]],
      areaOfEffect            = 8,
      beamlaser               = 1,
      beamTime                = 0.1,
      coreThickness           = 0.5,
      craterBoost             = 0,
      craterMult              = 0,

      damage                  = {
        default = 26.8,
        planes  = 26.8,
        subs    = 1.34,
      },

      duration                = 0.02,
      energypershot           = 0.2,
      explosionGenerator      = [[custom:FLASH1yellow2]],
      fireStarter             = 50,
      impactOnly              = true,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 1,
      laserFlareSize          = 5.49,
      lineOfSight             = true,
      minIntensity            = 1,
      noSelfDamage            = true,
      range                   = 600,
      reloadtime              = 0.6,
      renderType              = 0,
      rgbColor                = [[1 1 0.4]],
      soundHit                = [[laserhit]],
      soundStart              = [[OTAunit/LASRFIR1]],
      soundTrigger            = true,
      targetMoveError         = 0,
      thickness               = 3.66060104354463,
      tolerance               = 10000,
      turret                  = true,
      weaponType              = [[BeamLaser]],
      weaponVelocity          = 800,
    },

  },


  featureDefs         = {

    DEAD  = {
      description      = [[Wreckage - Samson]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 500,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[20]],
      hitdensity       = [[100]],
      metal            = 52,
      object           = [[samsonwreck.s3o]],
      reclaimable      = true,
      reclaimTime      = 52,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Samson]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 500,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 52,
      object           = [[debris3x3b.s3o]],
      reclaimable      = true,
      reclaimTime      = 52,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Samson]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 500,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 26,
      object           = [[debris3x3b.s3o]],
      reclaimable      = true,
      reclaimTime      = 26,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ armsam = unitDef })
