unitDef = {
  unitname               = [[armtick]],
  name                   = [[Tick]],
  description            = [[All-Terrain EMP Crawling Bomb]],
  acceleration           = 0.18,
  bmcode                 = [[1]],
  brakeRate              = 0.6,
  buildCostEnergy        = 100,
  buildCostMetal         = 100,
  buildPic               = [[armtick.png]],
  buildTime              = 100,
  canAttack              = true,
  canGuard               = true,
  canMove                = true,
  canstop                = [[1]],
  category               = [[LAND]],
  cloakCost              = 0,
  collisionVolumeOffsets = [[0 0 0]],
  collisionVolumeScales  = [[15 15 15]],
  collisionVolumeTest    = 1,
  collisionVolumeType    = [[ellipsoid]],
  corpse                 = [[DEAD]],

  customParams           = {
    description_bp = [[Bomba de PEM escaladora rastejante]],
    description_es = [[Bomba móvil PEM All-terrain]],
    description_fi = [[Maastokelpoinen ry?miv? EMP-pommi]],
    description_fr = [[Bombe rampate EMP tout-terrain]],
    description_it = [[Bomba PEM mobile All-terrain]],
    helptext       = [[Used skillfully, the Tick can be worth dozens of times its cost. Use it to paralyze defenses, heavy units, and tightly packed units armed with slow weapons. Other units can then eliminate the helpless enemies without risk. Counter with missile towers or single cheap units to set off a premature detonation.]],
    helptext_bp    = [[Tick ? um rob? de PEM escalador suicida. Usado com habilidade pode valer v?rias vezes seu pre?o. Use-o para paralizar defesas, unidades inimigas pesadas e grupos de unidades inimigas pr?ximas umas das outras armadas com armas lentas. Outras unidades podem entao eliminar as unidades paralizadas correndo pouco risco. defenda-se com defenders ou caminhoes de miss?is, ou uma ?nica unidade barata para provocar uma explosao prematura.]],
    helptext_es    = [[Usado bien, el Tick puede valer docenas de veces su costo. Usalo para paralizar defensas, unidades pesadas, y masas de unidades con armas lentas. Otras unidades pueden eliminar a los enemigos indefensos sin riesgos. Contrastalos con torres de misil o síngolas unidades baratas para causar detonaciones inmaduras.]],
    helptext_fi    = [[Taitavasti k?ytettyn? Tick voi maksaa itsens? takaisin lukuisia kertoja. K?yt? sit? niit? vihollisia vastaan, joiden l?helle p??set - esimerkkin? suuret, hitaasti ampuvat yksik?t ja tiiviit ryhmittym?t. Muu armeijasi voi t?m?n j?lkeen vaaratta eliminoida lamaantuneet vastustajat. Ohjukset ja laserit r?j?ytt?v?t Tickin helposti ennen kuin se ylt?? kohteeseensa.]],
    helptext_fr    = [[Utilisé avec tacte, le Tick peut valoir une dizaine de fois son prix. Utilisez le pour paralyser les defenses, unité lourdes, et les hordes d'énemis munis d'arme lente. Vos unités peuvent par la suite éliminer l'énemis devenus impotant sans risques. Contrez les avec des tour missiles ou détonez le prématurément en utilisant des unités a moindre cout.]],
    helptext_it    = [[Usato bene, il Tick puo valere dozzine di volte il suo costo. Usalo per paralizzare difese, unitá pesanti, e masse di unitá con armi lente. Altre tue unitá posson eliminare i nemici indifesi senza rischi. Contrastali con torri lancia-razzo o singole unitá economiche per provocare una detonazione prematura.]],
  },

  designation            = [[ARM-PASPD2]],
  explodeAs              = [[ARMTICK_DEATH]],
  fireState              = 0,
  footprintX             = 1,
  footprintZ             = 1,
  iconType               = [[spiderbomb]],
  kamikaze               = true,
  kamikazeDistance       = 80,
  kamikazeUseLOS         = true,
  mass                   = 82,
  maxDamage              = 50,
  maxSlope               = 72,
  maxVelocity            = 4.2,
  maxWaterDepth          = 15,
  minCloakDistance       = 40,
  movementClass          = [[TKBOT1]],
  noChaseCategory        = [[FIXEDWING LAND SINK SHIP SATELLITE SWIM GUNSHIP FLOAT SUB HOVER]],
  objectName             = [[ARMTICK]],
  pushResistant          = 1,
  seismicSignature       = 4,
  selfDestructAs         = [[ARMTICK_DEATH]],
  selfDestructCountdown  = 0,

  sfxtypes               = {

    explosiongenerators = {
      [[custom:digdig]],
    },

  },

  shootme                = [[1]],
  side                   = [[ARM]],
  sightDistance          = 160,
  smoothAnim             = true,
  steeringmode           = [[1]],
  TEDClass               = [[TANK]],
  threed                 = [[1]],
  turninplace            = 0,
  turnRate               = 1500,
  wpri_badtargetcategory = [[VTOL]],
  zbuffer                = [[1]],

  featureDefs            = {

    DEAD  = {
      description      = [[Wreckage - Tick]],
      blocking         = true,
      category         = [[arm_corpses]],
      damage           = 50,
      featureDead      = [[DEAD2]],
      featurereclamate = [[smudge01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[20]],
      hitdensity       = [[100]],
      metal            = 40,
      object           = [[armtick_dead]],
      reclaimable      = true,
      reclaimTime      = 40,
      seqnamereclamate = [[tree1reclamate]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Tick]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 50,
      featureDead      = [[HEAP]],
      featurereclamate = [[smudge01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 40,
      object           = [[debris1x1a.s3o]],
      reclaimable      = true,
      reclaimTime      = 40,
      seqnamereclamate = [[tree1reclamate]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Tick]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 50,
      featurereclamate = [[smudge01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 20,
      object           = [[debris1x1a.s3o]],
      reclaimable      = true,
      reclaimTime      = 20,
      seqnamereclamate = [[tree1reclamate]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ armtick = unitDef })
