unitDef = {
  unitname               = [[blastwing2]],
  name                   = [[Blastwing]],
  description            = [[Bomb Drone]],
  acceleration           = 0.1,
  airhoverfactor         = 1,
  altfromsealevel        = [[60]],
  amphibious             = true,
  bankscale              = [[1.64]],
  brakeRate              = 3.5,
  buildCostEnergy        = 50,
  buildCostMetal         = 50,
  builder                = false,
  buildPic               = [[blastwing.png]],
  buildTime              = 50,
  canAttack              = true,
  canFly                 = true,
  canGuard               = true,
  canMove                = true,
  canPatrol              = true,
  canstop                = true,
  canSubmerge            = false,
  category               = [[GUNSHIP]],
  collide                = false,
  cruiseAlt              = 60,
  defaultmissiontype     = [[VTOL_standby]],
  floater                = true,
  footprintX             = 2,
  footprintZ             = 2,
  hoverAttack            = true,
  iconType               = [[airbomb]],
  idleAutoHeal           = 5,
  idleTime               = 1800,
  kamikaze               = true,
  maneuverleashlength    = [[1240]],
  mass                   = 25,
  maxDamage              = 100,
  maxVelocity            = 8.2,
  minCloakDistance       = 75,
  noAutoFire             = false,
  noChaseCategory        = [[TERRAFORM SATELLITE SUB]],
  objectName             = [[f-1.s3o]],
  scale                  = [[1]],
  script                 = [[blastwing.lua]],
  seismicSignature       = 0,
  selfDestructAs         = [[BLASTWING_EXPLOSION]],
  selfDestructCountdown  = 0,
  side                   = [[CORE]],
  sightDistance          = 380,
  smoothAnim             = true,
  steeringmode           = [[1]],
  TEDClass               = [[VTOL]],
  turnRate               = 1144,
  wpri_badtargetcategory = [[VTOL]],

  weapons                = {

    {
      def                = [[missile]],
      onlyTargetCategory = [[FIXEDWING LAND SINK SHIP SWIM FLOAT GUNSHIP HOVER]],
    },

  },


  weaponDefs             = {

    missile = {
      name                    = [[Missile]],
      areaOfEffect            = 160,
      cegTag                  = [[BANISHERTRAIL]],
      craterBoost             = 1,
      craterMult              = 2,

      damage                  = {
        default = 500,
        subs    = 75,
      },

      edgeEffectiveness       = 0.4,
      explosionGenerator      = [[custom:xamelimpact]],
      fireStarter             = 20,
      flightTime              = 4,
      guidance                = true,
      impulseBoost            = 0,
      impulseFactor           = 0.6,
      interceptedByShieldType = 2,
      lineOfSight             = true,
      model                   = [[corbanishrk.s3o]],
      noSelfDamage            = true,
      range                   = 200,
      reloadtime              = 4,
      renderType              = 1,
      selfprop                = true,
      smokedelay              = [[0.01]],
      smokeTrail              = false,
      soundHit                = [[TAWF114b]],
      soundStart              = [[nexuiz/rocket_fire]],
      startsmoke              = [[1]],
      startVelocity           = 400,
      tolerance               = 9000,
      tracks                  = true,
      trajectoryHeight        = 0.45,
      turnRate                = 22000,
      turret                  = true,
      weaponAcceleration      = 70,
      weaponTimer             = 5,
      weaponType              = [[MissileLauncher]],
      weaponVelocity          = 400,
    },

  },

}

return lowerkeys({ blastwing2 = unitDef })
