unitDef = {
  unitname              = [[chicken_dodo]],
  name                  = [[Dodo]],
  description           = [[Chicken Bomb]],
  acceleration          = 6,
  activateWhenBuilt     = true,
  bmcode                = [[1]],
  brakeRate             = 0.2,
  buildCostEnergy       = 0,
  buildCostMetal        = 0,
  builder               = false,
  buildPic              = [[chicken_dodo.png]],
  buildTime             = 170,
  canGuard              = true,
  canHover              = true,
  canMove               = true,
  canPatrol             = true,
  canstop               = [[1]],
  category              = [[SWIM]],

  customParams          = {
    description_fr = [[Chicken Bomb]],
    helptext       = [[The Dodo's body contains a volatile mixture of organic explosives. At the slightest provocation, it explodes spectacularly, with the resulting shockwave throwing nearby units into the air. Beware as its flying limbs and spikes will do residual damage.]],
    helptext_fr    = [[The Dodo's body contains a volatile mixture of organic explosives. At the slightest provocation, it explodes spectacularly, with the resulting shockwave throwing nearby units into the air. Beware as its flying limbs and spikes will do residual damage.]],
  },

  defaultmissiontype    = [[Standby]],
  explodeAs             = [[DODO_DEATH]],
  floater               = false,
  footprintX            = 2,
  footprintZ            = 2,
  iconType              = [[chickendodo]],
  idleAutoHeal          = 20,
  idleTime              = 300,
  kamikaze              = true,
  kamikazeDistance      = 80,
  leaveTracks           = true,
  maneuverleashlength   = [[640]],
  mass                  = 117,
  maxDamage             = 200,
  maxSlope              = 36,
  maxVelocity           = 7,
  minCloakDistance      = 75,
  movementClass         = [[BHOVER3]],
  movestate             = 2,
  noAutoFire            = false,
  noChaseCategory       = [[FIXEDWING SATELLITE GUNSHIP SUB]],
  objectName            = [[chicken_dodo.s3o]],
  onoffable             = true,
  power                 = 170,
  seismicSignature      = 4,
  selfDestructAs        = [[DODO_DEATH]],
  selfDestructCountdown = 0,

  sfxtypes              = {

    explosiongenerators = {
      [[custom:blood_spray]],
      [[custom:green_goo]],
      [[custom:dirt]],
    },

  },

  side                  = [[THUNDERBIRDS]],
  sightDistance         = 256,
  smoothAnim            = true,
  steeringmode          = [[2]],
  TEDClass              = [[KBOT]],
  trackOffset           = 1,
  trackStrength         = 6,
  trackStretch          = 1,
  trackType             = [[ChickenTrack]],
  trackWidth            = 10,
  turnRate              = 2000,
  upright               = false,
  waterline             = 4,
  workerTime            = 0,
}

return lowerkeys({ chicken_dodo = unitDef })
