unitDef = {
  unitname            = [[commrecon1]],
  name                = [[Recon Commander]],
  description         = [[High Mobility Commander, Builds at 10 m/s]],
  acceleration        = 0.25,
  activateWhenBuilt   = true,
  amphibious          = [[1]],
  autoHeal            = 5,
  brakeRate           = 0.45,
  buildCostEnergy     = 1200,
  buildCostMetal      = 1200,
  buildDistance       = 120,
  builder             = true,

  buildoptions        = {
  },

  buildPic            = [[commrecon.png]],
  buildTime           = 1200,
  canAttack           = true,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canManualFire       = true,
  category            = [[LAND]],
  commander           = true,
  collisionVolumeOffsets = [[0 0 0]],
  collisionVolumeScales  = [[45 50 45]],
  collisionVolumeTest    = 1,
  collisionVolumeType    = [[CylY]],  
  corpse              = [[DEAD]],

  customParams        = {
    canjump            = 1,
    jump_range         = 400,
    jump_speed         = 6,
    jump_reload        = 20,
    jump_from_midair   = 1,

	cloakstealth = [[1]],
	description_de = [[Hochmobiler Kommandant, Baut mit 10 M/s]],
	description_pl = [[Mobilny Dowodca, moc 10 m/s]],
	helptext       = [[The Recon Commander revolves around mobility and guile; this lightly armored platform can mount many special weapons and modules and comes pre-equipped with jumpjets.]],
	helptext_de    = [[Bei dem Recon Commander dreht sich alles um Mobilit‰t und List. Dieser schwach gepanzerte Grundsatz kann um viele Spezialwaffen und -module erweitert werden. Er besitzt auﬂerdem einen D?enstrahl zum Springen.]],
	helptext_pl    = [[Recon to Dowodca oparty na na szybkosci i przebieglosci; moze uzywac wielu egzotycznych broni i jest wyposazony w mozliwosc skoku.]],
	level = [[1]],
	statsname = [[commrecon1]],
	soundok = [[heavy_bot_move]],
	soundselect = [[bot_select]],
	soundbuild = [[builder_start]],
    commtype = [[3]],
    aimposoffset   = [[0 10 0]],
	att_speedmult  = 0.5,
  },

  energyStorage       = 0,
  energyUse           = 0,
  explodeAs           = [[ESTOR_BUILDINGEX]],
  footprintX          = 2,
  footprintZ          = 2,
  hideDamage          = false,
  iconType            = [[commander1]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  leaveTracks         = true,
  losEmitHeight       = 40,
  mass                = 407,
  maxDamage           = 1650,
  maxSlope            = 36,
  maxVelocity         = 1.45,
  maxWaterDepth       = 5000,
  metalStorage        = 0,
  minCloakDistance    = 75,
  movementClass       = [[AKBOT2]],
  noChaseCategory     = [[TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK TURRET]],
  norestrict          = [[1]],
  objectName          = [[commrecon.s3o]],
  script              = [[commrecon.lua]],
  seismicSignature    = 16,
  selfDestructAs      = [[ESTOR_BUILDINGEX]],

  sfxtypes            = {

    explosiongenerators = {
	  [[custom:NONE]],
	  [[custom:NONE]],
      [[custom:RAIDMUZZLE]],
	  [[custom:NONE]],
      [[custom:VINDIBACK]],
      [[custom:FLASH64]],
    },

  },

  showNanoSpray       = false,
  showPlayerName      = true,
  side                = [[ARM]],
  sightDistance       = 500,
  smoothAnim          = true,
  sonarDistance       = 300,
  trackOffset         = 0,
  trackStrength       = 8,
  trackStretch        = 1,
  trackType           = [[ComTrack]],
  trackWidth          = 22,
  terraformSpeed      = 600,
  turnRate            = 1350,
  upright             = true,
  workerTime          = 10,

  weapons             = {
  
	[1] = {
      def                = [[PEASHOOTER]],
      badTargetCategory  = [[FIXEDWING]],
      onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],	
	},

	[2] = {
      def                = [[LPB]],
      badTargetCategory  = [[FIXEDWING]],
      onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],	
	},

	[3] = {
      def                = [[HPB]],
      badTargetCategory  = [[FIXEDWING]],
      onlyTargetCategory = [[FIXEDWING LAND SINK TURRET SHIP SWIM FLOAT GUNSHIP HOVER]],	
	},

	[4] = {
      def                = [[PERSONAL_SHIELD]],
	},
	[5] = {
      def                = [[AREA_SHIELD]],
	},
  },

  weaponDefs          = {

	PEASHOOTER = {
		name                    = [[Laser Blaster]],
		areaOfEffect            = 8,
		coreThickness           = 0.5,
		craterBoost             = 0,
		craterMult              = 0,

		customParams			= {
			muzzleEffectShot = [[custom:BEAMWEAPON_MUZZLE_RED]],
		},

		damage                  = {
			default = 10,
		},

		duration                = 0.02,
		explosionGenerator      = [[custom:BEAMWEAPON_HIT_RED]],
		fireStarter             = 50,
		heightMod               = 1,
		impactOnly              = true,
		impulseBoost            = 0,
		impulseFactor           = 0.4,
		interceptedByShieldType = 1,
		noSelfDamage            = true,
		range                   = 300,
		reloadtime              = 0.1,
		rgbColor                = [[1 0 0]],
		soundHit                = [[weapon/laser/lasercannon_hit]],
		soundStart              = [[weapon/laser/small_laser_fire2]],
		soundTrigger            = true,
		thickness               = 2.55,
		tolerance               = 10000,
		turret                  = true,
		weaponType              = [[LaserCannon]],
		weaponVelocity          = 880,
	},
	
	LPB = {
		name                    = [[Light Particle Beam]],
		beamDecay               = 0.85,
		beamTime                = 0.01,
		beamttl                 = 45,
		coreThickness           = 0.5,
		craterBoost             = 0,
		craterMult              = 0,

		damage                  = {
			default = 40.01,
		},

		explosionGenerator      = [[custom:flash1red]],
		fireStarter             = 100,
		impactOnly              = true,
		impulseFactor           = 0,
		interceptedByShieldType = 1,
		laserFlareSize          = 4.5,
		minIntensity            = 1,
		range                   = 330,
		reloadtime              = 10/30,
		rgbColor                = [[1 0 0]],
		soundStart              = [[weapon/laser/mini_laser]],
		soundStartVolume        = 5,
		thickness               = 4,
		tolerance               = 8192,
		turret                  = true,
		weaponType              = [[BeamLaser]],
	},

	HPB = {
		name                    = [[Heavy Particle Beam]],
		beamDecay               = 0.9,
		beamTime                = 0.01,
		beamttl                 = 75,
		commandfire             = true,
		coreThickness           = 0.5,
		craterBoost             = 0,
		craterMult              = 0,

		damage                  = {
			default = 2000.1,
		},

		explosionGenerator      = [[custom:blue_explosion]],
		fireStarter             = 100,
		impactOnly              = true,
		impulseFactor           = 0,
		interceptedByShieldType = 1,
		laserFlareSize          = 10,
		minIntensity            = 1,
		pitchtolerance          = 8192,
		range                   = 350,
		reloadtime              = 15,
		rgbColor                = [[0.1 0.2 1]],
		soundStart              = [[weapon/laser/small_laser_fire4]],
		soundStartVolume        = 5,
		thickness               = 8,
		tolerance               = 8192,
		turret                  = true,
		weaponType              = [[BeamLaser]],
	},
	
    PERSONAL_SHIELD = {
		name                    = [[Personal Shield]],
		exteriorShield          = true,
		shieldAlpha             = 0.2,
		shieldBadColor          = [[1 0.1 0.1]],
		shieldGoodColor         = [[0.1 0.1 1]],
		shieldInterceptType     = 3,
		shieldPower             = 1250,
		shieldPowerRegen        = 16,
		shieldPowerRegenEnergy  = 0,
		shieldRadius            = 80,
		shieldRepulser          = false,
		shieldStartingPower     = 600,
		smartShield             = true,
		texture1                = [[shield3mist]],
		visibleShield           = true,
		visibleShieldHitFrames  = 4,
		visibleShieldRepulse    = true,
		weaponType              = [[Shield]],
		damage = {},
    },

	AREA_SHIELD = {
		name                    = [[Area Shield]],
		exteriorShield          = true,
		shieldAlpha             = 0.2,
		shieldBadColor          = [[1 0.1 0.1]],
		shieldGoodColor         = [[0.1 0.1 1]],
		shieldInterceptType     = 3,
		shieldPower             = 3600,
		shieldPowerRegen        = 50,
		shieldPowerRegenEnergy  = 12,
		shieldRadius            = 350,
		shieldRepulser          = false,
		smartShield             = true,
		texture1                = [[shield3mist]],
		visibleShield           = true,
		visibleShieldHitFrames  = 4,
		visibleShieldRepulse    = true,
		weaponType              = [[Shield]],
		damage                  = {},
	},
	
  },

  
  featureDefs         = {

    DEAD      = {
      description      = [[Wreckage - Recon Commander]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 1650,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[20]],
      hitdensity       = [[100]],
      metal            = 480,
      object           = [[commrecon_dead.s3o]],
      reclaimable      = true,
      reclaimTime      = 480,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP      = {
      description      = [[Debris - Recon Commander]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 1650,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      hitdensity       = [[100]],
      metal            = 480,
      object           = [[debris2x2c.s3o]],
      reclaimable      = true,
      reclaimTime      = 480,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ commrecon1 = unitDef })
