unitDef = {
  unitname            = [[concept_con]],
  name                = [[Dr. Quantum's Quizzical Qonstructor of a Quintillion Quandaries]],
  description         = [[Concept Engineer, Builds at 12 m/s]],
  acceleration        = 0.084,
  amphibious          = true,
  bankscale           = [[1.5]],
  bmcode              = [[1]],
  brakeRate           = 1.87,
  buildCostEnergy     = 900,
  buildCostMetal      = 900,
  buildDistance       = 80,
  builder             = true,

  buildoptions        = {
    [[concept_factory]],
    [[repairer]],
    [[armrl2]],
    [[armamb]],
    [[cortoast]],
    [[cordoom2]],
    [[armcent]],
    [[corjamt2]],
    [[mcbrtha]],
  },

  buildPic            = [[concept_con.png]],
  buildRange3D        = false,
  buildTime           = 900,
  canFly              = true,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canreclamate        = [[1]],
  canstop             = [[1]],
  canSubmerge         = false,
  category            = [[GUNSHIP UNARMED]],
  collide             = false,
  corpse              = [[HEAP]],
  cruiseAlt           = 70,
  defaultmissiontype  = [[VTOL_standby]],
  energyMake          = 0.3,
  energyUse           = 0,
  explodeAs           = [[CA_EX]],
  floater             = true,
  footprintX          = 2,
  footprintZ          = 2,
  iconType            = [[builder]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  maneuverleashlength = [[1280]],
  mass                = 450,
  maxDamage           = 240,
  maxVelocity         = 9.17,
  metalMake           = 0.3,
  minCloakDistance    = 75,
  noAutoFire          = false,
  noChaseCategory     = [[TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK]],
  objectName          = [[concept_con]],
  radarDistance       = 400,
  radarDistanceJam    = 200,
  scale               = [[0.8]],
  seismicDistance     = 300,
  seismicSignature    = 0,
  selfDestructAs      = [[CA_EX]],
  side                = [[ARM]],
  sightDistance       = 380,
  smoothAnim          = true,
  steeringmode        = [[1]],
  TEDClass            = [[VTOL]],
  terraformSpeed      = 600,
  turnRate            = 148,
  workerTime          = 12,

  featureDefs         = {

    DEAD  = {
      description      = [[Wreckage - Dr. Quantum's Quizzical Qonstructor of a Quintillion Quandaries]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 240,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[40]],
      hitdensity       = [[100]],
      metal            = 360,
      object           = [[wreck3x3b.s3o]],
      reclaimable      = true,
      reclaimTime      = 360,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Dr. Quantum's Quizzical Qonstructor of a Quintillion Quandaries]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 240,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 360,
      object           = [[debris2x2a.s3o]],
      reclaimable      = true,
      reclaimTime      = 360,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Dr. Quantum's Quizzical Qonstructor of a Quintillion Quandaries]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 240,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 180,
      object           = [[debris2x2a.s3o]],
      reclaimable      = true,
      reclaimTime      = 180,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ concept_con = unitDef })
