unitDef = {
  unitname           = [[corafrad]],
  name               = [[Floating Advanced Radar Tower]],
  description        = [[Long-Range Radar]],
  acceleration       = 0,
  activateWhenBuilt  = true,
  bmcode             = [[0]],
  brakeRate          = 0,
  buildAngle         = 8192,
  buildCostEnergy    = 500,
  buildCostMetal     = 500,
  builder            = false,
  buildPic           = [[CORAFRAD.png]],
  buildTime          = 500,
  canAttack          = false,
  category           = [[UNARMED FLOAT]],
  corpse             = [[DEAD]],
  energyUse          = 1.5,
  explodeAs          = [[SMALL_BUILDINGEX]],
  footprintX         = 4,
  footprintZ         = 4,
  iconType           = [[radar]],
  idleAutoHeal       = 5,
  idleTime           = 1800,
  isTargetingUpgrade = true,
  mass               = 250,
  maxangledif1       = [[1]],
  maxDamage          = 550,
  maxSlope           = 18,
  maxVelocity        = 0,
  minCloakDistance   = 150,
  minWaterDepth      = 0,
  noAutoFire         = false,
  objectName         = [[CORAFRAD]],
  onoffable          = true,
  radarDistance      = 4000,
  seismicSignature   = 4,
  selfDestructAs     = [[SMALL_BUILDINGEX]],
  side               = [[CORE]],
  sightDistance      = 800,
  smoothAnim         = true,
  TEDClass           = [[SPECIAL]],
  turnRate           = 0,
  waterline          = 0,
  workerTime         = 0,
  yardMap            = [[wwwwwwwwwwwwwwww]],

  featureDefs        = {

    DEAD  = {
      description      = [[Wreckage - Floating Advanced Radar Tower]],
      blocking         = false,
      category         = [[corpses]],
      damage           = 550,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 4,
      footprintZ       = 4,
      height           = [[20]],
      hitdensity       = [[100]],
      metal            = 200,
      object           = [[CORAFRAD_DEAD]],
      reclaimable      = true,
      reclaimTime      = 200,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Floating Advanced Radar Tower]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 550,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 200,
      object           = [[debris3x3b.s3o]],
      reclaimable      = true,
      reclaimTime      = 200,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Floating Advanced Radar Tower]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 550,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 100,
      object           = [[debris3x3b.s3o]],
      reclaimable      = true,
      reclaimTime      = 100,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ corafrad = unitDef })
