unitDef = {
  unitname            = [[corcsa]],
  name                = [[Outcast]],
  description         = [[Airborne SpecOps Engineer, Builds at 6 m/s]],
  acceleration        = 0.072,
  airStrafe           = 0,
  amphibious          = true,
  autoHeal            = 2,
  bankscale           = [[1.5]],
  bmcode              = [[1]],
  brakeRate           = 1.875,
  buildCostEnergy     = 500,
  buildCostMetal      = 500,
  buildDistance       = 60,
  builder             = true,

  buildoptions        = {
    [[cormex]],
    [[corsolar]],
    [[corwin]],
    [[cornanotc]],
    [[corrad]],
    [[corjamt]],
    [[cormine1]],
    [[corrl]],
    [[corllt]],
    [[corgrav]],
    [[corpre]],
    [[cordl]],
    [[corhlt]],
    [[corvipe]],
    [[corrazor]],
    [[corcomdgun]],
    [[corkarg]],
    [[armraven]],
    [[gorg]],
    [[corkrog]],
    [[cortide]],
    [[corsonar]],
    [[cortl]],
    [[corfast]],
    [[blastwing]],
    [[corak]],
    [[cormort]],
    [[corpyro]],
    [[corthud]],
    [[corroach]],
  },

  buildPic            = [[CORCSA.png]],
  buildRange3D        = false,
  buildTime           = 500,
  canFly              = true,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canreclamate        = [[1]],
  canstop             = [[1]],
  canSubmerge         = false,
  category            = [[GUNSHIP UNARMED]],
  cloakCost           = 10,
  cloakCostMoving     = 10,
  collide             = true,
  corpse              = [[HEAP]],
  cruiseAlt           = 80,

  customParams        = {
    description_fr = [[ADAV de Construcion Furtif Camouflable, Construit r 6 m/s]],
    helptext       = [[One of the few stealth Logos units, the Outcast is a surprisingly subtle approach to the problem of interdiction. It is capable of getting past hostile defenses undetected, then putting together a field army in the back of the enemy's base.]],
    helptext_fr    = [[Le Outcast est un ingénieur de combat non armé. Équipé d'un brouilleur radar et d'un camouflage optique il peut construire certaines infrastructures et des unités nimporte ou, et ainsi surprendre l'enneme. ]],
  },

  defaultmissiontype  = [[VTOL_Standby]],
  energyMake          = 0.15,
  energyUse           = 0,
  explodeAs           = [[GUNSHIPEX]],
  floater             = true,
  footprintX          = 2,
  footprintZ          = 2,
  iconType            = [[t3builder]],
  initCloaked         = false,
  maneuverleashlength = [[1280]],
  mass                = 250,
  maxDamage           = 200,
  maxSlope            = 36,
  maxVelocity         = 8.71,
  metalMake           = 0.15,
  minCloakDistance    = 50,
  noAutoFire          = false,
  noChaseCategory     = [[TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK]],
  objectName          = [[CORCSA]],
  radarDistanceJam    = 300,
  scale               = [[0.8]],
  seismicDistance     = 300,
  seismicSignature    = 0,
  selfDestructAs      = [[GUNSHIPEX]],
  showNanoSpray       = false,
  side                = [[CORE]],
  sightDistance       = 380,
  smoothAnim          = true,
  stealth             = true,
  steeringmode        = [[1]],
  TEDClass            = [[VTOL]],
  terraformSpeed      = 300,
  turnRate            = 132,
  workerTime          = 6,

  featureDefs         = {

    DEAD  = {
      description      = [[Wreckage - Outcast]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 200,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[40]],
      hitdensity       = [[100]],
      metal            = 200,
      object           = [[ARMHAM_DEAD]],
      reclaimable      = true,
      reclaimTime      = 200,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Outcast]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 200,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 200,
      object           = [[debris2x2c.s3o]],
      reclaimable      = true,
      reclaimTime      = 200,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Outcast]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 200,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 100,
      object           = [[debris2x2c.s3o]],
      reclaimable      = true,
      reclaimTime      = 100,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ corcsa = unitDef })
