unitDef = {
  unitname               = [[corclog]],
  name                   = [[Dirtbag]],
  description            = [[Box of Dirt]],
  acceleration           = 0.2,
  amphibious             = [[1]],
  brakeRate              = 0.2,
  buildCostEnergy        = 20,
  buildCostMetal         = 20,
  builder                = false,
  buildPic               = [[corclog.png]],
  buildTime              = 20,
  canAttack              = false,
  canFight               = true,
  canGuard               = true,
  canMove                = true,
  canPatrol              = true,
  canstop                = [[1]],
  category               = [[LAND UNARMED STUPIDTARGET]],
  collisionVolumeOffsets = [[0 0 0]],
  collisionVolumeScales  = [[34 45 27]],
  collisionVolumeTest    = 1,
  collisionVolumeType    = [[box]],

  customParams           = {
    canjump        = [[1]],
    description_bp = [[]],
    description_es = [[Caja de tierra]],
    description_fr = [[]],
    description_it = [[Scatola di terra]],
	description_de = [[Behälter voller Dreck]],
    helptext       = [[The Dirtbag is an unarmed unit whose sole purpose is to die - leaving a mound that obstructs enemy movement, effective against vehicles. It also doubles as an expendable scout.]],
    helptext_bp    = [[]],
    helptext_fr    = [[Le Clogger est une unit? sacrifiable sans armement. Il s'agit en fait d'une fortification anti-tank l?g?re ?quip?e d'un syst?me de propulsion bip?de. Il sert donc autant a rep?rer l'ennemi avec des unit?s de co?t d?risoire qu'a bloquer la progression d'une arm?e.]],
	helptext_de    = [[Der Dirtbag ist eine unbewaffnete Einheit mit der einzigen Absicht zu sterben - dabei hinterlässt er einen Hügel, der feindlichen Bewegung behindert, vor allem gegen Fahrzeuge effektiv. Er fungiert gegebenenfalls auch als entbehrlicher Auklärer.]],
  },

  explodeAs              = [[CLOGGER_EXPLODE]],
  footprintX             = 2,
  footprintZ             = 2,
  iconType               = [[clogger]],
  idleAutoHeal           = 5,
  idleTime               = 1800,
  leaveTracks            = true,
  mass                   = 97,
  maxDamage              = 650,
  maxSlope               = 36,
  maxVelocity            = 2.5,
  maxWaterDepth          = 22,
  minCloakDistance       = 75,
  movementClass          = [[KBOT2]],
  noAutoFire             = false,
  noChaseCategory        = [[TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK TURRET]],
  objectName             = [[clogger.s3o]],
  ovradjust              = [[1]],
  script				 = [[corclog.lua]],
  seismicSignature       = 4,
  selfDestructAs         = [[CLOGGER_EXPLODE]],
  selfDestructCountdown  = 0,
  shootme                = [[1]],
  side                   = [[CORE]],
  sightDistance          = 200,
  smoothAnim             = true,
  trackOffset            = 0,
  trackStrength          = 8,
  trackStretch           = 1,
  trackType              = [[ComTrack]],
  trackWidth             = 22,
  threed                 = [[1]],
  turnRate               = 2000,
  unitnumber             = [[6525]],
  upright                = true,
  version                = [[1]],
  workerTime             = 0,
  zbuffer                = [[1]],

  featureDefs            = {

    DEAD       = {
      description      = [[Debris - Clogger]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 12500,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 1,
      object           = [[debris1x1b.s3o]],
      reclaimable      = true,
      reclaimTime      = 1,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    RockTeeth  = {
      description      = [[Debris - Clogger]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 12500,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 1,
      object           = [[debris1x1b.s3o]],
      reclaimable      = true,
      reclaimTime      = 1,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    SLAB_HEAP1 = {
      description      = [[Debris - Clogger]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 12500,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 1,
      object           = [[debris1x1b.s3o]],
      reclaimable      = true,
      reclaimTime      = 1,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ corclog = unitDef })
