unitDef = {
  unitname            = [[core_egg_shell]],
  name                = [[Dragon's Egg]],
  description         = [[Blockade Runner]],
  acceleration        = 0.04,
  activateWhenBuilt   = false,
  bmcode              = [[1]],
  brakeRate           = 0.02,
  buildCostEnergy     = 400,
  buildCostMetal      = 400,
  builder             = false,
  buildPic            = [[Core_Egg_Shell.png]],
  buildTime           = 400,
  canAttack           = true,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canstop             = [[1]],
  category            = [[LAND FIREPROOF]],
  corpse              = [[DEAD]],

  customParams        = {
    description_bp = [[Corredor de bloqueio]],
    description_fr = [[Forceur de Blocus]],
    fireproof      = [[1]],
    helptext       = [[When closed up, the Dragon's Egg takes 15% damage and moves at half speed. Opens up to fire its close-range flamethrower. Excellent for passing thin defenses, or rushing lightly guarded long range units.]],
    helptext_bp    = [[Quando fechado, o Dragon's Egg recebe só 15% do dano normal e se move a metade da velocidade. Se abre para atirar seu lança-chamas de curto alcançe. Excelente para atravessar defesas finas ou cargar contra unidades de longo alcançe pouco defendidas. Nasçe programado para n?o atirar a menos que receba a ordem, ent?o de uma ordem de ataque direta ou mude a opç?o "hold fire" para "fire at will" para faze-lo abrir-se.]],
    helptext_fr    = [[Le Dragon's Egg est un forceur de blocus. Ce tank au blindage ultra lourd se déplace lentement. Lorsqu'il est fermé il se déplace deux fois plus lentement mais bloque les trois-quart des dégâts. Une fois ouvert sont puissant lance flamme se charge de réduire en cendre les grandes installations ennemies en un clin d'oeuil.]],
  },

  damageModifier      = 0.15,
  defaultmissiontype  = [[guard]],
  designation         = [[CORE-RV8]],
  explodeAs           = [[BIG_UNITEX]],
  fireState           = 0,
  footprintX          = 4,
  footprintZ          = 4,
  iconType            = [[tankassault]],
  leaveTracks         = true,
  maneuverleashlength = [[640]],
  mass                = 200,
  maxDamage           = 2000,
  maxSlope            = 18,
  maxVelocity         = 2.5,
  maxWaterDepth       = 22,
  minCloakDistance    = 75,
  movementClass       = [[TANK4]],
  noAutoFire          = false,
  noChaseCategory     = [[TERRAFORM FIXEDWING SATELLITE GUNSHIP SUB]],
  objectName          = [[core_egg_shell]],
  onoffable           = true,
  seismicSignature    = 4,
  selfDestructAs      = [[BIG_UNITEX]],
  shootme             = [[1]],
  side                = [[CORE]],
  sightDistance       = 400,
  steeringmode        = [[1]],
  TEDClass            = [[TANK]],
  trackOffset         = 8,
  trackStrength       = 9,
  trackStretch        = 1,
  trackType           = [[StdTank]],
  trackWidth          = 45,
  turnRate            = 600,
  workerTime          = 0,
  zbuffer             = [[1]],

  weapons             = {

    {
      def                = [[FLAMETHROWER]],
      badTargetCategory  = [[FIREPROOF]],
      onlyTargetCategory = [[SWIM LAND SINK FLOAT SHIP HOVER GUNSHIP FIXEDWING]],
    },

  },


  weaponDefs          = {

    FLAMETHROWER = {
      name                    = [[fakeflame]],
      areaOfEffect            = 64,
      avoidFeature            = false,
      collideFeature          = false,
      craterBoost             = 0,
      craterMult              = 0,

      damage                  = {
        default = 10,
        planes  = 10,
        subs    = 0.00225,
      },

      explosionGenerator      = [[custom:SMOKE]],
      fireStarter             = 500,
      flameGfxTime            = 1.6,
      impulseBoost            = 0,
      impulseFactor           = 0,
      intensity               = 0.1,
      interceptedByShieldType = 0,
      lineOfSight             = true,
      noExplode               = true,
      noSelfDamage            = true,
      range                   = 280,
      reloadtime              = 0.16,
      renderType              = 5,
      sizeGrowth              = 1.05,
      sprayAngle              = 50000,
      tolerance               = 2500,
      turnRate                = 160000,
      turret                  = true,
      weaponType              = [[Flame]],
      weaponVelocity          = 800,
    },

  },


  featureDefs         = {

    DEAD  = {
      description      = [[Wreckage - Dragon's Egg]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 2000,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[20]],
      hitdensity       = [[100]],
      metal            = 160,
      object           = [[Core_Egg_shell_DEAD]],
      reclaimable      = true,
      reclaimTime      = 160,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Dragon's Egg]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 2000,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      hitdensity       = [[100]],
      metal            = 160,
      object           = [[debris4x4a.s3o]],
      reclaimable      = true,
      reclaimTime      = 160,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Dragon's Egg]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 2000,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      hitdensity       = [[100]],
      metal            = 80,
      object           = [[debris4x4a.s3o]],
      reclaimable      = true,
      reclaimTime      = 80,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ core_egg_shell = unitDef })
