unitDef = {
  unitname            = [[cormabm]],
  name                = [[Hedgehog]],
  description         = [[Mobile Anti-missile Defense]],
  acceleration        = 0.0198,
  activateWhenBuilt   = true,
  antiweapons         = [[1]],
  bmcode              = [[1]],
  brakeRate           = 0.0374,
  buildCostEnergy     = 2500,
  buildCostMetal      = 2500,
  builder             = false,
  buildPic            = [[CORMABM.png]],
  buildTime           = 2500,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canstop             = [[1]],
  category            = [[LAND]],
  corpse              = [[DEAD]],

  customParams        = {
    description_bp = [[Defesa anti-mísseis anfíbia]],
    description_fr = [[Défense Mobile Anti-Missile Amphibie]],
    helptext       = [[The Hedgehog is a mobile antinuke platform, capable of intercepting enemy nuclear missiles within a small radius.]],
    helptext_bp    = [[Hedgehog é uma plataforma anti-mísseis atômicos móvel, capaz de interceptar mísseis nucleares inimigos dentro de um curto alcançe.]],
    helptext_fr    = [[Le Hedgehog est un systcme de contre mesure anti-nucléaires mobile. Capable de se cacher dans de nombreux endroit y compris sous l'eau, il ne sera cependant pas opérationnel si il ne peux déployer ses tubes de lancement r la surface.]],
  },

  damageModifier      = 0.5,
  defaultmissiontype  = [[Standby]],
  explodeAs           = [[LARGE_BUILDINGEX]],
  footprintX          = 2,
  footprintZ          = 2,
  iconType            = [[tankantinuke]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  leaveTracks         = true,
  maneuverleashlength = [[640]],
  mass                = 1250,
  maxDamage           = 1500,
  maxSlope            = 36,
  maxVelocity         = 2.1,
  maxWaterDepth       = 5000,
  minCloakDistance    = 75,
  movementClass       = [[AKBOT2]],
  moveState           = 0,
  objectName          = [[CORMABM]],
  radarDistance       = 1000,
  seismicSignature    = 4,
  selfDestructAs      = [[LARGE_BUILDINGEX]],
  side                = [[CORE]],
  sightDistance       = 660,
  smoothAnim          = true,
  steeringmode        = [[1]],
  TEDClass            = [[TANK]],
  trackOffset         = 6,
  trackStrength       = 5,
  trackStretch        = 1,
  trackType           = [[StdTank]],
  trackWidth          = 34,
  turninplace         = 0,
  turnRate            = 520.3,
  workerTime          = 0,

  weapons             = {

    {
      def = [[CORMABM_WEAPON]],
    },

  },


  weaponDefs          = {

    CORMABM_WEAPON = {
      name                    = [[Anti-Nuke Missile]],
      areaOfEffect            = 96,
      collideFriendly         = false,
      coverage                = 1000,
      craterBoost             = 1,
      craterMult              = 2,

      damage                  = {
        default = 500,
        subs    = 25,
      },

      explosionGenerator      = [[custom:ANTINUKE]],
      fireStarter             = 100,
      flighttime              = 100,
      guidance                = true,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 1,
      interceptor             = 1,
      lineOfSight             = true,
      model                   = [[fmdmisl]],
      noautorange             = [[1]],
      noSelfDamage            = true,
      range                   = 3000,
      reloadtime              = 12,
      renderType              = 1,
      selfprop                = true,
      smokedelay              = [[0.1]],
      smokeTrail              = true,
      soundHit                = [[OTAunit/XPLOMED4]],
      soundStart              = [[OTAunit/ROCKHVY1]],
      startsmoke              = [[1]],
      startVelocity           = 400,
      tolerance               = 4000,
      tracks                  = true,
      turnrate                = 65535,
      twoPhase                = true,
      vlaunch                 = true,
      weaponAcceleration      = 400,
      weaponTimer             = 0.2,
      weaponType              = [[StarburstLauncher]],
      weaponVelocity          = 1300,
    },

  },


  featureDefs         = {

    DEAD  = {
      description      = [[Wreckage - Hedgehog]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 1500,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[20]],
      hitdensity       = [[100]],
      metal            = 1000,
      object           = [[CORMABM_DEAD]],
      reclaimable      = true,
      reclaimTime      = 1000,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Hedgehog]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 1500,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 1000,
      object           = [[debris3x3b.s3o]],
      reclaimable      = true,
      reclaimTime      = 1000,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Hedgehog]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 1500,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 500,
      object           = [[debris3x3b.s3o]],
      reclaimable      = true,
      reclaimTime      = 500,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ cormabm = unitDef })
