unitDef = {
  unitname          = [[cortide]],
  name              = [[Tidal Generator]],
  description       = [[Produces Energy]],
  acceleration      = 0,
  activateWhenBuilt = true,
  bmcode            = [[0]],
  brakeRate         = 0,
  buildAngle        = 4096,
  buildCostEnergy   = 55,
  buildCostMetal    = 55,
  builder           = false,
  buildPic          = [[CORTIDE.png]],
  buildTime         = 55,
  category          = [[UNARMED FLOAT]],
  corpse            = [[DEAD]],

  customParams      = {
    pylonrange = 70,
  },

  energyUse         = 0,
  explodeAs         = [[SMALL_BUILDINGEX]],
  footprintX        = 3,
  footprintZ        = 3,
  iconType          = [[energy1]],
  idleAutoHeal      = 5,
  idleTime          = 1800,
  mass              = 27.5,
  maxDamage         = 260,
  maxSlope          = 18,
  maxVelocity       = 0,
  minCloakDistance  = 150,
  minWaterDepth     = 20,
  noAutoFire        = false,
  objectName        = [[CORTIDE]],
  onoffable         = true,
  seismicSignature  = 4,
  selfDestructAs    = [[SMALL_BUILDINGEX]],
  side              = [[CORE]],
  sightDistance     = 273,
  smoothAnim        = true,
  TEDClass          = [[WATER]],
  tidalGenerator    = 0.1,
  turnRate          = 0,
  waterline         = 10,
  workerTime        = 0,
  yardMap           = [[wwwwwwwww]],

  featureDefs       = {

    DEAD  = {
      description      = [[Wreckage - Tidal Generator]],
      blocking         = false,
      category         = [[corpses]],
      damage           = 260,
      energy           = 0,
      featureDead      = [[DEAD2]],
      footprintX       = 4,
      footprintZ       = 4,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 22,
      object           = [[CORTIDE_DEAD]],
      reclaimable      = true,
      reclaimTime      = 22,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Tidal Generator]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 260,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 4,
      footprintZ       = 4,
      hitdensity       = [[100]],
      metal            = 22,
      object           = [[debris4x4c.s3o]],
      reclaimable      = true,
      reclaimTime      = 22,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Tidal Generator]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 260,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 4,
      footprintZ       = 4,
      hitdensity       = [[100]],
      metal            = 11,
      object           = [[debris4x4c.s3o]],
      reclaimable      = true,
      reclaimTime      = 11,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ cortide = unitDef })
