unitDef = {
  unitname               = [[corvamp]],
  name                   = [[Hawk]],
  description            = [[Air Superiority Fighter]],
  amphibious             = true,
  buildCostEnergy        = 300,
  buildCostMetal         = 300,
  buildPic               = [[corvamp.png]],
  buildTime              = 300,
  canAttack              = true,
  canDropFlare           = false,
  canFly                 = true,
  canGuard               = true,
  canMove                = true,
  canPatrol              = true,
  canstop                = [[1]],
  canSubmerge            = false,
  category               = [[FIXEDWING]],
  collide                = false,
  collisionVolumeOffsets = [[0 0 5]],
  collisionVolumeScales  = [[30 12 50]],
  collisionVolumeTest    = 1,
  collisionVolumeType    = [[box]],
  corpse                 = [[DEAD]],
  crashDrag              = 0.01,
  cruiseAlt              = 220,

  customParams           = {
    description_bp = [[Caça de superioridade aérea invisível a radar]],
    description_fr = [[Chasseur Anti-Air Sup?rieur]],
	description_de = [[Luftüberlegenheitsjäger]],
	description_pl = [[Mysliwiec]],
    helptext       = [[The Hawk specializes in bringing down anything else that flies. It is sturdy enough to take limited AA fire, although it has no ground attack capability.]],
    helptext_bp    = [[Hawk é um caça poderoso contra unidades aéreas mas incapaz de atacar unidades terrestres.]],
    helptext_fr    = [[le Hawk combine, vitesse, invisibilit? au radar, et puissante force offensive Air/Air, afin d'abatre les aeronefs ennemis. Sans d?fense contre les attaques Sol/Air.]],
	helptext_de    = [[Der Hawk ist darauf spezialisiert, alles vom Himmel zu holen, was dort umherfliegt. Er ist stabil genung, um begrenztes Flugabwehrfeuer auszuhalten, obwohl er keine Möglichkeit zum Angriff auf Bodenziele besitzt.]],
	helptext_pl    = [[Hawk to ciezki mysliwiec, ktory jest przeznaczony do niszczenia wszystkiego, co lata. Jest dosc wytrzymaly, jednak nie jest w stanie atakowac celow naziemnych.]],
    midposoffset   = [[0 3 0]],
    aimposoffset   = [[0 3 0]],
	modelradius    = [[10]],
	refuelturnradius = [[120]],

	combat_slowdown = 0.5,
	selection_scale = 1.4,
  },

  explodeAs              = [[GUNSHIPEX]],
  fireState              = 2,
  floater                = true,
  footprintX             = 2,
  footprintZ             = 2,
  frontToSpeed           = 0.1,
  iconType               = [[stealthfighter]],
  idleAutoHeal           = 5,
  idleTime               = 1800,
  mass                   = 187,
  maxAcc                 = 0.5,
  maxDamage              = 1000,
  maxVelocity            = 7.6,
  minCloakDistance       = 75,
  mygravity              = 1,
  noChaseCategory        = [[TERRAFORM LAND SINK TURRET SHIP SWIM FLOAT SUB HOVER]],
  objectName             = [[fighter2.s3o]],
  power                  = 100,
  script                 = [[corvamp.lua]],
  seismicSignature       = 0,
  selfDestructAs         = [[GUNSHIPEX]],
  side                   = [[CORE]],
  sightDistance          = 750,
  smoothAnim             = true,
  speedToFront           = 0.5,
  turnRadius             = 400,

  weapons                = {

    {
      def                = [[LASER]],
      badTargetCategory  = [[GUNSHIP]],
      mainDir            = [[0 0 1]],
      maxAngleDif        = 90,
      onlyTargetCategory = [[FIXEDWING GUNSHIP]],
    },

  },


  weaponDefs             = {

    LASER = {
      name                    = [[Anti-Air Laser Battery]],
      areaOfEffect            = 12,
      avoidFriendly           = false,
      beamDecay               = 0.736,
      beamTime                = 0.01,
      beamttl                 = 15,
      canattackground         = false,
      canAttackGround         = 0,
      collideFriendly         = false,
      coreThickness           = 0.5,
      craterBoost             = 0,
      craterMult              = 0,
      cylinderTargeting       = 1,

	  customParams        	  = {
		isaa = [[1]],
	  },

      damage                  = {
        default = 0.96,
        planes  = 9.6,
        subs    = 0.96,
      },

      explosionGenerator      = [[custom:flash_teal7]],
      fireStarter             = 100,
      impactOnly              = true,
      impulseFactor           = 0,
      interceptedByShieldType = 1,
      laserFlareSize          = 2.9,
      minIntensity            = 1,
      range                   = 800,
      reloadtime              = 0.1,
      rgbColor                = [[0 1 1]],
      soundStart              = [[weapon/laser/rapid_laser]],
      soundStartVolume        = 2.2,
      thickness               = 1.95,
      tolerance               = 8192,
      turret                  = true,
      weaponType              = [[BeamLaser]],
      weaponVelocity          = 2200,
    },

  },


  featureDefs            = {

    DEAD = {
      description      = [[Wreckage - Hawk]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 1000,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[40]],
      hitdensity       = [[100]],
      metal            = 120,
      object           = [[fighter2_dead.s3o]],
      reclaimable      = true,
      reclaimTime      = 120,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP = {
      description      = [[Debris - Hawk]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 1000,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 60,
      object           = [[debris2x2b.s3o]],
      reclaimable      = true,
      reclaimTime      = 60,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ corvamp = unitDef })
