unitDef = {
  unitname            = [[corvoyr]],
  name                = [[Voyeur]],
  description         = [[Radar Bot]],
  acceleration        = 0.049,
  activateWhenBuilt   = true,
  bmcode              = [[1]],
  brakeRate           = 0.015,
  buildCostEnergy     = 100,
  buildCostMetal      = 100,
  builder             = false,
  buildPic            = [[CORVOYR.png]],
  buildTime           = 100,
  canAttack           = false,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canstop             = [[1]],
  category            = [[LAND UNARMED]],
  corpse              = [[DEAD]],

  customParams        = {
    description_bp = [[Robô radar]],
    description_fr = [[Robot Radar]],
    helptext       = [[Voyeur provides radar coverage on the battlefield.]],
    helptext_bp    = [[]],
    helptext_fr    = [[Le Voyeur est un robot sans défense et peu maniable, mais l'information est capitale dans la guerre. Son radar longue portée vous évitera par exemple de foncer sur l'endroit le plus défendu pour attaquer.]],
  },

  defaultmissiontype  = [[Standby]],
  energyUse           = 1.5,
  explodeAs           = [[BIG_UNITEX]],
  footprintX          = 2,
  footprintZ          = 2,
  iconType            = [[kbotradar]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  maneuverleashlength = [[640]],
  mass                = 50,
  maxDamage           = 350,
  maxSlope            = 36,
  maxVelocity         = 2.3,
  maxWaterDepth       = 22,
  minCloakDistance    = 75,
  movementClass       = [[KBOT2]],
  moveState           = 0,
  noAutoFire          = false,
  noChaseCategory     = [[TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK]],
  objectName          = [[CORVOYR]],
  onoffable           = true,
  radarDistance       = 1800,
  seismicSignature    = 4,
  selfDestructAs      = [[BIG_UNITEX]],
  side                = [[CORE]],
  sightDistance       = 800,
  smoothAnim          = true,
  sonarDistance       = 600,
  steeringmode        = [[1]],
  TEDClass            = [[KBOT]],
  turnRate            = 583,
  workerTime          = 0,

  featureDefs         = {

    DEAD  = {
      description      = [[Wreckage - Voyeur]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 350,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[20]],
      hitdensity       = [[100]],
      metal            = 40,
      object           = [[CORVOYR_DEAD]],
      reclaimable      = true,
      reclaimTime      = 40,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Voyeur]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 350,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 40,
      object           = [[debris2x2a.s3o]],
      reclaimable      = true,
      reclaimTime      = 40,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Voyeur]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 350,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 20,
      object           = [[debris2x2a.s3o]],
      reclaimable      = true,
      reclaimTime      = 20,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ corvoyr = unitDef })
