unitDef = {
  unitname         = [[factoryhover]],
  name             = [[Amphibious Operations Platform]],
  description      = [[Produces Hovercraft and Amphibious units, Builds at 6 m/s]],
  acceleration     = 0,
  bmcode           = [[0]],
  brakeRate        = 0,
  buildCostEnergy  = 550,
  buildCostMetal   = 550,
  builder          = true,

  buildoptions     = {
    [[corch]],
    [[corsh]],
    [[nsaclash]],
    [[hoverassault]],
    [[hoverriot]],
    [[hoveraa]],
    [[armmanni]],
  },

  buildPic         = [[factoryhover.png]],
  buildTime        = 550,
  canMove          = true,
  canPatrol        = true,
  canstop          = [[1]],
  category         = [[UNARMED FLOAT]],
  corpse           = [[DEAD]],

  customParams     = {
    helptext = [[The Amphibious Operations Platform is fast and deadly, offering the ability to cross sea and plains alike and outmaneuver the enemy. Key units: Halberd, Mace, Penetrator]],
    sortName = [[8]],
  },

  energyMake       = 0.225,
  energyUse        = 0,
  explodeAs        = [[LARGE_BUILDINGEX]],
  footprintX       = 6,
  footprintZ       = 6,
  iconType         = [[fachover]],
  idleAutoHeal     = 5,
  idleTime         = 1800,
  mass             = 275,
  maxDamage        = 4000,
  maxSlope         = 15,
  maxVelocity      = 0,
  metalMake        = 0.225,
  minCloakDistance = 150,
  noAutoFire       = false,
  objectName       = [[ARMFHP.s3o]],
  seismicSignature = 4,
  selfDestructAs   = [[LARGE_BUILDINGEX]],
  showNanoSpray    = false,
  side             = [[ARM]],
  sightDistance    = 273,
  smoothAnim       = true,
  TEDClass         = [[PLANT]],
  turnRate         = 0,
  waterline        = 1,
  workerTime       = 6,
  yardMap          = [[occccooccccooccccooccccooccccoocccco]],

  featureDefs      = {

    DEAD  = {
      description      = [[Wreckage - Amphibious Operations Platform]],
      blocking         = false,
      category         = [[corpses]],
      damage           = 4000,
      energy           = 0,
      featureDead      = [[DEAD2]],
      footprintX       = 8,
      footprintZ       = 7,
      height           = [[20]],
      hitdensity       = [[100]],
      metal            = 220,
      object           = [[ARMFHP_DEAD.s3o]],
      reclaimable      = true,
      reclaimTime      = 220,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Amphibious Operations Platform]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 4000,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 8,
      footprintZ       = 7,
      hitdensity       = [[100]],
      metal            = 220,
      object           = [[debris4x4c.s3o]],
      reclaimable      = true,
      reclaimTime      = 220,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Amphibious Operations Platform]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 4000,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 8,
      footprintZ       = 7,
      hitdensity       = [[100]],
      metal            = 110,
      object           = [[debris4x4c.s3o]],
      reclaimable      = true,
      reclaimTime      = 110,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ factoryhover = unitDef })
