unitDef = {
  unitname                      = [[kettle]],
  name                          = [[Kettle]],
  description                   = [[Geothermal Plant - produces energy (80)]],
  acceleration                  = 0,
  activateWhenBuilt             = true,
  bmcode                        = [[0]],
  brakeRate                     = 0,
  buildAngle                    = 8192,
  buildCostEnergy               = 1500,
  buildCostMetal                = 1500,
  builder                       = false,
  buildingGroundDecalDecaySpeed = 30,
  buildingGroundDecalSizeX      = 8,
  buildingGroundDecalSizeY      = 8,
  buildingGroundDecalType       = [[kettle_aoplane.dds]],
  buildPic                      = [[kettle.png]],
  buildTime                     = 1500,
  canAttack                     = true,
  canstop                       = [[1]],
  category                      = [[SINK]],
  corpse                        = [[DEAD]],
  defaultmissiontype            = [[GUARD_NOMOVE]],
  energyUse                     = -80,
  explodeAs                     = [[LARGE_BUILDINGEX]],
  footprintX                    = 5,
  footprintZ                    = 5,
  iconType                      = [[defense]],
  idleAutoHeal                  = 5,
  idleTime                      = 1800,
  mass                          = 750,
  maxDamage                     = 8000,
  maxSlope                      = 255,
  maxVelocity                   = 0,
  maxWaterDepth                 = 0,
  minCloakDistance              = 150,
  noAutoFire                    = false,
  noChaseCategory               = [[FIXEDWING LAND SHIP SATELLITE SWIM GUNSHIP SUB HOVER]],
  objectName                    = [[CORBHMTH]],
  onoffable                     = false,
  seismicSignature              = 4,
  selfDestructAs                = [[LARGE_BUILDINGEX]],
  side                          = [[CORE]],
  sightDistance                 = 660,
  smoothAnim                    = true,
  TEDClass                      = [[FORT]],
  turnRate                      = 0,
  useBuildingGroundDecal        = true,
  workerTime                    = 0,
  yardMap                       = [[ooooo ooooo ooGoo ooooo ooooo]],

  weapons                       = {

    {
      def                = [[FLAMETHROWER2]],
      badTargetCategory  = [[FIREPROOF]],
      onlyTargetCategory = [[SWIM LAND SINK FLOAT SHIP HOVER]],
    },

  },


  weaponDefs                    = {

    FLAMETHROWER2 = {
      name                    = [[FlameThrower2]],
      areaOfEffect            = 64,
      avoidFeature            = false,
      burst                   = 3,
      burstRate               = 0.1,
      collideFeature          = false,
      craterBoost             = 0,
      craterMult              = 0,

      damage                  = {
        default       = 5,
        flamethrowers = 0.6,
        planes        = 5,
        subs          = 0.0025,
      },

      explosionGenerator      = [[custom:SMOKE2]],
      flameGfxTime            = 2.6,
      impulseBoost            = 0,
      impulseFactor           = 0,
      intensity               = 0.9,
      interceptedByShieldType = 1,
      lineOfSight             = true,
      noExplode               = true,
      noSelfDamage            = true,
      projectiles             = 3,
      range                   = 400,
      reloadtime              = 0.05,
      renderType              = 5,
      sizeGrowth              = 1.9,
      soundStart              = [[steam3.wav]],
      soundTrigger            = false,
      sprayAngle              = 20000,
      texture1                = [[steam]],
      tolerance               = 4000,
      turret                  = true,
      weaponType              = [[Flame]],
      weaponVelocity          = 280,
    },

  },


  featureDefs                   = {

    DEAD  = {
      description      = [[Wreckage - Kettle]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 8000,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 5,
      footprintZ       = 5,
      height           = [[20]],
      hitdensity       = [[100]],
      metal            = 600,
      object           = [[CORBHMTH_DEAD]],
      reclaimable      = true,
      reclaimTime      = 600,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Kettle]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 8000,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 5,
      footprintZ       = 5,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 600,
      object           = [[debris4x4b.s3o]],
      reclaimable      = true,
      reclaimTime      = 600,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Kettle]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 8000,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 5,
      footprintZ       = 5,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 300,
      object           = [[debris4x4b.s3o]],
      reclaimable      = true,
      reclaimTime      = 300,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ kettle = unitDef })
