unitDef = {
  unitname              = [[logareamine]],
  name                  = [[Demo]],
  description           = [[Napalm Cluster Trap Mine]],
  acceleration          = 0,
  activateWhenBuilt     = true,
  bmcode                = [[0]],
  brakeRate             = 0,
  buildCostEnergy       = 100,
  buildCostMetal        = 100,
  builder               = false,
  buildPic              = [[logareamine.png]],
  buildTime             = 100,
  canAttack             = false,
  canGuard              = false,
  canMove               = false,
  canPatrol             = false,
  canstop               = [[0]],
  category              = [[FLOAT FIREPROOF]],
  cloakCost             = 0,
  collide               = true,
  collisionVolumeScales = [[16 16 16]],
  collisionVolumeTest   = 1,
  collisionVolumeType   = [[Sphere]],

  customParams          = {
    dontCount      = [[1]],
    fireproof      = [[1]],
    helptext       = [[A powerful napalm charge, very effective against raiders.]],
    mobilebuilding = [[1]],
  },

  defaultmissiontype    = [[Standby_Mine]],
  explodeAs             = [[MINE_LOGOS_AREA_NAPALM]],
  footprintX            = 1,
  footprintZ            = 1,
  iconType              = [[mine]],
  idleAutoHeal          = 25,
  idleTime              = 100,
  initCloaked           = true,
  kamikaze              = true,
  kamikazeDistance      = 160,
  levelGround           = 0,
  mass                  = 2.5,
  maxDamage             = 300,
  maxSlope              = 255,
  maxVelocity           = 0,
  minCloakDistance      = 50,
  noAutoFire            = true,
  noChaseCategory       = [[FIXEDWING LAND SINK SHIP SATELLITE SWIM GUNSHIP FLOAT SUB HOVER]],
  objectName            = [[logmine.s3o]],
  onoffable             = false,
  seismicDistance       = 80,
  seismicSignature      = 16,
  selfDestructAs        = [[MINE_LOGOS_AREA_NAPALM]],
  selfDestructCountdown = 0,
  side                  = [[CORE]],
  sightDistance         = 100,
  smoothAnim            = true,
  sonarDistanceJam      = 16,
  stealth               = true,
  TEDClass              = [[SPECIAL]],
  turnRate              = 0,
  waterline             = 1,
  workerTime            = 0,
  yardMap               = [[o]],

  weapons               = {

    {
      def                = [[NAPALM_CLUSTERS]],
      mainDir            = [[0, 1, 0]],
      maxAngleDif        = 200,
      onlyTargetCategory = [[NONE]],
    },

  },


  weaponDefs            = {

    NAPALM_CLUSTERS = {
      name                    = [[Napalm Clusters Detonation]],
      areaOfEffect            = 155,
      craterBoost             = 0.7,
      craterMult              = 0.4,

      damage                  = {
        default = 30,
        subs    = 5,
      },

      edgeEffectiveness       = 0.2,
      explosionGenerator      = [[custom:NAPALM_Expl]],
      fireStarter             = 360,
      FixedLauncher           = true,
      flameGfxTime            = 0.3,
      flightTime              = 0.5,
      impulseBoost            = 0.7,
      impulseFactor           = 1.2,
      interceptedByShieldType = 2,
      lineOfSight             = true,
      model                   = [[bomb]],
      myGravity               = 0.5,
      noSelfDamage            = true,
      range                   = 180,
      reloadtime              = 1,
      renderType              = 4,
      smokeTrail              = true,
      soundHit                = [[OTAunit/XPLOSML2]],
      soundHitVolume          = 8,
      soundStart              = [[openQuarz/sattck1]],
      soundStartVolume        = 2,
      sprayangle              = 650,
      startsmoke              = [[1]],
      startVelocity           = 95,
      tolerance               = 9999,
      turret                  = true,
      weaponAcceleration      = 75,
      weaponTimer             = 3,
      weaponType              = [[MissileLauncher]],
      weaponVelocity          = 160,
    },

  },

}

return lowerkeys({ logareamine = unitDef })
