unitDef = {
  unitname              = [[novareamine]],
  name                  = [[Hoplite]],
  description           = [[Cluster Pipebomb Trap Mine]],
  acceleration          = 0,
  activateWhenBuilt     = true,
  bmcode                = [[0]],
  brakeRate             = 0,
  buildCostEnergy       = 80,
  buildCostMetal        = 80,
  builder               = false,
  buildPic              = [[novareamine.png]],
  buildTime             = 80,
  canAttack             = false,
  canGuard              = false,
  canMove               = false,
  canPatrol             = false,
  canstop               = [[0]],
  category              = [[FLOAT]],
  cloakCost             = 0,
  collide               = true,
  collisionVolumeScales = [[16 16 16]],
  collisionVolumeTest   = 1,
  collisionVolumeType   = [[Sphere]],

  customParams          = {
    dontCount      = [[1]],
    helptext       = [[An anti-raider mine that jumps up and saturates the immediate area with deadly pipepombs.]],
    mobilebuilding = [[1]],
  },

  defaultmissiontype    = [[Standby_Mine]],
  explodeAs             = [[MINE_NOVA_AREA]],
  footprintX            = 1,
  footprintZ            = 1,
  iconType              = [[mine]],
  idleAutoHeal          = 25,
  idleTime              = 100,
  initCloaked           = true,
  kamikaze              = true,
  kamikazeDistance      = 120,
  levelGround           = 0,
  mass                  = 3,
  maxDamage             = 320,
  maxSlope              = 255,
  maxVelocity           = 0,
  minCloakDistance      = 110,
  noAutoFire            = true,
  noChaseCategory       = [[FIXEDWING LAND SINK SHIP SATELLITE SWIM GUNSHIP FLOAT SUB HOVER]],
  objectName            = [[novmine.s3o]],
  onoffable             = false,
  seismicDistance       = 80,
  seismicSignature      = 16,
  selfDestructAs        = [[MINE_NOVA_AREA]],
  selfDestructCountdown = 0,
  side                  = [[ARM]],
  sightDistance         = 100,
  smoothAnim            = true,
  sonarDistanceJam      = 16,
  stealth               = true,
  TEDClass              = [[SPECIAL]],
  turnRate              = 0,
  waterline             = 1,
  workerTime            = 0,
  yardMap               = [[oo oo]],

  weapons               = {

    {
      def                = [[BOUNCY_ROCKETS]],
      mainDir            = [[0, -1, 0]],
      maxAngleDif        = 20,
      onlyTargetCategory = [[NONE]],
    },

  },


  weaponDefs            = {

    BOUNCY_ROCKETS = {
      name                    = [[ROCKETS detonation]],
      areaOfEffect            = 140,
      bouncerebound           = 0.37,
      bounceslip              = 0.65,
      craterBoost             = 1.2,
      craterMult              = 1,

      damage                  = {
        default = 63,
        subs    = 5,
      },

      edgeEffectiveness       = 0.01,
      explosionGenerator      = [[custom:WEAPEXP_PUFF]],
      fireStarter             = 70,
      FixedLauncher           = true,
      flightTime              = 0.1,
      gravityAffected         = true,
      groundbounce            = 1,
      guidance                = true,
      impulseBoost            = 0.85,
      impulseFactor           = 0.5,
      interceptedByShieldType = 2,
      lineOfSight             = true,
      model                   = [[wep_b_fabby.s3o]],
      myGravity               = 0.35,
      noSelfDamage            = true,
      numbounce               = 3,
      range                   = 200,
      reloadtime              = 1,
      renderType              = 1,
      selfprop                = true,
      smokeTrail              = false,
      soundHit                = [[OTAunit/XPLOSML2]],
      soundHitVolume          = 2,
      soundStart              = [[bzflag/fire]],
      soundStartVolume        = 1,
      sprayangle              = 35000,
      startsmoke              = [[1]],
      startVelocity           = 120,
      tolerance               = 0,
      turret                  = true,
      weaponAcceleration      = 55,
      weaponTimer             = 2,
      weaponType              = [[MissileLauncher]],
      weaponVelocity          = 180,
    },

  },

}

return lowerkeys({ novareamine = unitDef })
