return { obj_artefact = {
  name                          = [[Ancient Artefact]],
  description                   = [[Capture artefacts by destroying them. Control all artefacts to win.]],
  activateWhenBuilt             = true,
  autoHeal                      = 100,
  builder                       = false,
  canSelfDestruct               = false,
  category                      = [[SINK UNARMED STUPIDTARGET]],
  collisionVolumeOffsets        = [[0 -15 0]],
  collisionVolumeScales         = [[80 110 80]],
  collisionVolumeType           = [[CylY]],
  selectionVolumeOffsets        = [[0 -15 0]],
  selectionVolumeScales         = [[100 110 100]],
  selectionVolumeType           = [[CylY]],

  customParams                  = {
    removewait = 1,
    removestop = 1,
    midposoffset   = [[0 25 0]],
    soundselect = "cloaker_select",
    rescale_factor = 1.4,
    no_xp = 1,
    bait_level_target = 1,
    very_low_priority_target = 1,
  },

  explodeAs                     = [[ESTOR_BUILDINGEX]],
  floater                       = true,
  footprintX                    = 7,
  footprintZ                    = 7,
  health                        = 11000,
  levelGround                   = false,
  iconType                      = [[mahlazer_special]],
  maxSlope                      = 24,
  metalCost                     = 1000,
  noAutoFire                    = false,
  objectName                    = [[pw_artefact.dae]],
  reclaimable                   = false,
  script                        = [[obj_artefact.lua]],
  selfDestructAs                = [[ESTOR_BUILDINGEX]],
  selfDestructCountdown         = 9001,
  sightDistance                 = 273,
  useBuildingGroundDecal        = false,
  workerTime                    = 0,

  featureDefs                   = {
  },

} }
