unitDef = {
  unitname            = [[owl]],
  name                = [[Owl]],
  description         = [[High-Altitude Spy Drone]],
  acceleration        = 0.01,
  activateWhenBuilt   = true,
  amphibious          = true,
  bankscale           = [[0.5]],
  bmcode              = [[1]],
  brakeRate           = 3.75,
  buildCostEnergy     = 300,
  buildCostMetal      = 300,
  builder             = false,
  buildPic            = [[owl.png]],
  buildTime           = 300,
  canAttack           = true,
  CanDropFlare        = 1,
  canFly              = true,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canstop             = [[1]],
  canSubmerge         = false,
  category            = [[UNARMED SATELLITE]],
  collide             = false,
  cruiseAlt           = 1200,

  customParams        = {
    description_bp = [[Dróide espi?o]],
    description_fr = [[Drône Espion de Haute Altitude]],
    helptext       = [[This stealthy orb can serve as a spotter for your artillery or spy on an opponent's base. It uses a lot of energy to stay in the air but is safe from nearly all units. Vulnerable to advanced fighterplanes and long range missile towers.]],
    helptext_bp    = [[Essa esfera invisível a radar pode ser usada para achar alvos para sua artilharia ou simplesmente espiar o inimigo. Usa energia para manter-se no ar mais está a salvo da maioria das unidades. Pode ser abatido por torres de mísseis de longo alcançe ou caças de superioridade aérea.]],
    helptext_fr    = [[Le Owl est un drône furtif de trcs haute altitude. Il se déplace lentement et ne renseigne que sur des zones trcs précies et donc peu large. Il est cependant difficile de l'abattre, seules les meilleures défenses et les meilleurs avions Anti-Air sont dangereux pour eux.]],
  },

  defaultmissiontype  = [[VTOL_standby]],
  explodeAs           = [[SMALL_UNITEX]],
  FlareDelay          = 0.3,
  FlareDropVector     = [[0 0 -1]],
  FlareEfficiency     = 0.3,
  FlareReload         = 5,
  floater             = true,
  footprintX          = 4,
  footprintZ          = 4,
  hoverAttack         = true,
  iconType            = [[scoutplane]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  maneuverleashlength = [[500]],
  mass                = 150,
  maxDamage           = 400,
  maxVelocity         = 1,
  minCloakDistance    = 75,
  noAutoFire          = true,
  noChaseCategory     = [[TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK]],
  objectName          = [[owl.s3o]],
  scale               = [[1]],
  seismicSignature    = 0,
  selfDestructAs      = [[SMALL_UNITEX]],
  side                = [[CORE]],
  sightDistance       = 300,
  smoothAnim          = true,
  stealth             = true,
  steeringmode        = [[1]],
  TEDClass            = [[VTOL]],
  turnRate            = 297,
  upright             = true,
  workerTime          = 0,

  weapons             = {
  },


  weaponDefs          = {
  },

}

return lowerkeys({ owl = unitDef })
