return { plateamph = {
  unitname                      = [[plateamph]],
  name                          = [[Amphbot Plate]],
  description                   = [[Augments Production]],
  buildCostMetal                = Shared.FACTORY_PLATE_COST,
  builder                       = true,
  buildingGroundDecalDecaySpeed = 30,
  buildingGroundDecalSizeX      = 10,
  buildingGroundDecalSizeY      = 10,
  buildingGroundDecalType       = [[pad_decal.dds]],

  buildoptions     = {
    [[amphcon]],
    [[amphraid]],
    [[amphimpulse]],
    [[amphfloater]],
    [[amphriot]],
    [[amphassault]],
    [[amphlaunch]],
    [[amphaa]],
    [[amphbomb]],
    [[amphtele]],
  },

  buildPic                      = [[plateamph.png]],
  canMove                       = true,
  canPatrol                     = true,
  category                      = [[UNARMED SINK]],
  collisionVolumeOffsets        = [[0 0 -16]],
  collisionVolumeScales         = [[104 70 36]],
  collisionVolumeType           = [[box]],
  selectionVolumeOffsets        = [[0 0 14]],
  selectionVolumeScales         = [[104 70 96]],
  selectionVolumeType           = [[box]],
  corpse                        = [[DEAD]],

  customParams                  = {
    modelradius        = [[100]],
    aimposoffset       = [[0 0 -26]],
    midposoffset       = [[0 0 -10]],
    sortName           = [[8]],
    solid_factory      = [[3]],
    default_spacing    = 4,
    unstick_help       = 1,
    selectionscalemult = 1,
    child_of_factory   = [[factoryamph]],
    cus_noflashlight   = 1,
  },

  energyUse                     = 0,
  explodeAs                     = [[FAC_PLATEEX]],
  footprintX                    = 5,
  footprintZ                    = 7,
  iconType                      = [[padamph]],
  idleAutoHeal                  = 5,
  idleTime                      = 1800,
  maxDamage                     = Shared.FACTORY_PLATE_HEALTH,
  maxSlope                      = 15,
  minCloakDistance              = 150,
  moveState                     = 1,
  noAutoFire                    = false,
  objectName                    = [[plate_amph.s3o]],
  script                        = "plateamph.lua",
  selfDestructAs                = [[FAC_PLATEEX]],
  showNanoSpray                 = false,
  sightDistance                 = 273,
  useBuildingGroundDecal        = true,
  workerTime                    = Shared.FACTORY_BUILDPOWER,
  yardMap                       = [[ooooo ooooo ooooo yyyyy yyyyy yyyyy yyyyy]],

  featureDefs      = {

    DEAD  = {
      blocking         = true,
      featureDead      = [[HEAP]],
      footprintX       = 5,
      footprintZ       = 7,
      object           = [[plate_amph_dead.s3o]],
      collisionVolumeOffsets = [[0 0 -16]],
      collisionVolumeScales  = [[104 70 36]],
      collisionVolumeType    = [[box]],
    },

    HEAP  = {
      blocking         = false,
      footprintX       = 5,
      footprintZ       = 7,
      object           = [[debris4x4c.s3o]],
    },

  },

} }
