unitDef = {
  unitname                      = [[raveparty]],
  name                          = [[Disco Rave Party]],
  description                   = [[Rainbow Surprise Superweapon - On to Randomize]],
  acceleration                  = 0,
  brakeRate                     = 0,
  buildAngle                    = 32700,
  buildCostEnergy               = 40000,
  buildCostMetal                = 40000,
  builder                       = false,
  buildingGroundDecalDecaySpeed = 30,
  buildingGroundDecalSizeX      = 6,
  buildingGroundDecalSizeY      = 6,
  buildingGroundDecalType       = [[armbrtha_aoplane.dds]],
  buildPic                      = [[raveparty.png]],
  buildTime                     = 40000,
  canAttack                     = true,
  canstop                       = [[1]],
  category                      = [[SINK]],
  collisionVolumeOffsets        = [[0 0 0]],
  collisionVolumeScales         = [[70 194 70]],
  collisionVolumeTest           = 1,
  collisionVolumeType           = [[cylY]],
  corpse                        = [[DEAD]],

  customParams                  = {
    helptext       = [[The Disco Rave Party throws six different party shots at your enemy for a different surprise each time. Fun for the whole family!]],
  },

  explodeAs                     = [[ATOMIC_BLAST]],
  footprintX                    = 4,
  footprintZ                    = 4,
  iconType                      = [[mahlazer]],
  idleAutoHeal                  = 5,
  idleTime                      = 1800,
  levelGround                   = false,
  mass                          = 791,
  maxDamage                     = 16000,
  maxSlope                      = 18,
  maxVelocity                   = 0,
  maxWaterDepth                 = 0,
  minCloakDistance              = 150,
  noChaseCategory               = [[FIXEDWING LAND SHIP SATELLITE SWIM GUNSHIP SUB HOVER]],
  objectName                    = [[raveparty.s3o]],
  onoffable						= true,
  script						= [[raveparty.lua]],
  seismicSignature              = 4,
  selfDestructAs                = [[ATOMIC_BLAST]],

  sfxtypes                      = {

    explosiongenerators = {
      [[custom:ARMBRTHA_SHOCKWAVE]],
      [[custom:ARMBRTHA_SMOKE]],
      [[custom:ARMBRTHA_FLARE]],
    },

  },

  side                          = [[ARM]],
  sightDistance                 = 660,
  smoothAnim                    = true,
  turnRate                      = 0,
  useBuildingGroundDecal        = true,
  workerTime                    = 0,
  yardMap                       = [[oooooooooooooooo]],

  weapons                       = {

    {
      def                = [[RED_KILLER]],
      onlyTargetCategory = [[SWIM LAND SINK FLOAT SHIP HOVER]],
    },
    {
      def                = [[ORANGE_ROASTER]],
      onlyTargetCategory = [[SWIM LAND SINK FLOAT SHIP HOVER]],
    },
    {
      def                = [[YELLOW_SLAMMER]],
      onlyTargetCategory = [[SWIM LAND SINK FLOAT SHIP HOVER]],
    },
	{
      def                = [[GREEN_STAMPER]],
      onlyTargetCategory = [[SWIM LAND SINK FLOAT SHIP HOVER]],
    },	
	{
      def                = [[BLUE_SHOCKER]],
      onlyTargetCategory = [[SWIM LAND SINK FLOAT SHIP HOVER]],
    },	
	{
      def                = [[VIOLET_SLUGGER]],
      onlyTargetCategory = [[SWIM LAND SINK FLOAT SHIP HOVER]],
    },		
  },


  weaponDefs                    = {

    RED_KILLER = {
      name                    = [[Red Killer]],
      accuracy                = 750,
      areaOfEffect            = 192,
      cegTag                  = [[vulcanfx]],
      craterBoost             = 0.25,
      craterMult              = 0.5,

      damage                  = {
        default = 2000,
        planes  = 2000,
        subs    = 100,
      },

      explosionGenerator      = [[custom:lrpc_expl]],
      holdtime                = [[1]],
      impulseBoost            = 0.5,
      impulseFactor           = 0.2,
      interceptedByShieldType = 1,
      range                   = 6200,
	  rgbColor                = [[1 0.1 0.1]],
      reloadtime              = 1,
      renderType              = 4,
	  size					  = 15,
	  sizeDecay				  = 0.03,
      soundHit                = [[weapon/missile/liche_hit]],
      soundStart              = [[weapon/cannon/big_begrtha_gun_fire]],
	  stages				  = 30,
      startsmoke              = [[1]],
      turret                  = true,
      weaponType              = [[Cannon]],
      weaponVelocity          = 1100,
    },
	
    ORANGE_ROASTER = {
      name                    = [[Orange Roaster]],
      accuracy                = 750,
      areaOfEffect            = 256,
      cegTag                  = [[vulcanfx]],
      craterBoost             = 0.25,
      craterMult              = 0.5,
	  
	  customParams        	  = {
	    setunitsonfire = "1",
		burntime = 240,
	  },

      damage                  = {
        default = 300,
        planes  = 300,
        subs    = 15,
      },

      explosionGenerator      = [[custom:firewalkernapalm]],
      holdtime                = [[1]],
      impulseBoost            = 0.2,
      impulseFactor           = 0.1,
      interceptedByShieldType = 1,
      range                   = 6200,
	  rgbColor                = [[0.9 0.3 0]],
      reloadtime              = 1,
      renderType              = 4,
	  size					  = 15,
	  sizeDecay				  = 0.03,
      soundHit                = [[weapon/missile/nalpalm_missile_hit]],
      soundStart              = [[weapon/cannon/big_begrtha_gun_fire]],
	  stages				  = 30,
      startsmoke              = [[1]],
      turret                  = true,
      weaponType              = [[Cannon]],
      weaponVelocity          = 1100,
    },
	
    YELLOW_SLAMMER = {
      name                    = [[Yellow Slammer]],
      accuracy                = 750,
      areaOfEffect            = 256,
      cegTag                  = [[vulcanfx]],
      craterBoost             = 0.25,
      craterMult              = 0.5,

      damage                  = {
        default = 800,
        planes  = 800,
        subs    = 40,
      },

      explosionGenerator      = [[custom:100rlexplode]],
      holdtime                = [[1]],
      impulseBoost            = 1.25,
      impulseFactor           = 2.5,
      interceptedByShieldType = 1,
      range                   = 6200,
	  rgbColor                = [[0.7 0.7 0]],
      reloadtime              = 1,
      renderType              = 4,
	  size					  = 15,
	  sizeDecay				  = 0.03,
      soundHit                = [[weapon/cannon/earthshaker]],
      soundStart              = [[weapon/cannon/big_begrtha_gun_fire]],
	  stages				  = 30,
      startsmoke              = [[1]],
      turret                  = true,
      weaponType              = [[Cannon]],
      weaponVelocity          = 1100,
    },	

    GREEN_STAMPER = {
      name                    = [[Green Stamper]],
      accuracy                = 750,
      areaOfEffect            = 512,
      cegTag                  = [[vulcanfx]],
      craterBoost             = 0.25,
      craterMult              = 0.5,

      damage                  = {
        default = 500,
        planes  = 500,
        subs    = 25,
      },

      explosionGenerator      = [[custom:blobber_goo]],
      holdtime                = [[1]],
      impulseBoost            = 0.7,
      impulseFactor           = 0.5,
      interceptedByShieldType = 1,
      range                   = 6200,
	  rgbColor                = [[0.1 1 0.1]],
      reloadtime              = 1,
      renderType              = 4,
	  size					  = 15,
	  sizeDecay				  = 0.03,
      soundHit                = [[explosion/ex_large4]],
      soundStart              = [[weapon/cannon/big_begrtha_gun_fire]],
	  stages				  = 30,
      startsmoke              = [[1]],
      turret                  = true,
      weaponType              = [[Cannon]],
      weaponVelocity          = 1100,
    },	

    BLUE_SHOCKER = {
      name                    = [[Blue Shocker]],
      accuracy                = 750,
      areaOfEffect            = 256,
      cegTag                  = [[vulcanfx]],
      craterBoost             = 0.25,
      craterMult              = 0.5,

      damage                  = {
        default        = 10000,
        commanders     = 100,
        empresistant75 = 2500,
        empresistant99 = 100,
      },

      explosionGenerator      = [[custom:POWERPLANT_EXPLOSION]],
      holdtime                = [[1]],
      impulseBoost            = 0,
      impulseFactor           = 0,
      interceptedByShieldType = 1,
      paralyzer               = true,
      paralyzeTime            = 10,
      range                   = 6200,
	  rgbColor                = [[0.1 0.1 1]],
      reloadtime              = 1,
      renderType              = 4,
	  size					  = 15,
	  sizeDecay				  = 0.03,
      soundHit                = [[weapon/more_lightning]],
      soundStart              = [[weapon/cannon/big_begrtha_gun_fire]],
	  stages				  = 30,
      startsmoke              = [[1]],
      turret                  = true,
      weaponType              = [[Cannon]],
      weaponVelocity          = 1100,
    },

    VIOLET_SLUGGER = {
      name                    = [[Violet Slugger]],
      accuracy                = 750,
      areaOfEffect            = 512,
      cegTag                  = [[vulcanfx]],
      craterBoost             = 0.25,
      craterMult              = 0.5,

      damage                  = {
        default = 600,
        planes  = 600,
        subs    = 30,
      },

      explosionGenerator      = [[custom:riotballpluspurple]],
      holdtime                = [[1]],
      impulseBoost            = 0.2,
      impulseFactor           = 0.1,
      interceptedByShieldType = 1,
      range                   = 6200,
	  rgbColor                = [[0.7 0 0.7]],
      reloadtime              = 1,
      renderType              = 4,
	  size					  = 15,
	  sizeDecay				  = 0.03,
      soundHit                = [[weapon/aoe_aura]],
      soundStart              = [[weapon/cannon/big_begrtha_gun_fire]],
	  stages				  = 30,
      startsmoke              = [[1]],
      turret                  = true,
      weaponType              = [[Cannon]],
      weaponVelocity          = 1100,
    },	
	
  },


  featureDefs                   = {

    DEAD  = {
      description      = [[Wreckage - Disco Rave Party]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 16000,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[40]],
      hitdensity       = [[100]],
      metal            = 16000,
      object           = [[raveparty_dead.s3o]],
      reclaimable      = true,
      reclaimTime      = 16000,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

    HEAP  = {
      description      = [[Debris - Disco Rave Party]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 16000,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 8000,
      object           = [[debris3x3c.s3o]],
      reclaimable      = true,
      reclaimTime      = 8000,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ raveparty = unitDef })
