unitDef = {
  unitname               = [[terraunit]],
  name                   = [[Terraform]],
  description            = [[Spent: 0]],
  acceleration           = 0,
  brakeRate              = 0,
  buildCostEnergy        = 1000000,
  buildCostMetal         = 1000000,
  builder                = false,
  buildPic               = [[levelterra.png]],
  buildTime              = 1000000,
  canAttack              = false,
  capturable             = false,
  category               = [[TERRAFORM]],
  collisionVolumeOffsets = [[0 -1500 0]],
  collisionVolumeScales  = [[32 32 32]],
  collisionVolumeTest    = 1,
  collisionVolumeType    = [[box]],

  customParams           = {
    dontcount      = [[1]],
    mobilebuilding = [[1]],
  },

  footprintX             = 2,
  footprintZ             = 2,
  idleAutoHeal           = 0,
  idleTime               = 1800,
  isFeature              = false,
  levelGround            = false,
  mass                   = 500000,
  maxDamage              = 1000000,
  maxSlope               = 255,
  maxVelocity            = 0,
  minCloakDistance       = 0,
  objectName             = [[debris1x1b.s3o]],
  reclaimable            = false,
  script                 = [[nullscript.lua]],
  seismicSignature       = 4,
  selfDestructCountdown  = 1,
  side                   = [[ARM]],
  sightDistance          = 0,
  airSightDistance		 = 0,
  stealth                = true,
  turnRate               = 0,
  upright                = false,
  workerTime             = 0,
  yardMap                = [[yyyy]],
}

return lowerkeys({ terraunit = unitDef })
